### ISSUE TITLE
Error when saving changes in edited device

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1160]
Error shows up when saving edited Rack in Asset module /assets/dc/edit/device/-devNo-/.
My mistake was to forget to put invoice number when creating a device (rack). After that I decided to complete the form by providing the missing id number. When clicking on Save button on the bottom of the page I get "Asset with this Barcode already exists." The strange thing is the barcode textfield was and remains empty.
Affects Ralph 2.0.1

**Comment by mkurek** [comment]
It's bug in assets - when you don't fill barcode field, it's saved as empty string. This field is unique and only one row could have empty string for this field ("" == "", unlike null != null). It's fixed in Ralph NG.
