### ISSUE TITLE
Discovery: Cannot delete device because of its empty name

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1165]
Cannot edit and delete one of the devices because of its empty name ->
/admin/discovery/device/

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/4702397/b015d9a6-5862-11e4-93cb-3ad4c1ea139d.JPG)

**Comment by vi4m** [comment]
You can edit this device even when the name is empty. Just try to focus and click on this place :)

**Comment by damian1976** [comment]
Ok. Understood:)
