### ISSUE TITLE
Rack "parent" is Unknown

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1170]
My rack "parent" is unknown. It is an error or some information is missing. What should be the parent of the rack? (venture, data center, etc?)
![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/4754663/b65d97fe-5abf-11e4-8f95-008e52e63668.JPG)

**Comment by vi4m** [comment]
device type = data center

**Comment by damian1976** [comment]
Ok. Understood :)
