### ISSUE TITLE
Scan: ssh_linux plugin problem

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1171]
I'm trying to scan given IP in a defined network.
In the settings file I have defined SSH_USER and SSH_PASSWORD used to login onto this machine.
I didn't touch SNMP_PLUGIN_COMMUNITIES variable which is  ['public'] by default.

I get the following error:
```
ralph.scan: SNMP name and community is missing. Forcing autoscan.
ralph.scan.plugins.ssh_linux: Running plugin ralph.scan.plugins.ssh_linux.
ralph.scan.plugins.ssh_linux: Exception occured in plugin ssh_linux and address __IP__
ralph.scan.plugins.ssh_linux: No snmp found
```
Do you know why is that?

**Comment by vi4m** [comment]
Could you run snmpwalk on this device and make sure the port is open?

**Comment by damian1976** [comment]
The problem is already solved long time ago.  The strange thing was tightening ssh with snmp i. e. checking for snmp community before logging onto remote machine. Our machines do not have snmp configured. The appropriate fragment of the code has been commented out.

**Comment by damian1976** [comment]
In case SNMP is not configured the problem can be solved by commenting out lines 232...247 in src/ralph/scan/plugins/ssh_linux.py

**Comment by damian1976** [comment]
My proposition is to put a new value to settings called i.e. SNMP_CONFIGURED  = True/False.
Depending o that ssh_linux plugin (and possibly others) would check inside for SNMP. In my case (SNMP_CONFIGURED = False) the above lines in the code would be skipped and the code execution should carry on.

**Comment by freeseacher** [comment]
we have the same problem. snmp on host is not available at all. and there is no reason to install it.

**Comment by vi4m** [comment]
As @damian1976 said we're open to pull request as damian suggested.

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
