### ISSUE TITLE
Ralph Core/Addresses Tab - management IP address empty

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1197]
Although device has one of its IP addresses selected as **management** in the admin module

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/5125658/e4f9bb7a-70c6-11e4-8be3-a096ee341fcb.JPG)

it is not visible in the  **/ui/search/addresses/?** list

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/5125738/8447c168-70c7-11e4-9ee0-32ba4bd6b4b0.JPG)

**Comment by vi4m** [comment]
Still having this issue?

**Comment by damian1976** [comment]
In the current version of admin module this checkbox doesn't exist anymore. However, in the Core @ ui/racks/rack_id/addresses/device_id? there is a section written in bold called "Management address" which is filled with IP address. And what happens this address apperars in the rack devices list (/ui/racks/rack_id/addresses/) not in "Management" column (which is empty), but in "IP addresses" one.

**Comment by damian1976** [comment]
OK. I most probably found the reason. The ip address typed in "Management address" section (/ui/racks/rack_id/addresses/device_id?)  is inserted in **discovery_ipaddress** table where device_id column equals current device id. In the same time the column **management_id** in **discovery_device** table is empty. This column should point to **discovery_ipaddress** table **id** column.And then,  when building addresses list the manahgement ip address should be selected by the above relation.
Tables relation in this context is ambigous. discovery_ipaddress table has the relation with discovery_device (device_id -> id) and reverse; discovery_device  has identical relation (management_id -> id).
One of them seems to be redundant.
**_Update:**_
When I update the management_id column in  discovery_device table from NULL to appropriate id from discovery_ipaddress table the "Management" column in addresses list shows up the address. But the second column "IP addresses" also presents it ....It should probably not.

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
