### ISSUE TITLE
Invalid UI behaviour -> wrong page address building

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1238]
Observed incorrect UI behaviours are as follows:

1/ Go to the following: Core-> Ventures -> choose a Venture from the list, then device, then Scan tab, then address to scan, and finally under the menu, where 'Search, Services', and other items are (more or less below the 'Rack' item) there is a hyperlink starting from Ventures, then slash and then Venture name. When you click on it you will get "Page not found" server error page

2/ Second option: Instead of clicking on the hyperlink, click on the Venture name in the list (on the left side of the WWW page).
You will get the error written in red "Requested IP address is invalid or unknown."
This is because it tries to reach wrong page address:  ui/ventures/my_venture/scan// instead of: ui/ventures/my_venture/info/

**Comment by vi4m** [comment]
Ralph2 is now unsupported. Please upgrade to the Ralph 3 version if unsure.
