### ISSUE TITLE
Ralph Core/Racks tab/DC visualization: Cannot visualize DC grid. Page not found (404)

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1246]
The problem is as follows:
- DC has been created using admin/ralph_assets/add new data center function
- Racks have been created using admin/ralph_assets/add rack which point to DC just created
- The DC name includes spaces and looks similarily to "Server room at Main Street"
- Deprecated ralph dc was also given and points to Discovery/Devices/Server room at Main Street (created earlier) with the model of type 'data center'
- Now going back to Core/Racks on the left hand side I can see the tree structure containing this DC with some racks. 

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/5503972/e630798e-877d-11e4-92a6-b49612100003.JPG)

When clicking on DC name, namely, "Server room at Main Street"  I get the error

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/5503913/1246f404-877d-11e4-9912-d05e9475c93e.JPG)

BTW: Can someone comment on this: Why is there 'Unknown' in the tree structure?

**Comment by damian1976** [comment]
The problem are "spaces" in the DC name. In my opinion hyperlink instead of containing DC name should consist of DC ID. In this way the problem with spaces will dissapear. The other aspect of it is that other hyperlinks in the system are built using ids, not names. This is an example of inconsistence.

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
