### ISSUE TITLE
Obstacles when adding a new network

### ISSUE THREAD

**Issue by MahmoudTaher** [allegro/ralph#1250]
Hi,

I installed Ralph 2.2.0, And when to add network from (Admin>Discovery>Networks)  it required fill some fields, Include choosing at least one rack to add new network. But when add rack and in device environment attempt fails, I tried too much to add it but to no avail.

So please help how can i add new rack and new network.

![ralph_20141222_issue_1](https://cloud.githubusercontent.com/assets/9685363/5560640/b41c4d84-8da3-11e4-93bf-dac0576c6504.png)
![ralph_20141222_issue_2](https://cloud.githubusercontent.com/assets/9685363/5560641/b41f5b8c-8da3-11e4-92dd-a331dd40a355.png)

**Comment by vi4m** [comment]
How did you install ralph ? using docker or generic installation(longer one) ?

**Comment by vi4m** [comment]
If not using docker, there is quick and easy way to solve this. 

1. Download this gist file https://gist.github.com/vi4m/51f30b8adb752be03621 and save it in the /home/ralph/fixtures.py
2.Go to installation directory (/home/ralph) and activate virtualenv (source /home/ralph/bin/activate) and type python fixtures.py

It will create default Service and default environment which you can use further

**Comment by MahmoudTaher** [comment]
I installed it using docker.. Are this way work with docker also?

**Comment by vi4m** [comment]
I will push the newer docker image so it has this command line tool embedded

**Comment by vi4m** [comment]
Now update your docker instance with newer ralph version with `docker pull vi4m/ralph:latest`

**Comment by vi4m** [comment]
And upgrade your database with `docker run -P -t -i -volumes-from mysql_data vi4m/ralph:latest /home/ralph/upgrade_mysql.sh`

**Comment by vi4m** [comment]
Remeber to stop ralph before doing this (Ctrl+C and wait for shutdown)

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
