### ISSUE TITLE
ImportError: cannot import name CascadeModelChoiceField when running ralph run_gunicorn

### ISSUE THREAD

**Issue by XANi** [allegro/ralph#1273]
I've installed fresh install on centos 6 (python 2.7.5 from centos scl) from 9fed160, everything went without errors (btw install instruction seems to be out of date with latest as i needed to make install ralph_assets too), synced and false migrated db etc but when i do  `ralph run_gunicorn` I get

    2015-01-16 14:07:14 [21451] [ERROR] Error handling request
    Traceback (most recent call last):
      File "/home/ralph/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 102, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/home/ralph/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
        return self.application(environ, start_response)
      File "/home/ralph/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
        response = self.get_response(request)
      File "/home/ralph/lib/python2.7/site-packages/django/core/handlers/base.py", line 177, in get_response
        response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
      File "/home/ralph/lib/python2.7/site-packages/django/core/handlers/base.py", line 222, in handle_uncaught_exception
        if resolver.urlconf_module is None:
      File "/home/ralph/lib/python2.7/site-packages/django/core/urlresolvers.py", line 342, in urlconf_module
        self._urlconf_module = import_module(self.urlconf_name)
      File "/home/ralph/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
        __import__(name)
      File "/home/ralph/src/ralph/src/ralph/urls.py", line 23, in <module>
        from ralph.discovery.api import (
      File "/home/ralph/src/ralph/src/ralph/discovery/api.py", line 39, in <module>
        from ralph.ui.views.common import _get_details
      File "/home/ralph/src/ralph/src/ralph/ui/views/common.py", line 87, in <module>
        from ralph.ui.forms.devices import (
      File "/home/ralph/src/ralph/src/ralph/ui/forms/devices.py", line 8, in <module>
        from ajax_select.fields import (
    ImportError: cannot import name CascadeModelChoiceField

on first request.

2.1.0 from pip installed fine but I got weird problem where I had to choose something for "service" field in "add device" dialog, but could not add service anywhere, so I wanted to try latest. I did total wipe (home virtualenv + DB) before installing from git.

**Comment by quamilek** [comment]
For testing Ralph installation we propose docker image installation, see here:  http://ralph.readthedocs.org/en/latest/installation.html#prebuilt-docker-image

**Comment by XANi** [comment]
I did but on parts I wanted to test (scan) I got 500:

    Request Method:	POST
    Request URL:	http://127.0.0.1:49172/ui/search/scan/10.0.2.13/
    Django Version:	1.4.16
    Exception Type:	KeyError
    Exception Value:	
    u'disc_queue'
    Exception Location:	/home/ralph/local/lib/python2.7/site-packages/django_rq/queues.py in get_connection, line 23
    Python Executable:	/home/ralph/bin/python
    Python Version:	2.7.3
    Python Path:	
    ['/home/ralph/bin',
     '/home/ralph/sources/bob-ajax-selects',
     '/home/ralph/sources/django_bob',
     '/home/ralph/sources/ralph/src',
     '/home/ralph/sources/ralph_assets/src',
     '/home/ralph/sources/ralph_pricing/src',
     '/home/ralph/lib/python2.7',
     '/home/ralph/lib/python2.7/plat-linux2',
     '/home/ralph/lib/python2.7/lib-tk',
     '/home/ralph/lib/python2.7/lib-old',
     '/home/ralph/lib/python2.7/lib-dynload',
     '/usr/lib/python2.7',
     '/usr/lib/python2.7/plat-linux2',
     '/usr/lib/python2.7/lib-tk',
     '/home/ralph/local/lib/python2.7/site-packages']
    Server time:	Fri, 16 Jan 2015 14:45:33 +0100

only thing I've done is adding env->dc, discovery queue "disc_queue", then network 10.0.2.0/24 with one terminator.

Then added IP/hostname to host and run "scan"

And that is why I tried to install it directly on machine, to not fiddle with docker while debugging.

**Comment by vi4m** [comment]
1. Easy way - use queue 'default' - no setup required
2. If you want to run worker on another machine just:
- Add queue name into the RQ_QUEUES_LIST(AFAIR) in the ~/.ralph/settings
- Run ralph rqworker [queue_name] to start additional worker

**Comment by XANi** [comment]
Might want add that to documentation as there is no mention that discovery queue must be named same. Or just add default discovery queue in initial database for "no setup required"

I just assumed queue "default" is "whatever didn't match any other queue"

**Comment by vi4m** [comment]
Thanks, we will make sure the init script will be included also in 'generic' ralph installation - currently only docker have some initials.
