### ISSUE TITLE
DC visualization: Wrong path is built

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1275]
When selecting DC from Core/Racks context the following path is built
'Racks / My_DC_Name'. When clicking on 'My_DC_Name' which points to
http://SITE/ui/racks/view/data_center_view?
I get 'Page not found' error.

![reseda_capture](https://cloud.githubusercontent.com/assets/9283029/5777941/60cb68e6-9d97-11e4-9fff-25c627332950.JPG)

**Comment by damian1976** [comment]
In my opinion My_DC_Name should point to http://SITE/ui/racks/view/My_DC_Name/ which is equivalent to clicking on 'My_DC_Name  in the navigation tree on the left hand side

**Comment by vi4m** [comment]
Can you fix it ? :)

**Comment by damian1976** [comment]
What do you mean ? :) I cannot do anything. The problem is on your side.

**Comment by vi4m** [comment]
We fixed it in newest release. Closing.
