### ISSUE TITLE
Rack visualization: Asset/device marked as "Deleted"  is drawn.

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1290]
Device is visualized despite being marked in /admin/ralph_assets/asset/asset_id as Deleted

**Comment by vi4m** [comment]
Did you remove it using GUI ?

**Comment by vi4m** [comment]
Asserts -> Actions -> Delete

**Comment by xliiv** [comment]
Perhaps this:
https://github.com/allegro/ralph_assets/pull/597
would solve the problem.

**Comment by damian1976** [comment]
What I meant wasn't physical removal of an asset but setting the appropriate checkbox:
![reseda_capture](https://cloud.githubusercontent.com/assets/9283029/6571994/a2ce7864-c70e-11e4-8925-c2741b1690a4.JPG)
In other words setting this checkbox doesn't do what it says. The asset is still visualized

**Comment by mkurek** [comment]
working right now. closing.
