### ISSUE TITLE
No distributions matching the version for ralph-assets==2.4.0 (from ralph==2.2.0)

### ISSUE THREAD

**Issue by hzome** [allegro/ralph#1330]
Downloading/unpacking ralph-assets==2.4.0 (from ralph==2.2.0)
  Could not find a version that satisfies the requirement ralph-assets==2.4.0 (from ralph==2.2.0) (from versions: 1.0.0, 1.0.1, 1.2.13, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 2.0.0-rc1, 2.2.0, 2.3.0)
Cleaning up...
No distributions matching the version for ralph-assets==2.4.0 (from ralph==2.2.0)
Storing debug log for failure in /home/ralph/.pip/pip.log
make: *** [install] Error 1

**Comment by vi4m** [comment]
Please use docker image - pypi packages are 6 months old.
