### ISSUE TITLE
pkg_resources.VersionConflict: (pytz 2013b (/home/ralph/lib/python2.7/site-packages), 

### ISSUE THREAD

**Issue by hzome** [allegro/ralph#1331]
(ralph)ralph@ubuntu:~/project$ ralph makeconf
Traceback (most recent call last):
  File "/home/ralph/bin/ralph", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ralph/local/lib/python2.7/site-packages/pkg_resources.py", line 2720, in <module>
    parse_requirements(__requires__), Environment()
  File "/home/ralph/local/lib/python2.7/site-packages/pkg_resources.py", line 592, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (pytz 2013b (/home/ralph/lib/python2.7/site-packages), Requirement.parse('pytz>=2013.6'))

**Comment by vi4m** [comment]
Did you try docker? We don't support currently other ways of installation

**Comment by hzome** [comment]
ok docker no problem

**Comment by vi4m** [comment]
Try docker or newest release http://ralph.readthedocs.org/en/latest/changes.html

**Comment by Tontaube** [comment]
no ralph without docker? no ralph on openbsd, freebsd, other unix'es?

**Comment by mkurek** [comment]
@Tontaube you could always install it directly from source code (http://ralph.readthedocs.org/en/latest/installation.html#installing-ralph-advanced-installation)

Either way, we're suggesting to check out Ralph NG (http://ralph-ng.readthedocs.org/) (Ralph 2 will soon be no longer supported).

**Comment by Tontaube** [comment]
@mkurek thank you very much for your reply. I will check out ralph ng, as I didn't run into it before. Thx!

**Comment by bencheikh** [comment]
hello everyone,
I have the same problem trying to install ralph 2.x , I don't want to use Docker.
Traceback (most recent call last):
  File "/usr/local/bin/ralph", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 644, in resolve
    raise VersionConflict(dist, req)
pkg_resources.VersionConflict: (requests 2.4.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.10.0,!=2.12.2'))

Do i have to use Docker for the install and why ? or is there any new method ?
By the way i saw that you "do not work anymore on old 2.x branch from develop branch. So i i start by installing an old version do i have to start the migration to 3 ?

**Comment by vi4m** [comment]
@bencheikh don't use old version, since we're going to deprecate it in a next few weeks. It just doesn't make sense to migrate to the new version.

**Comment by bencheikh** [comment]
@vi4m  thank you for your answer but ralph 3 is not supported on Debian Jessie so what should i do
