### ISSUE TITLE
ability to scan SQL databases and add to CMDB

### ISSUE THREAD

**Issue by whoisearth** [allegro/ralph#1347]
from mkurek:
@whoisearth we have some internal basic version of MSSQL plugin (to get all databases) - there should be no problem to add this to ralph core after some tweaks to make it more generic. Could you add an issue on github for that (as a reminder for us)?

**Comment by vi4m** [comment]
@mkurek what to do with that?

**Comment by mkurek** [comment]
Currently i don't have time to tweak it and push this to open source. Maybe someone other from @pylabs-team could do this?

**Comment by vi4m** [comment]
No work here, so closing.
