### ISSUE TITLE
Translating Ralph into Chineese

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1348]
This is design document how to translate Ralph into other languages. 

Please update this issue with comments about missing or hard translation areas.

**Comment by deejay1** [comment]
Hmm, IMHO
 * all models should have proper Meta with both verbose names
 * templates need to have their strings inside {% trans %}
 * angularjs parts should propably use angular-gettext

For starters we could run podebug(http://docs.translatehouse.org/projects/translate-toolkit/en/stable-1.12.0/commands/podebug.html) on the standard django generated gettext catalogue and see what's missing

**Comment by flashput** [comment]
I have send a language request on transifex, and I'm willing to do the translation if needed

**Comment by vi4m** [comment]
@deejay1 what about the assets module? I imported this file and it's roughly touch the user interface, mostly admin gui.

**Comment by vi4m** [comment]
@deejay1  How to keep all modules on transifex for translations ?

**Comment by deejay1** [comment]
@vi4m We can either go with creating a new resource or make a proper allegrogroup organization and assign the projects there creating a new ralph assets project (AFAIR they are separate repositories)

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
