### ISSUE TITLE
Modification of ci type name /region name causes entities disappeared in front end pages

### ISSUE THREAD

**Issue by flashput** [allegro/ralph#1349]
***Case 1***
**admin page**
![qq20150402-1](https://cloud.githubusercontent.com/assets/11661814/6965392/af9a80c4-d983-11e4-9379-293ce9477c05.png)

**front end before modify anything**
![qq20150402-2](https://cloud.githubusercontent.com/assets/11661814/6965404/cacd6c80-d983-11e4-96de-62417771cafd.png)
**modify Environment to Env**
![qq20150402-3](https://cloud.githubusercontent.com/assets/11661814/6965475/4778e2dc-d984-11e4-8119-fd796cd96fbe.png)
**after modify**
![qq20150402-4](https://cloud.githubusercontent.com/assets/11661814/6965487/65b061d0-d984-11e4-9298-09b8e03f0e6d.png)
**front end after modify** 
![qq20150402-5](https://cloud.githubusercontent.com/assets/11661814/6965509/a0ba12c6-d984-11e4-8ee0-c47f3399916c.png)

**As we can see , Environment entity 'Default environment'  disappeared after the modification, no environment available for selection**

***Case 2***
**admin page**
![qq20150402-6](https://cloud.githubusercontent.com/assets/11661814/6965628/b96308b8-d985-11e4-8d6b-e132e02434ac.png)

**front end page**
![qq20150402-7](https://cloud.githubusercontent.com/assets/11661814/6965643/d8031fb0-d985-11e4-9407-15a9624b9d82.png)
**modify region name to other**
![qq20150402-8](https://cloud.githubusercontent.com/assets/11661814/6965768/81a095de-d986-11e4-9ce5-04403cab9314.png)
**after modify**
![qq20150402-9](https://cloud.githubusercontent.com/assets/11661814/6965779/8e0598a6-d986-11e4-8bfd-bcadb844de67.png)
**front end after modify** 
![qq20150402-10](https://cloud.githubusercontent.com/assets/11661814/6965802/a8bc18c8-d986-11e4-8537-cacd3262f7f6.png)

**As we can see , after the modification, no region available for selection**

***new added regions are also not available for selection***

**Comment by vi4m** [comment]
Thanks for bug report @ar4s can you confirm it?

**Comment by ar4s** [comment]
@flashput you must checked ``Default region`` in user's profile.

**Comment by ar4s** [comment]
``ralph/discovery/models_device.py``
```
class DeviceEnvironmentManager(db.Manager):
    def get_query_set(self):
        return super(DeviceEnvironmentManager, self).get_query_set().filter(
-            type__name=models_ci.CI_TYPES.ENVIRONMENT,
+           type__id=models_ci.CI_TYPES.ENVIRONMENT.id,
            state=models_ci.CI_STATE_TYPES.ACTIVE,
        )
```

@zefciu please change to something like that. The problem is currently when Environment (CI type) renamed and in the code we match by name not by id.

**Comment by mkurek** [comment]
@flasput & @ar4s - there is setting for default region in ralph settings: `DEFAULT_REGION_NAME = 'Default region'` (https://github.com/allegro/ralph/blob/develop/src/ralph/settings.py#L407)

@flashput change default region name in your settings to `Default regionA` and regions should work again.

**Comment by flashput** [comment]
thanks for the reply. I'll try

**Comment by flashput** [comment]
User can access multi-regions( must be explicitly configured at user profile settings page).
There is a default region for everyone(configured at settings.py/DEFAULT_REGION_NAME), users who do not have specific-region-settings will be placed in this region. 
Is that right?

**Comment by mkurek** [comment]
@flashput yes

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
