### ISSUE TITLE
vmware -> support vcenter!

### ISSUE THREAD

**Issue by bzed** [allegro/ralph#1372]
Inventories of running machines should only be done via the vcenter server. Thats the only supported way, also the vcenter knows about the machines which are running where.

```
                if 'vcenter' in server_conn.get_server_type().lower():
                    raise NoMatchError(
                        "It is `VMware vCenter Server`. To save real "
                        "hypervisor - VM connecion you should scan only "
                        "VMware ESXi servers.",
```

**Comment by vi4m** [comment]
Could you make pull request for that?

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
