### ISSUE TITLE
DC View/Assets: When renaming Rack name, old rack name is not removed

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1374]
As in the issue title, when renaming Rack Name in DC View the old rack (name) is not removed

**Comment by damian1976** [comment]
The scenario can be as follows:
1/ Create 3 racks: rack_1, rack_2, rack_3
2/ Try to change rack_1 to rack_3 and rack_3 to rack_1 by 
   2a/ renaming rack_3 to rack_4, then 
   2b/ rack_1 to rack_3

When doing step 2b the erros message occurs saying rack_3 already exists (we just renamed it to rack_4......:( )

**Comment by vi4m** [comment]
To check

**Comment by ar4s** [comment]
https://github.com/allegro/ralph_assets/pull/667 resolved this issue

**Comment by damian1976** [comment]
The error still exists. Please follow the steps above (1, 2 2a, 2b) to check this out. Moreover. when removing racks in Admin > Assets > Racks the rack is note removed from Discovery > Devices
