### ISSUE TITLE
DC View: Wrong title visualization when rotating the rack about 180 degrees

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1392]
The name is not clipped as it is in default rack position

![tucor](https://cloud.githubusercontent.com/assets/9283029/7389340/44707f8e-ee6d-11e4-8ee3-2213fbc6e4a0.jpg)

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
