### ISSUE TITLE
Rack assets/devices are not moved, when rack location (DC, server room) is changed

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1393]
When changing rack DC and/or server room in admin/assets the assets/devices  belonging to this rack are not moved either.
If, in turn I want to change location using group "Edit Location" in assets/dc/search I get the error message saying I can move only blade servers.
How to move the whole rack with its content to other location (DC & server room & probably a warehouse too)

**Comment by vi4m** [comment]
go to assets -> select some assets -> bulk actions -> bulk move (afair)

**Comment by damian1976** [comment]
Yes, this is exactly what I'm doing in assets/dc/search , then "Bulk actions/Edit location" button. 
I can move only blades. Otherwise I get the error message.

**Comment by mkurek** [comment]
Thats because asset has assigned data center, server room, rack etc separately. This will be fixed in NG model (where asset will only have rack assigned, rack will be assigned to server room, server room to DC).
