### ISSUE TITLE
Environment is not valid for Service Catalog when adding devices

### ISSUE THREAD

**Issue by flashput** [allegro/ralph#1396]
![qq20150505-1](https://cloud.githubusercontent.com/assets/11661814/7469162/eca4f6ce-f342-11e4-9b48-e27be48f1482.png)

When adding devices, no Environment can be used , though there are Environments available for select.
Error message also does not contain any useful information

**Comment by mkurek** [comment]
Do you have connected service with environment in cmdb (go to your service in CMDB, then Relations tab)? In such relation service should be parent, environment child and relation kind 'Contains'.

**Comment by flashput** [comment]
No, I will try now.
And it really get me confused. 
I would suggest only valid Environments can be presented

**Comment by mkurek** [comment]
Right now only valid environments are displayed.
