### ISSUE TITLE
autoscan will not work as wanted in CentOS

### ISSUE THREAD

**Issue by flashput** [allegro/ralph#1397]
![qq20150505-3](https://cloud.githubusercontent.com/assets/11661814/7469339/03c28ec8-f345-11e4-9c7a-703a2887e86e.png)

Before do any scan, serival icmp-ping operation will be performed first. 
If all pings are failed. host will be judged as not exist.
here is the code in ralph
![qq20150505-5](https://cloud.githubusercontent.com/assets/11661814/7469365/552ab844-f345-11e4-845a-91e11266a757.png)

but in CentOS , only processes running as root can send icmp messages, which means the ping operation will never get TRUE if ralph is not running as root.

![qq20150505-4](https://cloud.githubusercontent.com/assets/11661814/7469356/39a7a6cc-f345-11e4-8e49-4597fa27836d.png)

**Comment by mkurek** [comment]
Try to use setcap (http://ralph.readthedocs.org/en/latest/installation.html#installing-ralph-advanced-installation)

**Comment by flashput** [comment]
![qq20150505-6](https://cloud.githubusercontent.com/assets/11661814/7469727/61a082b2-f349-11e4-9a16-cc418e39c018.png)

**Comment by mkurek** [comment]
you use setcap on `/usr/bin/python2.7` but your python is probably in `/home/ralph/bin/python` - try to use setcap on it.

**Comment by flashput** [comment]
that works , thanks
