### ISSUE TITLE
Network autoscan page, 404 links found

### ISSUE THREAD

**Issue by flashput** [allegro/ralph#1399]
![Http 404 Page](https://cloud.githubusercontent.com/assets/11661814/7507317/a836f8ca-f4a0-11e4-9853-a423ca7693c1.png)

when click Device name, I got Http 404

Page not found (404)
Request Method: GET
Request URL:    http://127.0.0.1:8000/ui/networks/15/info/58

**Comment by vi4m** [comment]
If you display this device via core ui do you see "Detected changes" on the top of edit form?

**Comment by vi4m** [comment]
I will close it for now, because all  theeforts go for Ralph NG now.
