### ISSUE TITLE
Ralph 3.0 screenshots

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1400]
![ralph-3](https://cloud.githubusercontent.com/assets/552398/7513812/8b33c912-f4b7-11e4-9f7f-129efeb334b4.png)

**Comment by deejay1** [comment]
Looks a bit heavy IMHO

**Comment by vi4m** [comment]
It's just admin panel with django-suit

**Comment by vi4m** [comment]
This is new, modern Objects hierarchy for BackOffice, DataCenter, discovery and others.

![core](https://cloud.githubusercontent.com/assets/552398/7516204/dab42f7a-f4cd-11e4-87ea-175a159c8ac6.png)

**Comment by damian1976** [comment]
Ok for me

**Comment by vi4m** [comment]
@ar4s Why Rack field is CharField? ;-)

**Comment by vi4m** [comment]
@ar4s and ServiceEnv - looks like overengineering. So when i add `Service`, and `Environment` set like `prod`, `test`, `preprod`, then i have 3rd step to choose the environments used by this particular `Service`? How many times is this gonna happen? Why not maintain global set of environments and that's it ?

**Comment by damian1976** [comment]
Just an idea: what do you think about adding url (to specification web page for example) and/or image (device image) for DCAsset?

**Comment by vi4m** [comment]
We have had some Attachment object for such a pictures. What has happened?

**Comment by vi4m** [comment]
Specification url is a good idea, but on model itself, not asset.

**Comment by damian1976** [comment]
pics can be useful especially  for chassises where precise layout can't be reflected in DCView (i.e. http://e.huawei.com/~/media/EBG/Images/product/server/eh/e9000/E9000-c1.jpg)

**Comment by mkurek** [comment]
@vi4m rack will be changed to foreign key tomorrow. About service & env - it'll be much more easier than now (you define environments once, and then, when creating service you choose what environments does this service "contains"). When you define you service-envs like this, on asset form you'll have just one field in which you'll choose already associated pair of service-env (ex. "Load Balancing - prod" etc).

**Comment by vi4m** [comment]
@mkurek I'd agree if its managed in easy and straightforward way

**Comment by ar4s** [comment]
@vi4m at first glance it seems to be unjustified design decision but relation between `Service` and  `Environments` is m2m and we use existed table `ServiceEnvironment` (by `through` option in `Service` model), thus we get simple way to:
- add new constraint between service-env (`ServiceEnv.objects.create(service=foo, env=bar)` or `Service.objects.environments.add([env_1, env_2])`)
- fetch envs to specific service (`ServiceEnv.objects.select_related('env').filter(service=s).values('env')`)
