### ISSUE TITLE
Add DCView/Rack edit mode

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1404]
It would be great to add **Edit mode** to DCView/Rack (/ui/dc/#/dc/dc_id/rack/rack_id) as it is done in DCView iself.
It this mode I could:
- edit all or some elements which are presented in Preview Mode
- move devices inside the rack (with SHIFT key I could move group of devices). Let's say: I made a mistake and positioned devices with 1 position too high. With this opiton I could easily move them to correct place without editing them one by one and changing **Position** manually

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
