### ISSUE TITLE
Importer

### ISSUE THREAD

**Issue by ar4s** [allegro/ralph#1409]
Create importer to new models. 
Main concepts: agnostic, generic.

Design example:

![image](http://yuml.me/diagram/class/[Reader]^-[CSVReader], [Reader]^-[FooReader], [Reader]^-[BarReader], [Reader]-[note:Some common interface {bg:wheat}], [Importer|__init__%28Reader reader_class%29], [Importer]uses -.->[Reader])

**Comment by ghost** [comment]
DONE:
- django-import-export integration for 2 models
- simple: manufacturer
- complex: dc-asset

TODO:
- replace PKs in dc-asset with natural-keys
