### ISSUE TITLE
New attachments 

### ISSUE THREAD

**Issue by ghost** [allegro/ralph#1457]
I'd like to add attachment to asset, let's say an image.
The image (and other attachments) should be visible on asset's page as a thumbnail.

@vi4m what do you think?

**Comment by damian1976** [comment]
Sometimes for the persons sitting behind the desk it's nice to be able (without going to DC) to see how given device looks like and read its specification . I had this problem and curiosity when adding devices (sometimes layout of blades in a chassis is unclear, etc.).
Mapping some kinds of layouts in ralph in 100 % is not possible. It this case the real device picture helps. As much as web url to device specification. Please look at the the following example:

![](http://e.huawei.com/~/media/EBG/Images/product/server/eh/e9000/E9000-c2.jpg)

The above information can be added in separate tab in DC Asset

**Comment by mkurek** [comment]
Attachments should be generic and there should be possibility to add attachment to every object in ralph (at lest at BaseObject level, but it'd great to add them for every object).

Resources: https://www.djangopackages.com/grids/g/attachments/
