### ISSUE TITLE
Visualization: Rack delete mechanism missing

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1461]
Rack delete mechanisms would be a nice and very helpfull feature.
Maybe "-" or "X" could be added (in Edit mode) to a pen and rotate icons (difficult, there's rather no space for that)
OR
when Shift is pressed+mouse is over the rack box it could probably change the color to red, then pop up window shows up with the appropriate message.
The existing info message "Please click to edit basic info about rack, click to rotate or just use drag and drop to edit position. Use Admin to edit DC properties."  could be supplement with the following description "Please use Shift key+Left mouse button to remove selected rack" or similar.

**Comment by vi4m** [comment]
Please reopen if still missing in Ralph3
