### ISSUE TITLE
Visualization: Negative numbers when displaying number of free slots in rack 

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1462]
Just a small remark: I heard the algorithm calculating number of free slots in rack in DCView you are using is complicated. So, not to complicate it more, it would be great to add (at the end of the algorihm) a condition checking whether returning number is positive or negative. In the latter please just return 0.

**Comment by mkurek** [comment]
Fixed in https://github.com/allegro/ralph/pull/2129
