### ISSUE TITLE
Configuration and settings 2.0

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1482]
# Background

We need to have simple and safe settings and configuration for Ralph. Relaying on bare settings from Django settings.py doesn't allow to:
- validate the data
- hint the users what is required to bootup the instance, and what's optional configuration
- separate application bootup settings such as mysql settings from optional configuration like some custom jira integration setting
# Definitions
## Configuration

Configuration is type of setting, that user can change, without administrators effort. Mostly it won't require restarting application. Examples:
- simple settings for ui
- enable/disable scan plugins, and its configuration
- transition types and settings
- jira creds, and integration settings
- profile settings, such as home page url

Any application `configuration`  should be stored in the central place(etcd), and in secure way, because can contains some confidential data.

All ralph instances will connect to etcd and manage configuration with the optional pub-sub notification to reload settings.
## Settings

Settings allows application to boot up, connect to the database and other required daemons,  and connect to the central configuration server, or other configuration backend to fetch `configuration settings`

Required settings are:
- ETCD_DSN
- DB_DSN
- REDIS_HOST
- REDIS_PORT
- REDIS_PASS
- DEBUG
- TIMEZONE
- LANG
- ALLOWED_HOSTS
- SECRET_KEY
# Implementation
## Docker

Environment variables for `settings` provided from commandline or `ralph.env` file allow to boot up and scale numer of ralph instances
## Ordinary installation
- Environment variables with RALPH_ prefix
- `ralph.yaml` file located in /etc/ralph/ or `~/.ralph` parsed and incorporated to the settings file
## Reloading

The idea is to subscribe to the configuraiton server(redis, etcd) for pub/sub notification and populated settings.\* django object 
# Examples
## Columns in change list configuration

```
COLUMNS_PRESET:{{ _meta.app_label }}_{{ _meta.model }} = [
    {'Accounting' : ['invoice', 'niw'] },
    {'DCO' : ['barcode', 'sn']}
]
```

**Comment by ghost** [comment]
Maybe a few of our requirements could be covered by:
https://github.com/EliotBerriot/django-dynamic-preferences/tree/master/dynamic_preferences
However the package should be reviewed because I haven't used it, so I have no opinion.

**Comment by vi4m** [comment]
Why not use redis ? 

Mixing general purpose RAM-limited key-value storage, with the sensitive and precious settings is IMO bad idea. 
Redis is RAM-limited. But we should be able to purge redis cache any time without worrying about losing persistent data. So it's good idea to use redis for cache data (sessions, reports generation, scanned data etc) which you can regenerate in cases of exceeding RAM limits or outage. Losing all the settings will be very bad idea. Even when you enable snapshotting to the disk you loose ability to separate "trash" data from precious data.

Why using etcd instead?

Etcd is build with HA in mind, using consesus alghoritm, not limited to RAM, designed for securely storing configuration information in a distributed systems.

**Comment by mkurek** [comment]
Redis is NOT RAM-limited - there is persistence option: http://redis.io/topics/persistence , http://oldblog.antirez.com/post/redis-persistence-demystified.html , http://www.slideshare.net/eugef/redis-persistence-in-practice-1  (however i didn't test it, but AFAIK any of us didn't test etcd (in production) either). 

We could separate data from trash data using separated redis DBs (but unfortunately we cannot set persistence only for specific DB: http://stackoverflow.com/questions/28419458/setting-persistence-off-rdb-only-for-specific-redis-db-and-not-the-whole-redis). 

When we use etcd it'll become another, tightly connected to ralph dependency, which we'll have to maintain (another "thing" to install, another "thing" to administrate/configure, another thing to provide HA (more servers, more costs)). 

It's good to think about HA of service/tool early, but: configuration/settings are not the thing which will have thousands of request/queries per seconds and probably in 99.9% of cases it'll be read operation (IMO we should cache this configuration/settings either way to not call etcd service to access every settings). BTW isn't redis build with HA in mind too?

In terms of security - it'd be easy to implement our own encryption mechanism, which will encrypt every value before sending it to redis and decrypt before using it in application. Encryption key could be stored in primary settings in file (we obviously have to store some settings there, ex. database connection settings, redis settings etc). 

And btw it would be good idea to design and implement everything in such way, that without connection to configuration/settings storage Ralph will work either way (at least in read-only mode), don't you think?

**Comment by vi4m** [comment]
Redis **is** RAM limited, you can't store more data then available RAM size.  Persistence is just a snapshotting solution which doesn't cover this issue.

**Comment by mkurek** [comment]
Yes - you're right here, but this argument does not make any sense when concerning settings/configuration. I doubt if our configuration/settings will exceed 1mb (and if you're worrying about memory, then how ralph should work when every settings are loaded into memory from file (regular django way)?). 

My only concern here is that we'll have to maintain **another, different** tool, learn it well to use it on production and provide support for our open source users in case of any problems concerning ralph-etcd cooperation.

**Comment by vi4m** [comment]
This argument is valid - we have shared redis instance, and it will overflow at some point in time, since it handles also our caches and in the future - redis queues. Taking this into account, we clearly seee that settings needs separate tool/instance.

**Comment by romcheg** [comment]
Closing a stale proposal. Settings have been re-done within the packaging initiative.
