### ISSUE TITLE
REP10: Scan

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1502]
# Introduction

Scanning interface in Ralph 3 should focus on
- simplicity
- performance
- extensibility

Lessons learned from Ralph 2:
- too complex modeling of components and connections trying to handle every possible model 
- too many plugins fighting for priority forcing user to decide which is better
- too strict scanning interface which requires modeling network, environment
- sn is not a good primary key for connecting devices
- scanning from python require some setcap python capabilities, but spawning ping each time is too time consuming
# General guidelines
- modular architecture which will shift plugins to the sysadmin scripts
- don't reinvent the wheel - nmap[https://nmap.org], zmap[https://zmap.io]
# Architecture details

We will introduce 2 actors -> observer and executor. Observer is triggered by UI/API/CLI action, just after adding ScanTask object, directly from ralph instance. 

Then observer  then triggers one or more executors tasks. Executor task is just another instance serving ralph_scanner project, which listens on RQ queue for observers requests.. Executor run prescan and scan plugins, merging it's outputs using priorities, just as in previous ralph version. Then the executor stores plugin output in the redis database. 

After each plugin finished, executor notifies observer about overall progres and output. Observer is still running and observing given executors progress, and updating ScanTask progress in the database. 

From the user perspective, autorefresh + generic data table view with "Progress column" and "Scan status" should be sufficient. Progress column is presenting ScanTask.progress field value. Autorefreshing of the UI could be a good addition.  

The difference is, executor knows nothing about ralph itself, about the internal models. 

This is the observer's  role to handle scan task output, and decide, if it's autowrite value to the database(if given ip exists, just write whitelisted fields values to the database without prompt(software packages and discovered compontens - without touching model(manual selected) and position). 
# Active/Inactive field

Optionally, we could update last_seen field, to show which hosts don't respond to requests.
# Agent interface

We should focus and provide only stable/usable scan plugins
- lshw plugin
- puppet plugin(facts)

**Comment by moimael** [comment]
Any ETA on this feature ? I'd love to have it implemented to start testing ng more extensively :)

**Comment by vi4m** [comment]
I can't promise any ETA, but - it's coming soon.

**Comment by delize** [comment]
Any update to this?

Also, I would like to confirm if there would be any iDrac funcationality with this scan method, like there is in 2.x versions.

**Comment by mkurek** [comment]
Hi @delize - yes - we're working on it right now in [ralph-cli](https://github.com/allegro/ralph-cli) repository. It's cli wrapper around Ralph's API, able to run various scripts (written in any language!) to fetch data from host (for example idrac, ilo etc - there will be predefined plugins for some platforms, but you'll be able to write and run your own) and push it to Ralph.

**Comment by vi4m** [comment]
#TODO: replace the contents with our in-house proposal.

**Comment by vi4m** [comment]
Replaced with: https://github.com/allegro/ralph-cli
