### ISSUE TITLE
Bo models exporter/importer part 2

### ISSUE THREAD

**Issue by ar4s** [allegro/ralph#1526]
- [ ] Transition
- [ ] TransitionsHistory
- [ ] Action - connected to #1525
- [ ] Attachment ?
- [ ] ReportOdtSource ?
- [ ] ReportOdtSourceLanguage ?
- [ ] CoaOemOs
- [ ] AssetOwner
- [ ] BudgetInfo ?
- [ ] Service (should be renamed in NG to sth else)

**Comment by mkurek** [comment]
Done
