### ISSUE TITLE
Fix docker-mysql encoding

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1538]
Default mysql (from docker) encoding isn't utf-8. We should set proper encoding in one of init scripts.

Temporary solution:

Create mysql.cnf file:

```
[client]
default-character-set=utf8

[mysql]
default-character-set=utf8


[mysqld]
collation-server = utf8_unicode_ci
init-connect='SET NAMES utf8'
character-set-server = utf8
```

Add it to mysql container using volumes in docker-compose.yml

```
db:
...
  volumes:
    - mysql.cnf:/etc/mysql/conf.d/mysql.cnf
```

**Comment by mkurek** [comment]
PR which fix it globally for docker-mysql: https://github.com/docker-library/mysql/pull/14

**Comment by vi4m** [comment]
@mkurek done?

**Comment by mkurek** [comment]
Not exactly - this docker-library issue is closed now, but there is no trivial way to set this in docker (ex. using single env variable).

**Comment by vi4m** [comment]
Cannot we just stick to the django init_command settings?

**Comment by mkurek** [comment]
It should work, but I'll have to test it.

**Comment by romcheg** [comment]
MySQL was removed from the official docker image.
