### ISSUE TITLE
Docs for the Relationship between rack/dc/other inventory info in Core and in Assets page

### ISSUE THREAD

**Issue by daniellingo** [allegro/ralph#1556]
As a newbie, I find it is quite confused to figure out what are the steps to 
- add a new dc
- add a new rack

== For adding a new dc (EXD) ==
By reading the demo data, I am kind of successfully creating a new dc with these steps
- add a new Data centers EXD in discovery section of Admin page
- add a new Device (EXD) with data center Model in discovery section of Admin page
- add a new Data centre (EXD) with selecting "Deprecated ralph dc: EXD" in ralph_asset section of Admin page

Finally, I got new dc (EXD) shows up both in Core page and Assets page

My question is, are these correct steps to create a new dc, any easier way to do that?

== For adding a new rack (EXD-rack01) ==
I was just adding a new rack in Assets page, it was very user friendly, however, it doesn't show up in Core page. 
Without trying the similar steps with creating new Dc, I just changed the name of demo rack01 in "DC A" in Assets page, and the surprise to me is Core page doesn't get updated.

My question is, is Core page Deprecated for DC/Rack, what is the reason of keeping them both show up in the ralph, anyway can do sync automatically, instead of duplicate work in Admin page?

Very appreciated for any input

**Comment by ghost** [comment]
Ad. "Data center creation"
This is the correct way of adding `data centers`. I agree with you it's not an easiest thing to do, but this is also one of reasons why RalphNG (https://github.com/allegro/ralph/tree/ng)  is under development.
On the other hand, data centers are not added quite often, so I'm with you ;) .
Speaking of new racks.. . The recommended way of this is by done by view:

```
Core > DC View > DC (pick one of existing) > edit tab (default is "preview")
Now you can click anywhere on the dc map to add the new rack correctly.
```

which is easy, I think.
I will add a section to documentation covering that topic.

**Comment by ghost** [comment]
Quick guide in doc.
https://github.com/allegro/ralph/pull/1565

**Comment by daniellingo** [comment]
Hi xliiv,

Thanks for the guide! For new racks, I think I was not clear on the description, let me put more details here, there are two sub pages in Core pages, Racks & DC view, after I followed the recommended way you mentioned, I need to assign the Server Room in the ralph_asset section of admin page, so that it can be properly pop up as one of option in the Assets page.

However, the Racks sub pages looks like out of sync with DC view sub pages, is Racks sub pages totally deprecated after ralph_assets module enabled, so that we can ignore this page?

**Comment by daniellingo** [comment]
Hi xliiv,

Thanks for the guide! For new racks, I think I was not clear on the description, let me put more details here, there are two sub pages in Core pages, Racks & DC view, after I followed the recommended way you mentioned, I need to assign the Server Room in the ralph_asset section of admin page, so that it can be properly pop up as one of option in the Assets page.

However, the Racks sub pages looks like out of sync with DC view sub pages, is Racks sub pages totally deprecated after ralph_assets module enabled, so that we can ignore this page?

**Comment by ghost** [comment]
I checked it and it's out of sync as you wrote. I'll fix it this week. Thanks for input :)
Here's the ticket: https://github.com/allegro/ralph/issues/1566

**Comment by daniellingo** [comment]
Thanks, man!

**Comment by ghost** [comment]
It looks like synchronization is already done.
The reason why it wasn't fired could be..  rack and/or data-center (which asset belongs to them )  doesn't have set 'Deprecated ralph rack' and `Deprecated ralph dc` (see admin page for confirmation).
