### ISSUE TITLE
`Rack` sub page is out of sync with `DC View`.

### ISSUE THREAD

**Issue by ghost** [allegro/ralph#1566]
Like the topic.. .

**Comment by vi4m** [comment]
So. What would we do ?

**Comment by ghost** [comment]
I have a fix for this on branch with unfinished tests.
Today I'm gonna finish it.

**Comment by vi4m** [comment]
@xliiv ping ;-)

**Comment by ghost** [comment]
I'm working on it. Test fails. :D

**Comment by mkurek** [comment]
@xliiv do you remember if it was fixed?

**Comment by ghost** [comment]
I think it was.
