### ISSUE TITLE
Mass adding asset

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1606]
- should be similar to mass adding in Ralph 2.0
- overwrite barcode and SN widgets to support multiline input
- save should validate uniqueness of barcodes/SNs, equal number of barcodes and SNs (equal number of lines - could be empty if asset doesn't have barcode or sn, but at least one should be specified) and if it's valid save multiple assets
- after save show message that X assets were created with following barcodes/SNs

At the end (not necessarily in one PR/issue/sprint):
- improve widget: add single/multiple mode button which will change number of rows in textarea

**Comment by damian1976** [comment]
IMHO: when validating multiline SNs/barcodes please remove leading/trailing newline(s) (if any) using lstrip()/rstrip(). Currently in 2.x the case when message saying "New line exists. Please remove it" appears is unnecessary

**Comment by ghost** [comment]
@damian1976 I don't see such text in ralph_assets sources. Are you sure it's still present?

**Comment by damian1976** [comment]
@xliiv if possible, please try do add an asset with SN and/or Barcode ending with newline character
