### ISSUE TITLE
Edit on accessory remarks on visualisation

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1614]
After click on accessory edit link on visualisation, rack edit page is opened - should be accessory edit page.

**Comment by damian1976** [comment]
Just to comment: 
1/ In **DCView** / **Edit** mode two "icons": pencil and rotate are invisible. In this way adding Description or name change is impossible. 
2/ In old ralph 2.x when changing the name the message used to appear "The rack was successfully added". But the only thing I made was the **name change**. The rack already existed. It would be great to change the message to sth like "Rack name has been successfully updated" in case of name change or "Rack description has been updated" in case of desc change OR in case anything has been change (name or description) set just one meesage "Rack details have been successfully updated" (simpler to implement)
3/ Please change **Rack accessorys** to **Rack accessories**. The plural form for accessory is acessories (http://dictionary.reference.com/browse/accessory)

**Comment by mkurek** [comment]
1) it's connected with font awesome icons
