### ISSUE TITLE
Data Center > Virtual servers: Parent objects list is "empty"

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1620]
When trying to add new Virtual server  and "unroll" the **Parent** list I get an empty list (objects list instead of list of parents' names to be precise) 

![111](https://cloud.githubusercontent.com/assets/9283029/8703032/78027f74-2b1b-11e5-9747-25a42f9ce198.png)

**Comment by mkurek** [comment]
This would be solved as a part of #1691
