### ISSUE TITLE
Scan: ssh_linux multiple account and private key management

### ISSUE THREAD

**Issue by aveseb** [allegro/ralph#1624]
Hello,

This is a proposal for the ssh linux scan. 
It would be great if we could manage several login and password in a list in order to try access to different linux severs. It seems that it can be bypassed by using XEN ssh in config file. 
But if think it should be much easy to manage it by using web UI. 
As we are speaking of SSH, by now many of us don't allow direct ssh login/password but use private/public keys. Would be possible to integrate management of login/privatekey too ?

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
