### ISSUE TITLE
Octodocker utilization

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1642]
We should start using octo docker right now :)

Please update the status of the project in this issue.

**Comment by szok** [comment]
Status: in progress
Works:
- Build images based on docker-compose.yml
- Divided into projects
- Docker in 

To do:
- Launch of images (there is an error Docker)
- Downgrade python Python 3 is 2.7 (docker-compose does not work properly with PY3)
- Deleting images
- Disable images
