### ISSUE TITLE
Export/Import from/to 2.x/3.x

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1665]
All assets models are imported as **back office** type.

**Comment by mkurek** [comment]
Also BO hostname is not exported/imported

**Comment by mkurek** [comment]
- not all bo assets, supports and licences are exported because of regions (admin_objects should be used)

**Comment by mkurek** [comment]
Thanks @szok - i almost have ready fix for it, but I didn't work out it finally before my leave. I'll tweak it and push in on monday.
