### ISSUE TITLE
Core > DCView > ... > 'Remarks' field (next to rack view) always empty (affects only 2.x)

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1677]
Most probably the idea was to display Remarks from Asset not from Device. However, it works the other way around. If possible, please enable displaying Remarks from Asset.
OR
When adding asset the Remarks field is not copied from Asset to Device

**Comment by vi4m** [comment]
Ralph 2 is not supported anymore, please migrate to the Ralph 3 which fixes many bugs and shortcomings of the previous version.
