### ISSUE TITLE
Beautiful charts on home page

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1682]
We should present some sort of dashboard for:

Assets models count
Assets statuses count
Easy access to newly craeated / last edited 10 assets
Other - tbd

(Previous issue: #1604)

**Comment by mkurek** [comment]
https://github.com/keen/dashboards

**Comment by vi4m** [comment]
:-1: `graphos` too 'fat' wrapper around existing libraries - we want to focus on one integrated library. And preferable - don't depend on django (upgrade problems and so on) 

https://github.com/agiliq/django-graphos - http://agiliq.com/demo/graphos/

**Comment by vi4m** [comment]
:-1: `jqplot` - old project pure javascript based. Renders on canvas. We used it, and it works fine  but is 'black box'-y, customization is really hard without patching the library. Overall - might be enough, but hey, let's try another librariers this time :)

**Comment by vi4m** [comment]
:-1: `d3.js` - beautifull charts, beautiful technology(d3 language, svg) but lacks 'boring business' charts.

http://d3js.org

**Comment by ar4s** [comment]
http://www.chartjs.org/ - Simple, clean and engaging charts for designers and developers

**Comment by vi4m** [comment]
:+1: http://nvd3.org - reusable business charst componentes for d3.js - definietelly worth trying

http://nvd3.org/examples/index.html
- pure svg
- easy to customize (dom + css)
- Live http://nvd3.org/livecode/index.html
