### ISSUE TITLE
Thousands separator missing

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1685]
To better read numbers separate them with spaces

<img width="730" alt="zrzut ekranu 2015-08-10 o 12 50 34" src="https://cloud.githubusercontent.com/assets/552398/9169948/e283b1e0-3f5e-11e5-8286-5eb9d852c870.png">

**Comment by ar4s** [comment]
Propably https://docs.djangoproject.com/en/1.8/topics/i18n/formatting/#template-filters solved the problem
