### ISSUE TITLE
BaseObject reference in autocomplete widget

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1691]
When there is reference to BaseObject in autocomplete widget, all values are now displayed as `BaseObject` (each `DataCenterAsset`, `BackOfficeAsset`, `VirtualServer` etc). We should display proper name of object here and allow to search by fields that are enabled to search for given object type (ex. name, barcode, sn, ... for DC Asset; hostname, barcode, sn, imei, ... for BO Asset; name, hypervisor, ... for Virtual etc)

Maybe we should se how it's done in django polymorphic: https://github.com/chrisglass/django_polymorphic

**Comment by ar4s** [comment]
TIP: ``[rel.related_model for rel BaseObject._meta.get_all_related_objects()]``

``https://github.com/hersonls/django-queryset-join/blob/master/src/querysetjoin/__init__.py``
