### ISSUE TITLE
Permissions by field for many-to-many relations

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1728]
When there is many-to-many relation between models, only one of them is keeping explicit information about this relation (it's model, where m2m field is defined). When we check permissions for such field, is permission if not found for user, we should try to get appropriate permission from the other site of this m2m relation.

https://github.com/allegro/ralph/blob/1b3f6262fa624f3e98daf31933d74640d9628fda/src/ralph/lib/permissions/models.py#L209

**Comment by romcheg** [comment]
Closing a stale issue. Please re-open, if needed.
