### ISSUE TITLE
Implement javascript error handler

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1744]
Our users are affected by javascript errors as well, but can't report it because we don't have error handler. 

Therefore, i propose to create own.
1. Handler: probably window.onerror will be sufficient
2. Action: show hand-crafted(not browser) window with error description, allowing to report it to us.
3. Nice to have: link to create an issue with the handled contents, including sentry or newrelic reporting

For now, let's begin with catching errors to notify the user, that it's an issue to fix.

**Comment by mkurek** [comment]
Done in https://github.com/allegro/ralph/pull/2091
