### ISSUE TITLE
Tabs & header

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1753]
Tabs doesn't align properly on macbook's resolutions. We have 2 rows there instead of one.

Two changes:
1. We should autoscale tabs list to keep them in 1 row
2. Replace label "Edit datacenter asset" with ""s10335.dc2" (object name without action name).

Screenshot of misaligned view below:

<img width="855" alt="zrzut ekranu 2015-09-02 o 15 14 23" src="https://cloud.githubusercontent.com/assets/552398/9632096/544ca25e-5185-11e5-8a37-96801117ca2d.png">

**Comment by mkurek** [comment]
Fixed in #1754
