### ISSUE TITLE
DC View doesn't respect permissions

### ISSUE THREAD

**Issue by msuszko** [allegro/ralph#1776]
DC View can be used to view assets, data centers and racks by users without sufficient permissions.

**Comment by msuszko** [comment]
This is related to #1735

**Comment by mkurek** [comment]
It's rather related to #1693

**Comment by msuszko** [comment]
DC View uses /api/data_center and /api/rack to fetch data it displays

**Comment by mkurek** [comment]
yes - permissions wasn't already applied to data center API part. It'll be done as a part of #1515

**Comment by romcheg** [comment]
Closing a stale issue.
