### ISSUE TITLE
CMDB implementation

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1779]
# Background

Ralph 2.0 introduced CMDB module which allows extending Ralph with the new objects, layers, and connections between them(relations). Two design decisions created cmdb the module it was
- CI database should be extended with the new objects such as Services, Business Lines, which are not related to the hardware
- CMDB should contains object which are not accessible through the Ralph interface
# New CMDB

**Comment by mkurek** [comment]
The equivalent of CI in Ralph NG is BaseObject. The equivalent of Change/Failure/etc in Ralph NG is Operation ( #1840 ). Closing this issue right now.
