### ISSUE TITLE
notifications based on low stock threshold (parts/items/assets)

### ISSUE THREAD

**Issue by ivan-sv** [allegro/ralph#1781]
Have a system implemented to keep track of spare assets/parts and be able to set threshold and get notifications if a certain item falls below the stock number (eg. amount of available spare 500gb drives is below 2, send notification to admin to order more or to just notify of capacity)

**Comment by romcheg** [comment]
It would be great to have a generic notification subsystem in Ralph. If this is still relevant, you're welcome to make a suggestion on Ralph's forum: https://ralph.discourse.group.
