### ISSUE TITLE
manually edit input/output ports hardware is plugged into

### ISSUE THREAD

**Issue by ivan-sv** [allegro/ralph#1782]
Ability to create networking devices/assets and be able to add ports to the equipment. (eg. Network switch - 24 ports or 48 ports). 

Be able to quickly connect devices to networking equipment and manually update description and ports if not using autodiscovery (eg. server A is connected to switch B on port 12) 

same concept can be applied to other equipment in general. Connection between devices and what interfaces/ports they are connected on to each other.

**Comment by mkurek** [comment]
I'll probably be managed by DC Asset connections field.

**Comment by ju5t** [comment]
Is this implemented already? If so, how would I test this?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
