### ISSUE TITLE
DC Visualization 2.x & 3.x: Wrong message after rack edit

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1790]
When rack is edited the following message appears: "The rack has been successfully added to data center". The message should be similar to "The rack has been successfully updated".

**Comment by vi4m** [comment]
Pull request ? :)

**Comment by damian1976** [comment]
https://github.com/allegro/ralph/pull/1795 :) Hope it's sufficient code change

**Comment by mkurek** [comment]
PR merged. Closing.
