### ISSUE TITLE
REP 1: Ralph Extensions Proposals

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1792]
# What is REP ?

REP stands for Ralph Extension Proposal.  A REP is a design document providing information to the Ralph community or describing a new feature for Ralph or its processes or environment. The REP should provide a concise technical specification of the feature and a rationale for the feature.

We intend REPs to be the primary mechanisms for proposing major new features, for collecting community input on an issue, and for documenting the design decisions that have gone into Ralph. The REP author is responsible for building consensus within the community and documenting dissenting opinions.

Because the REPs are maintained as text files in a versioned repository, their revision history is the historical record of the feature proposal.

Yes, we love [Python PEP's](https://www.python.org/dev/peps/pep-0001/#what-is-a-pep) and that's the main reason we adopt the same technique for Ralph development.
# REP Workflow
## Ralph BDFL

There are several reference in this REP to the "BDFL". This acronym stands for "Benevolent Dictator for Life" and refers to @vi4m Marcin Kliks, the project leader of, and the final design authority for, the Ralph DCIM System.
## REP Editors

The REP editors are individuals responsible for managing the administrative and editorial aspects of the REP workflow (e.g. assigning REP numbers and changing their status). The current editors are:

@ar4s Arkadiusz Adamski
@mkurek Mateusz Kurek
@andrzej-jankowski Andrzej Jankowski
@quamilek Kamil Warguła
@xliiv Tymoteusz Jankowski
@szok Piotr Jarolewski
## Github flow

Every REP is a github issue with the 'REP' label set. 
Statuses: 
- Open - await discussion.
- Closed - accepted or rejected, no further work is being done.

Labels: 
- REP/Accepted - feature accepted
- REP/Rejected - feature not accepted

**Comment by vi4m** [comment]
Please comment/accept this REP, @mkurek @xliiv @ar4s

**Comment by ghost** [comment]
:ok:

**Comment by ar4s** [comment]
where is @szok ?

**Comment by mkurek** [comment]
at home :) 
:ok:

**Comment by ar4s** [comment]
I mean I dont't see he in `REP Editiors`

**Comment by vi4m** [comment]
@szok is on the REP Editors Waiting List :-) I hope, he will join RE soon, after at least  100 successful pull requests. Currently 76 pull requests + 1 opened .

**Comment by RichiH** [comment]
Could you sync accepted and finished REPs into the source tree? Yes, it's double data retention and runs the risk of diverging, but GitHub does not offer anything better.

**Comment by vi4m** [comment]
@szok Congratulations, you've been added to the list, since you've successfully finished more than 100 PR's(123).

**Comment by vi4m** [comment]
@RichiH sounds like a good idea, we will do it after first Ralph 3.x release.

**Comment by romcheg** [comment]
Not relevant anymore.
