### ISSUE TITLE
Visualization grid should be property of ServerRoom, not DataCenter

### ISSUE THREAD

**Issue by msuszko** [allegro/ralph#1796]
At the moment visualization grid is an attribute of ServerRoom.
When DataCenter has more than one ServerRoom it is not always easy or even possible to draw all of then one one grid. One example would be ServerRooms stacked on different floors of one DataCenter.

**Comment by ar4s** [comment]
- [ ] move property from `DataCenter` model to `ServerRoom`
- [ ] create migration
- [ ] adapt DC visualization to new structure
  - [ ] add new view (Server room)
  - [ ] change url's router (new state)
  - [ ] add new service (`ServerRoomModel`)

**Comment by mkurek** [comment]
Implemented in #2433
