### ISSUE TITLE
REP3: Ralph CMDB interface

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1803]
# Introduction

Ralph 2.0 introduced CMDB module, which stands for "Configuration Management Database". It can be used for change management purpose, but it's not the main purpose. The main purpose it so securely store infrastructure components and relations between them.

Following Ralph 3.0 release, we want to merge CMDB into the ralph main interfae.
# Concept
1. Introduce or reuse baseobject with the CI concept in mind
2. Avoid generic relations, instead use concrete ForeignKeys as a relations
3. Remove CI types
4. Remove CI layers
5. Explicit is better than implicit
6. Think about removing uid, instead using baseobject id
# GUI Changes
1. Introduce cards: "Incidents", "Problems", "Changes", "Relations/Impact"
2. Move to main basic info new fields: CI uid
3. Every baseobject is called CI
# Concepts

Relations/Impacts uses just orm foreign keys instead of generic relations.

**Comment by mkurek** [comment]
`Move to main basic info new fields: CI uid` - what do you mean?

I'd remove points 3 and 4 in concept part - don't reference old CMDB (especially what to remove from it in context of new Ralph) - just write down what should be included in new Ralph (or optionally what to move from old CMDB).

About GUI changes - IMO there will be plenty of additional tabs, so we could wrap it in single meta-tab, which will be expanded into mutliple sub-tabs (dropdown).

To think about: do we really need single table just to have one ids space (and have to make additional join every time) - maybe content types could solve our problem?

**Comment by vi4m** [comment]
No, we should _definitelly_ avoid content types and loossly coupled data. You loose benefits of transactions and reliablity. I think we should just use baseobject id as a ci reference point without introducing uid-s. 

Migration of old data is another issue. I think we can deal with it.

**Comment by vi4m** [comment]
Implemented completely in Ralph 3.0
