### ISSUE TITLE
Autocomplete widget improvements

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1806]
- hide add button; add button should be displayed only when entered some text and there is no results
- when server returns error, widget should be highlighted (like in validation error)

See #1787 for details

**Comment by ar4s** [comment]
1. delete https://github.com/allegro/ralph/blob/ng/src/ralph/admin/static/elements/badge-input.html#L74-L82
2. (optional) replace edit with preview in a modal
3. add some information about server error (50x, 40x)

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
