### ISSUE TITLE
Bulk add/edit

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1809]
1/ BULK ADD
To definetely close the issue of bulk add it would great to add also Inventory number textarea next to SN, barcode and Position ones. In this way we will be able (without multiple asset edit process) to add multiple assets in a single step. BUT I'd like the Inventory number to be optional. 
Example.
4 assets. All fo them have SN, barcodes and positions. But only 1st and 4th asset has Inventory number (second and third line in the Inventory Number textarea is empty). Validation should let the things go with these lines to be empty.

2/ BULK EDIT

Like in 2.x, my proposition is to add another option like Bulk location edit  in /data_center/datacenterasset/ in Actions form OR in existing Bulk edit option, when clicked, TWO additional columns should be added: Rack  and Position (probably also Slot is to be considered ?)

What do you think about it? In my opinion this funcionality will be very helpful and intuitive.

**Comment by mkurek** [comment]
@szok would you like to take care of this? As far as i remember second issue has been already resolved.

**Comment by damian1976** [comment]
Yes, 2nd issue is resolved. We may think of adding just one more column: 'Slot'. Just in case of e.g. blade assets. Them it will work for all cases. Can we add this column, please?

**Comment by mkurek** [comment]
1 is resolved too (you could select bulk add fields using MULTIADD_DATA_CENTER_ASSET_FIELDS settings.
