### ISSUE TITLE
Quick installation not suitable for beginners

### ISSUE THREAD

**Issue by danielniccoli** [allegro/ralph#1811]
I have never worked with docker. But I decided to use the recommended option from the manuals to get _Ralph_ running. I installed docker and already the first command gives me a headache.

`docker run -i -t --name mysql_data -v /var/lib/mysql -v /home/ralph/.ralph busybox /bin/sh -c "chown default /home/ralph; chown default /home/ralph/.ralph"`

The error message is

```
chown: unknown user default
chown: unknown user default
```

Is there something in that line that needs to be changed according to my environment? If so, what has to be changed? In my opinion, the guide should cover those points.

**Comment by vi4m** [comment]
Ralph 3(beta version of new, much simpler Ralph)  has ready to use deb packages available. 

http://ralph-ng.readthedocs.org

**Comment by vi4m** [comment]
http://ralph-ng.readthedocs.org/installation/

**Comment by danielniccoli** [comment]
Much easier! :+1:  And the app looks good!

To get an idea of whether it is prudent to use Ralph v3 in our small environment, I have another question: How is the progress of the beta? Is it close to be released, or do we have to expect major changes?

**Comment by vi4m** [comment]
https://github.com/allegro/ralph/wiki/Ralph-3.x-roadmap

**Comment by vi4m** [comment]
It depends on what you need. If you need dc visualization and hardware tracking it should be enough today to start with it. More advanced things like costs reporting and scanning functionality will be ported over in next weeks as independent ralph-\* packages([to keep things simple](https://github.com/allegro/ralph/wiki/The-Zen-of-Ralph))

I would say database model should be stable enough to use today, most work will be on the interface level (virtual servers, components editing) which is easy to upgrade (apt-get upgrade)

**Comment by stokkie90** [comment]
@mkurek  Could you update the Roadmap with the right dates. Really looking forward on the first release.

**Comment by vi4m** [comment]
We've finished Ralph 3 :)
