### ISSUE TITLE
Replace "Components" scaffold with the real form

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1812]
Currently "Components" tab shows just Example data. 
The task is to replace it with manual components edit form similar to ralph 2.x admin panel.

**Comment by pydubreucq** [comment]
Hi,
Another cool feature could be to get facter by puppet automatically like:
processors
disks
...
Maybe It could be after the scan addon ;)
Best Regards,
Pierre-Yves

**Comment by mkurek** [comment]
@pydubreucq It will be part of the scan addon .

**Comment by mkurek** [comment]
Done in #2182
