### ISSUE TITLE
Licence - Can't add Type or Category

### ISSUE THREAD

**Issue by pydubreucq** [allegro/ralph#1818]
Hi,
I can't add Licence Type or Category
I have this error :

```
TypeError at /licences/softwarecategory/add/

'NoneType' object is not iterable

Request Method:     GET
Request URL:    http://ralph.odiso.net:8000/licences/softwarecategory/add/?_popup=1
Django Version:     1.8.4
Exception Type:     TypeError
Exception Value:    

'NoneType' object is not iterable

Exception Location:     /opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/lib/permissions/admin.py in get_form, line 49
Python Executable:  /opt/ralph/ralph-core/bin/python
Python Version:     3.4.2
Python Path:    

['/opt/ralph/ralph-core/bin',
 '/opt/ralph/ralph-core/lib/python3.4',
 '/opt/ralph/ralph-core/lib/python3.4/plat-x86_64-linux-gnu',
 '/opt/ralph/ralph-core/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/opt/ralph/ralph-core/lib/python3.4/site-packages']

Server time:    Mon, 5 Oct 2015 13:46:33 +0200
```

Thanks by advance

**Comment by mkurek** [comment]
This was fixed as a part of https://github.com/allegro/ralph/pull/1807 (https://github.com/allegro/ralph/pull/1807/files#diff-4443e2f0e817788ae977e150d5c92242R49)

Fetch latest version and close this issue if problem does not occur anymore.

**Comment by pydubreucq** [comment]
Hi,
I've ever the lastest version (deb package) 

```
dpkg -l | grep ralph
ii  ralph-core                      3.0.0-28                           amd64        Ralph is an DCIM/CMDB - asset management for Data Centers/ Back Office.
```

**Comment by mkurek** [comment]
@vi4m could you setup releasing latests version of deb package after every new commit (in ng brancj) for example in travis?

**Comment by vi4m** [comment]
I can issue new build right now. 

Automation of deb packaging depends on #1734 it requires docker. 
More info here: https://github.com/allegro/ralph/issues/1519

**Comment by vi4m** [comment]
Building new release...

**Comment by vi4m** [comment]
I issued new release 29 with 2 known bugs:
- tooltips don't render correctly (https://github.com/allegro/ralph/pull/1821)
- in some cases switching between view tabs doesn't work as expected (https://github.com/allegro/ralph/pull/1822)
