### ISSUE TITLE
CMDB - Clean up links returns Not Found 

### ISSUE THREAD

**Issue by Eagllus** [allegro/ralph#1825]
In `CMDB -> Configuration items -> Clean up` there are links to `Edit | View`
![screen shot 2015-10-07 at 11 10 03](https://cloud.githubusercontent.com/assets/411073/10333414/012cafd6-6ce4-11e5-8972-3ce90ca3c164.png)

When clicking on any link I get
![screen shot 2015-10-07 at 11 12 09](https://cloud.githubusercontent.com/assets/411073/10333442/48a53d60-6ce4-11e5-8c9f-eceb033ba432.png)

I used the docker installation (installed it about 10 minutes ago) and havent changed or done anything.

**Comment by vi4m** [comment]
Thanks for reporting. @xliiv will take care of it in meantime.

**Comment by vi4m** [comment]
We support now only the 3.x version. Please upgrade. Closing.
