### ISSUE TITLE
Export/Import 2.x/3.x: Assets with position 0 and orientation left/right incorrectly imported

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#1834]
After import to 3.x all PDUs having originally orientation left/right and position 0 have been imported with invalid (empty) position field. Thus, they are not displayed in DC visualization.

**Comment by mkurek** [comment]
Could you please check what values are exported to csv? Is this exporter issue or importer issue. We're interested in orientation column (should be 101 for left and 102 for right) and position column.

**Comment by mkurek** [comment]
Resolved in #1871
