### ISSUE TITLE
REP5: Operations

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#1840]
## Introduction

This is continuation of #1803 (CMDB Interface)

In Ralph 2.0 each CI could have attached incidents, problems and changed (from Jira). According to #1803 we want to move this functionality to Ralph NG. This REP will describe technical details of this feature.
## CMDB 2.0

In current CMDB version (Ralph 2.0) there are incidents, problems and changes, which use the same base class (but are stored in different database tables). Each of this models has exactly the same fields:
- cis (many to many for CI)
- summary
- description (don't know what's the difference between summary and description)
- jira_id 
- status
- assignee
- analysis (don't know what's the purpose of this field - IMO it's rather impact than analysis)
- problems (ditto)
- priority
- issue_type
- created / updated / resolved / planned_start / planned_end date
## Hardware failures

There is new feature request, to store (assets) hardware failures in Ralph NG (both for DC and BO assets). Each failure should have the following fields:
- failure type (for example hard drive, RAM, power supply etc)
- description
- jira (or probably general purpose) ticket id
- status 
## Proposed architecture

![img_20151022_143014](https://cloud.githubusercontent.com/assets/107437/10665179/91e8bd26-78c9-11e5-86ca-f4305f3cfb66.jpg)

Notes:
- `Issue` is generic type for problems, incidents, changes and failures.
- `Failure` is inheriting from `Issue`, adding one additional field: `failure_type`, which is foreign key to additional table `FailureType`
- `FailureType` contains name and `ContentType` - particular failure type could be assigned only to failure for one base object type, for example controller crash could be reported only for data center asset
- `Issue` could be attached to multiple `BaseObject`s (probably all with the same type)
- status has only few valid choices (use `dj.choices`), for example open, closed, resolved etc.
- choosing 'failure' issue type forces to use `Failure` type; using `Failure` class forcing to use `failure` type;
## Discussion
- is failure proper name for it?
- should failure inherit from issue?
- dependency and conditions between issue type and inheriting is a little bit complicated

**Comment by vi4m** [comment]
Well I really like this approach in general.
I'm wondering if we really need separate Failure object.

What if we simplify that a little bi,  to just say that Failure = Incident, type=hardware incident, details=disk broken. You can than relate incidents together, for example nic card incident -> service not responding incident in the same place. I'm not sure how specific is Failure in comparision with Incident.

**Comment by vi4m** [comment]
summary vs description -> summary - one line summary(disk failure), description -> complete contents about all work being done for that incident(replacing disks, checking if ok, restarting)

**Comment by vi4m** [comment]
I suggest to change Issues -> Operations, or 'Service Operations'.

**Comment by vi4m** [comment]
![operation](https://cloud.githubusercontent.com/assets/552398/10817847/0de258e2-7e3d-11e5-955f-d2d8bb6ad921.png)

**Comment by mkurek** [comment]
Merged in #1856
