### ISSUE TITLE
REP7: Zen of Ralph

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1849]
### Focused scope

Ralph is a Single Point of Truth for your Infrastructure.

The scope of Ralph should be to securely store, and share all of inventory information, no matter what type of hardware and software it contains.

Ralph package doesn't:
- orchestrate the infrastructure
- modify its state
- depend on its type and flavor (Back Office, DC)

Every mutating action should be delegated to the separate applications.
### Self descriptive

Ralph should be easy to understand without excessive manual reading. User interface describes itself, providing descriptions of fields, reports, actions, forms, reducing the need to read manual.
### Easy to develop

Ralph should be also easy to extend. Developer has all the resources to integrate separate applications integrated with Ralph, such as Scan,  DNS orchestration, deployment and other, without modifying single line of Ralph package.
### Easy to install

Ralph should be easy to install, not requiring installation of other software apart from chosen distribution we support. That's why we always focus on native system package managers support, because Ralph is a tool for administrators who want this. 

We provide other methods of installations such as Docker, but native packages support will be always provided.
### Simple

We will try to limit total LOC of project, focusing on security. The less LOC, the higher quality of code. 
Introducing new dependency into the setup.py needs BDFL acceptance in every case.
### Preconfigured

Ralph should have sane defaults reducing the need to configure it after installation. Install it and use OOTB.
### Open Source

Ralph will be always Open Source, without handcrafting free and non-free version. Basically, the source you see, is the version we use at Allegro Group. Development will be always done in public, with the listening of the community.

**Comment by fossilet** [comment]
Bravo!

**Comment by romcheg** [comment]
Not relevant anymore.
