### ISSUE TITLE
Some Admin Views are inaccessible in spite of granted permission

### ISSUE THREAD

**Issue by msuszko** [allegro/ralph#1882]
For example user without admin status gets HTTP 403 trying to access Component tab on DataCenterAsset (/data_center/datacenterasset/1/datacenter_asset_components/) despite having "Can view DataCenterAssetComponents" granted.

`ralph.lib.permissions.views.PermissionViewMetaClass` wraps `.dispatch` method of View classes to check is user rights to get a View. Permission name consists of  Django application name and "can_view_extra_" + view name.
`.dispatch` wrapper tries to get application name from its keyword arguments, when there is no name it uses _accounts_

Below is inheritance tree of `DataCenterAssetComponents` with users of `PermissionViewMetaClass` in bold:
- **ralph.admin.mixins.RalphTemplateView**, ralph.admin.views.extra.RalphExtraViewMixin
  - **ralph.admin.views.extra.RalphDetailView**
    - ralph.admin.views.extra.RalphDetailViewAdmin
      - ralph.data_center.views.ui.DataCenterAssetComponents

every descendant of `PermissionViewMetaClass` has wrapped or added `.dispatch` method.
This causes permission check to execute four times. Three times it passes, because all subclasses of `RalphExtraViewMixin` get application name corretly, but `RalphTemplateView.dispatch` checks for _accounts.can_view_extra_backofficeassetcomponents_, and doesn't find it.

**Comment by mkurek** [comment]
@msuszko could you confirm that the error still occurs? I definitely can reproduce multiple-permission-checking (in every dispatch), but I cannot reproduce "forbidden" error even if user has permission to view - didn't [this](https://github.com/allegro/ralph/commit/7956d3a48742684cebf3355c21b8c6b1915d2791) commit fix it?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
