### ISSUE TITLE
REP8: Unification of packaging

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#1913]
# Problems

Currently we use 2 separate mechanisms to package code (deb and docker). We don't want to favor one solution over another, because both of them have its strengths:
- docker is good for starters, and existing docker users who have docker installated and running
- deb is good for sysadmins who want control and integration with existing systems (i think it's most of our audience) and don't want to bother with patching kernel, installation of docker, and docker-compose (and optional: swarm, machine)
# Solution

Using deb package as a packaging layer, and using it with the docker itself.
- always make deb package
- when making docker image - use this package
# Arguments over this approach
1. It's easy - packaging with dh_virtualenv is just a matter of writting one file https://github.com/allegro/ralph/blob/ng/debian/rules it doesn't do much overhead itself
2. Versioning did right - dpkg & apt releases history
3. Slimming docker image - first pass just create small (10 MB) ralph package, then docker image doesn't need build environment with autoconf, perl, automake, headers, dev packages, and other stuff (it slims a lot)
4. We want to be included as a "normal" ubuntu package into official repository. Starting with unmaintable and non-packagable crap/dependencies hell/ from the beginning could be a problem in the future.
5. Many(how much - todo) of docker packages are just a apt-get "fascades" with preconfigured environment variables and helpers (which is great imo)

**Comment by pierlon** [comment]
Is there any update on this? Would love to help out.

**Comment by vi4m** [comment]
I think it’s still in todo state - any help really appreciated!. @romcheg any news about it ?

**Comment by vi4m** [comment]
I think we need improvements in Ci/CD script which will build deb package on a separate OS such as Debian, Ubuntu etc. Then testing the  installation of package - maybe even inside the Docker. We can then reuse this Docket as a official and fully supported way of installation integrated with CI

**Comment by romcheg** [comment]
Not relevant anymore.
