### ISSUE TITLE
Ralph 3 : Sort Content Type select box and another question

### ISSUE THREAD

**Issue by pydubreucq** [allegro/ralph#1927]
Hi,
It could be usefull to sort the content type select box in 

```
Data Center > Cloud projects > Add
Data Center > Virtual Servers > Add
```

Another question, what do you mean by content type ?
Is this form is terminated ? Because if I would like to add a Virtual Server I can't give an hostname

Best Regards,
Pierre-Yves

**Comment by mkurek** [comment]
Cloud & Virtual hosts are not finished yet - there is REP for it: https://github.com/allegro/ralph/issues/1914

This field will be hidden in final version (as well as hostname and other fields will be added). Stay tuned for updates in this REP!

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
