### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by mkurek** [allegro/ralph#2172]
First of all docs automatically build should be fixed: https://readthedocs.org/projects/ralph-ng/builds/3660852/ (it's probably related to https://github.com/mitsuhiko/click/issues/494 - if yes don't know if we can change it ourself).

(sub)sections that need update:
- [ ] configuration - list all available (Ralph) config options. Move here `LDAP Authentication` from `Installation` as well.
- [x] move current `Transitions` content to `Developer guide` - Transitions for `User guide` should describe transitions from user point of view (how to configure transition, select actions, actions could have some fields required, transition history etc)
- [ ] API - list all available resources. consider apiary / swagger (http://blog.apiary.io/2016/01/18/We-ve-got-Swagger/)
- [x] describe main modules (BO, DC, Licences, Supports). 
- [x] describe DC View
- [x] describe asset lifecycle
- [x] describe reports
- [ ] describe some major functions as bulk add, bulk edit, import/export
- [ ] describe inkpy (how to configure it with RQ)
- [ ] describe permissions mechanism (per object, per field etc)

**Comment by vi4m** [comment]
I think we should close this issue, and follow missing documentation pages already marked in docs

**Comment by mkurek** [comment]
Ok. closing.
