### ISSUE TITLE
missing docker-compose.yml.tmpl

### ISSUE THREAD

**Issue by javexed** [allegro/ralph#2174]
According to here: http://ralph-ng.readthedocs.org/installation/#docker-installation-experimental there should be a docker-compose.yml.tmpl file to copy to docker-compose.yml.

I also do see in the .dockerignore file a reference to ignoring the docker-compose.yml file (which makes sense), but can't find the template anywhere.

Am I missing something?

**Comment by ar4s** [comment]
`docker-compose.yml.tmpl` is located in `contrib` directory (https://github.com/allegro/ralph/blob/ng/contrib/docker-compose.yml.tmpl)

**Comment by javexed** [comment]
Oh silly me. I guess that "outside sources" in the link above is equal to "contrib" (aka contributions.)

Thanks.
