### ISSUE TITLE
Save button wrong color when bulk editing in Safari

### ISSUE THREAD

**Issue by fossilet** [allegro/ralph#2176]
When bulk editing assets, the color of the Save button at the bottom right corner is the same with its background color in Safari. I find the button has a class `default`. If I remove the `default` class, the color will become right. But I have not found how to fix this in the code.

**Comment by mkurek** [comment]
We cannot repeat it in Safari. Could you post a print-screen of it? What version of Ralph are you using? Btw, default class has no meaning at all in our css files :)

**Comment by fossilet** [comment]
@mkurek It was caused by some Safari extension. Thank you for the clue.
