### ISSUE TITLE
Trying to follow install guide failed

### ISSUE THREAD

**Issue by cdb-fr** [allegro/ralph#2179]
Sorry for the newbie question, but the initial setup failed on my Debian Jessie box.
$ sudo apt-get install ralph-core
E: Unable to locate package ralph-core.

Thanks for any tips to help

**Comment by ar4s** [comment]
run following commands and try again:
`sudo apt-key adv --keyserver  hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61`
`sudo sh -c "echo 'deb https://dl.bintray.com/vi4m/ralph wheezy main' >  /etc/apt/sources.list.d/vi4m_ralph.list"`

**Comment by cdb-fr** [comment]
Thank you ar4s, but even when re-running the previous commands leads to the same result 

patrick@debian8:~$ sudo apt-get install ralph-core redis-server mysql-server
Reading package lists... Done
Building dependency tree  
Reading state information... Done
E: Unable to locate package ralph-core

**Comment by ar4s** [comment]
Did you run `sudo apt-get update` before install command?

**Comment by cdb-fr** [comment]
I did
I follow exactly the procedure that is indicated on the installation guide.
I had an issue when trying to get apt-transport-https, but finally installed it properly
ii apt-transport-htt 1.0.9.8.2     i386          https download transport for APT

After $ sudo apt-get update, I ran
$ sudo apt-get install mysql-server with no problem
$ sudo apt-get install redis-server with no problem
only issue with ralph-core

The repository configuration is correct
patrick@debian8:~$ ls /etc/apt/sources.list.d
vi4m_ralph.list

Don't have any other ideas.
Thanks

**Comment by cdb-fr** [comment]
Just one info, I'm running a i-386 version of Jessie and it seems that the softawre is not available in the repository for this arch ?
![ralph-repository_i-386](https://cloud.githubusercontent.com/assets/16917909/12617423/e7bffcf4-c50f-11e5-976c-8be8cba530a6.JPG)

Should I reinstall my box in 64 bits version ?

**Comment by vi4m** [comment]
Yes, only amd64 builds are available at the moment

**Comment by cdb-fr** [comment]
Thanks vi4m,
I've created a 64 bits box and launch installer successfully.
Maybe more comments on product usage to follow.
Thank you.

**Comment by vi4m** [comment]
If you are open to collaboration, you could make some correction to the documentation - to write something like 'only 64bit architecture is supported' :-)

**Comment by cdb-fr** [comment]
I'd be happy to help (even with my limited time and knowledge).
Let me know how to create input in the documentation and I'll write what I estimate to be pertinent.

**Comment by vi4m** [comment]
https://github.com/allegro/ralph/edit/ng/docs/installation.md

**Comment by bencheikh** [comment]
Hello everyone i read your comments , so Ralph it's not supported on Debian jessie ? i had the same probleme as cdb-fr but i have an x86_64 Debian.
I think it's not available for this distribution , it works only with wheezy or ubuntu.
May you confrm vi4m and tell me if there will be some new changes

**Comment by mkurek** [comment]
Hi @bencheikh . It should work fine on jessie - we probably didn't release deb for this version. I'll do this by the monday.

**Comment by mkurek** [comment]
@bencheikh it should work fine on jessie (even using wheezy repo). Anyway after merging https://github.com/allegro/ralph/pull/2953, there will be jessie repo for ralph on bintray.
