### ISSUE TITLE
Ralph NG vs Ralph 2.x

### ISSUE THREAD

**Issue by justinlakhani** [allegro/ralph#2188]
Is Ralph NG intended to be a streamlined version of Ralph 2.x indefinitely or are there intentions to merge at some point?

**Comment by vi4m** [comment]
We will port to the ralph 3.x following functionality:
- scanner/autodiscovery support
- costs calculation integration (Scrooge)

We will not support/merge:
- old cmdb interface with impact detection/relations
- built-in deployment system (will be replaced with external terraform, openstack ironic integration)

**Comment by vi4m** [comment]
Is there any particular functionality are you interested in?
