### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by axcelx** [allegro/ralph#2193]
http://IP-HERE:8000/login/?next=/

Weblogs show 

[01/Feb/2016 17:10:13] "GET / HTTP/1.1" 302 0
[01/Feb/2016 17:10:13] "GET /login/?next=/ HTTP/1.1" 500 27

This is a clean Ubuntu install, followed directions under ubuntu section

Getting Server Error (500) when visiting page

**Comment by mkurek** [comment]
@axcelx Did you install it from source code, deb or docker?

**Comment by axcelx** [comment]
deb

**Comment by vi4m** [comment]
did you run `ralph migrate` ?

**Comment by axcelx** [comment]
yes

James Thomas

On Feb 1, 2016, at 2:42 PM, ? vi4m <notifications@github.com<mailto:notifications@github.com>> wrote:

did you run ralph migrate ?

##

**Comment by vi4m** [comment]
trying to reproduce...

**Comment by vi4m** [comment]
Yeah, reproduced it on new builds...

ValueError: The file 'vendor/css/foundation-datepicker.css' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0x7f7546638668>.

**Comment by vi4m** [comment]
Try to edit file: 

`/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/settings/prod.py`

and change `DEBUG = False` to `DEBUG = True`

Does it fix the problem?

**Comment by axcelx** [comment]
Yes, what an easy fix ☺ I appreciate your help.

**Comment by vi4m** [comment]
@mkurek we should provide gunicorn+static files hosting without the DEBUG flag the same way as docker installation method, what do you think?

**Comment by mkurek** [comment]
@vi4m yes - i'll look more closely to deb install in this week. 

About gunicorn + static files - it'll need nginx or some other www server (http://gunicorn.org/index.html#deployment). 

In my opinion, for simple (not-production) installation, runserver (even with DEBUG=True) as a default option will be enough. Then, we should describe in docs how to configure (and run) this as a production server (turn off debug, use www server, store logs somewhere etc).

**Comment by vi4m** [comment]
That's what i meant. 3.0 release is near, so we want to provide 'production ready' settings as well.

**Comment by delize** [comment]
Just for reference, I have to make the same change with version (3.0.0-snapshot-20160512-5556) to be able to effectively run

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group

**Comment by oswinfox** [comment]
Hello, I am trying Ralph installed with docker and I have the same error... Anyone can help me?

**Comment by ChrisJMacdonald** [comment]
Same again, on docker

**Comment by klmyhd** [comment]
docker-compose run web init
docker-compose up -d


https://ralph.discourse.group/t/docker-installation-server-error-500/216
