### ISSUE TITLE
ralph command not found

### ISSUE THREAD

**Issue by kevinba** [allegro/ralph#2194]
Hello,

I'm stuck on the part about the initialization of ralph, the command to start the migration "ralph migrate " is not recognized.

Can you help me ?

**Comment by mkurek** [comment]
@kevinba how did you install Ralph? Deb, Docker or directly from source code? Do you use Ralph 2 or Ralph 3 (a.k.a NG)?

**Comment by vi4m** [comment]
@kevinba make sure you exported your environment variables corectly (`set`). 

You should have /opt/ralph-core/virt/bin(i don't remember the particular path, but something like that) in your $PATH

**Comment by kevinba** [comment]
Hello,

I try to install Ralph 3.
Here are the commands I used for installation :
sudo apt-key adv --keyserver  hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
sudo sh -c "echo 'deb https://dl.bintray.com/vi4m/ralph wheezy main' >  /etc/apt/sources.list.d/vi4m_ralph.list"
sudo apt-get update
sudo apt-get install ralph-core redis-server mysql-server

How can i check that my environment variables were corectly exported ?

**Comment by kevinba** [comment]
I have type the command echo $PATH and here are the result : /opt/ralph/ralph-core/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr:/games:/usr/local/games

**Comment by mkurek** [comment]
could you paste here your output of `ls -al /opt/ralph/ralph-core/bin/` ?

**Comment by kevinba** [comment]
Here is the result :
total 7684
drwxr-xr-x 3 root root    4096 févr.  3 21:30 .
drwxr-xr-x 5 root root    4096 févr.  3 21:28 ..
-rw-r--r-- 1 root root    2202 févr.  3 12:16 activate
-rw-r--r-- 1 root root    1258 févr.  3 12:16 activate.csh
-rw-r--r-- 1 root root    2471 févr.  3 12:16 activate.fish
-rw-r--r-- 1 root root    1137 févr.  3 12:15 activate_this.py
-rwxr-xr-x 1 root root     316 févr.  3 12:16 dev_ralph
-rwxr-xr-x 1 root root     282 févr.  3 12:16 django-admin
-rwxr-xr-x 1 root root     141 févr.  3 12:16 django-admin.py
-rwxr-xr-x 1 root root     252 févr.  3 12:16 easy_install
-rwxr-xr-x 1 root root     252 févr.  3 12:16 easy_install-3.4
-rwxr-xr-x 1 root root     224 févr.  3 12:16 pip
-rwxr-xr-x 1 root root     224 févr.  3 12:16 pip3
-rwxr-xr-x 1 root root     224 févr.  3 12:16 pip3.4
drwxr-xr-x 2 root root    4096 févr.  3 21:29 **pycache**
lrwxrwxrwx 1 root root       9 févr.  3 12:16 python -> python3.4
lrwxrwxrwx 1 root root       9 févr.  3 12:16 python3 -> python3.4
-rwxr-xr-x 3 root root 3709944 oct.  14 23:42 python3.4
-rwxr-xr-x 1 root root 4061272 févr.  3 12:16 python3.4,orig
-rwxr-xr-x 1 root root     308 févr.  3 12:16 ralph
-rwxr-xr-x 1 root root     224 févr.  3 12:16 rq
-rwxr-xr-x 1 root root     224 févr.  3 12:16 rqinfo
-rwxr-xr-x 1 root root     228 févr.  3 12:16 rqworker
-rwxr-xr-x 1 root root    3866 févr.  3 12:16 sqlformat
-rwxr-xr-x 1 root root     318 févr.  3 12:16 test_ralph
-rwxr-xr-x 1 root root     232 févr.  3 12:16 unidecode
-rwxr-xr-x 1 root root     231 févr.  3 12:16 wheel

**Comment by vi4m** [comment]
What does  `ralph` output ?

**Comment by kevinba** [comment]
Hello,

The problem comes of my environments variables.
I have corrected this problem and continued the installation with ralph commands but i can't connect to ralph server with : http://IP-ADRESS:8000

An idea ?

**Comment by mkurek** [comment]
@kevinba How do you start ralph? Are you running in locally or in some cloud provider (AWS etc)? Maybe port is blocked for external access?

**Comment by vi4m** [comment]
please edit this file: `/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/settings/prod.py`

and change DEBUG = False to DEBUG = True

**Comment by kevinba** [comment]
Ok The problem was that the server was not started ^^
I started and everything works correctly !!!
Thanks you very much for your help
