### ISSUE TITLE
Really miss management of network addresses and vlan.

### ISSUE THREAD

**Issue by DarkBeardRUS** [allegro/ralph#2224]
Hello, 
**You have a very good project.** 
To my great regret I am not a programmer myself and I can not write like that. 

But for the needs of the companies do not have enough good visual management of network addresses and vlan.

**Comment by vi4m** [comment]
Thank you for good words. Speaking about IPAM. It's on our roadmap, so yeah, it's comming after (or during) deployment/scan implementation.

**Comment by serlaroc** [comment]
Hello vi4m...We have recently migrated into Ralph3 for DCIM solution and so far we think it's a great product. Do you have scheduled date for the IPAM solution update for Ralph3?

**Comment by mkurek** [comment]
@serlaroc check out the [feature/deployment](https://github.com/allegro/ralph/tree/feature/deployment) breanch with the newest updates for IPAM.

**Comment by serlaroc** [comment]
@vi4m ...Thanks for the link but I'm feeling a bit lost trying to find IPAM updates. Also I'm not a developer so I'm looking for some assistance to get the IPAM deployed onto Ralph3. Your help will greatly appreciated.

Thanks,
serlaroc

**Comment by mkurek** [comment]
@serlaroc how did you installed ralph? using deb, docker image, vagrant or directly from sources?

**Comment by ju5t** [comment]
This is definitely something I'd like to test. I've installed ralph from your packages. What would be the best way to do this?

**Comment by vi4m** [comment]
IPAM is now implemented. Just install the latest version. Closing this issue.
