### ISSUE TITLE
We would like to document HA IPs in Ralph NG too

### ISSUE THREAD

**Issue by renki81** [allegro/ralph#2226]
The Problem is, that HA IPs most propably cannot be inventurized automatically.
So we would need a possibility to mark an IP, and link it to another server that can get this IP in case of a failover.

**Comment by vi4m** [comment]
We have something like `load balancer pools` present in ralph 2 and we plan to port it over to the ralph 3. Does it solve your need?

**Comment by renki81** [comment]
Unlukily I dont know Ralph2 very well; we want to start documenting with Ralph3
How doest this work in Ralph2 exactly?

**Comment by vi4m** [comment]
It depends on what you mean. Do you mean load balancer - (haproxy, f5) vips ip's? Or dhcp pools? On which network layer?

**Comment by renki81** [comment]
We have configured lots of virtual IPs that can be used by different servers. (For high availibility purposes). -> An IP Adress can be set up on different servers, depending on where the service is started. But the IP Adress should still be documented (and be search-able) in Ralph to avoid IP conflicts when we need to find a free IP Adress.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
