### ISSUE TITLE
Cannot click on password change link

### ISSUE THREAD

**Issue by fossilet** [allegro/ralph#2237]
<img width="831" alt="screen shot 2016-02-23 at 18 06 41" src="https://cloud.githubusercontent.com/assets/948336/13248260/5009df16-da58-11e5-82af-02153d577118.png">
The link to the form for changing password cannot be clicked. One the mouse moves, the tip box disappears.

**Comment by ar4s** [comment]
1. add timeout

**Comment by Chewie9999** [comment]
Hi everyone, this is still a problem with the "jessie" version I have installed today

**Comment by vi4m** [comment]
@ar4s confirmed on master?

**Comment by nvdacsheets** [comment]
Appending `/password` to the user URL can serve as a workaround for this issue.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
