### ISSUE TITLE
Active Directory Authentication Failed

### ISSUE THREAD

**Issue by kevinba** [allegro/ralph#2240]
Hello,

I try to configure the LDAP Authentication of my Ralph server but I encounter some difficulties.
I managed to repatriate the users of my LDAP server but when I try to connect this is what I get :

"Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive. "

here are my configuration files :

```
- global_settings.py

AUTHENTICATION_BACKENDS = (
      'django_auth_ldap.backend.LDAPBackend',
      'django.contrib.auth.backends.ModelBackend',
  )

#LDAP CONFIG
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType
AUTH_LDAP_SERVER_URI = "ldap://XXXXXXXXXXX:389"
AUTH_LDAP_BIND_AS_AUTHENTICATING_USER = True
UTH_LDAP_USER_DN_TEMPLATE = "uid=%(user)s,ou=Utilisateurs,ou=XX,dc=YY,dc=ZZ"
AUTH_LDAP_BIND_DN = "cn=WW,ou=Utilisateurs,ou=XX,dc=YY,dc=ZZ"
AUTH_LDAP_BIND_PASSWORD = "secret"
AUTH_LDAP_PROTOCOL_VERSION = 3
AUTH_LDAP_START_TLS = True

# User and group search objects and types

AUTH_LDAP_USER_USERNAME_ATTR = "sAMAccountName"
AUTH_LDAP_USER_SEARCH_BASE = "ou=Utilisateurs,ou=XX,dc=YY,dc=ZZ"
AUTH_LDAP_USER_SEARCH_FILTER = '(&(objectclass=user)(objectcategory=person))'.format(
  AUTH_LDAP_USER_USERNAME_ATTR)
AUTH_LDAP_USER_SEARCH = LDAPSearch(AUTH_LDAP_USER_SEARCH_BASE,
  ldap.SCOPE_SUBTREE, AUTH_LDAP_USER_SEARCH_FILTER)
AUTH_LDAP_USER_FILTER = '(memberOf=CN=WW,OU=Groupes,OU=XX,DC=YY,DC=ZZ)'
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("ou=Groupes,ou=XX,dc=YY,dc=ZZ",
    ldap.SCOPE_SUBTREE, "(objectClass=groupOfNames)"
)
AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()
AUTH_LDAP_REQUIRE_GROUP = "cn=WW,ou=Groupes,ou=XX,dc=YY,dc=ZZ"
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "cn=WW,ou=Groupes,ou=XX,dc=YY,dc=ZZ",
    "is_staff": "cn=WW,ou=Groupes,ou=XX,dc=YY,dc=ZZ",
    "is_superuser": "cn=WW,ou=Groupes,ou=XX,dc=YY,dc=ZZ",
}
AUTH_LDAP_PROFILE_FLAGS_BY_GROUP = {
    "is_awesome": "cn=WW,ou=Groupes,ou=XX,dc=YY,dc=ZZ",
}

# What to do once the user is authenticated

AUTH_LDAP_USER_ATTR_MAP = {
  "first_name": "givenName",
  "last_name": "sn",
  "email": "userPrincipalName",

- base.py

LOGGING['loggers']['django_auth_ldap'] = {
      'handlers': ['file'],
      'propagate': True,
      'level': 'DEBUG',
  }
```

Can you help me ?

**Comment by mkurek** [comment]
Hi @kevinba . I assume, that you have local superuser account created, am i right? If yes, first try to run `ralph ldap_sync` to fetch all users and their permissions from ldap, then login into your local (non-ldap) superuser account and check if all users were fetched. Notice that each user that should be capable to login to ralph should be both active and staff (i assume that you're using Ralph NG).

**Comment by kevinba** [comment]
Hi mkurek,

Yes, I have a local superuser account and I have run `ralph ldap_sync`, all users from my ldap server have been fetched by my ralph server. However I can't connect with them.

![ralph](https://cloud.githubusercontent.com/assets/17054000/13315213/ba082678-dba9-11e5-9c78-eaaf24ad0f2b.png)

Thanks for your help

**Comment by ghost** [comment]
hey kevinba,

I have the exact same problem.
Did you get the ldap login with password working??

And if yes can you share your solution.

Kind regards,

Patrick
