### ISSUE TITLE
Adding pictures to devices

### ISSUE THREAD

**Issue by jhades60** [allegro/ralph#2264]
Hello,
Great work, asset management very useful and fresh GUI with great look !
a enhancement could be adding pictures to devices - to share access / send screenshot to local tech to be sure on where do the job.
like on openDCIM you can see it here https://youtu.be/fpMVRG9bPeA?t=322

Thanks

enhancement
ng
visualization

**Comment by vi4m** [comment]
Thanks for feedback! 

Please vote this issue if anybody else needs this.

**Comment by vi4m** [comment]
In March we will open source our mobile app, so it would be quite useful to add there the ability to capture camera shot, and attach to the given asset as attachments.

**Comment by odurgeau** [comment]
+1

**Comment by derbalazs** [comment]
+1

**Comment by angelionix99** [comment]
+1

**Comment by Vaygh** [comment]
+1

**Comment by Chewie9999** [comment]
+1. Also It would be nice to add photos to the "model" record, eg generic stock photos for things

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
