### ISSUE TITLE
make build-package error

### ISSUE THREAD

**Issue by fossilet** [allegro/ralph#2283]
I am trying to package deb's locally, but see the follow error in the final step:

```
dh_installdocs doc/_build/html
make[2]: Leaving directory `/home/vagrant/src/ralph/dh-virtualenv'
   dh_sphinxdoc
dh_sphinxdoc: ignoring unknown JavaScript code: debian/dh-virtualenv/usr/share/doc/dh-virtualenv/html/_static/underscore-1.3.1.js
dh_sphinxdoc: error: unknown JavaScript code: debian/dh-virtualenv/usr/share/doc/dh-virtualenv/html/_static/searchtools.js
make[1]: *** [binary] Error 255
make[1]: Leaving directory `/home/vagrant/src/ralph/dh-virtualenv'
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
make: *** [build-package] Error 2
```

Beside, the function [install_dh_virtualenv](https://github.com/allegro/ralph/blob/ng/packaging/build-package.sh#L9) seems not invoking. I added a line to run it in `build-package.sh`. Is this correct?

**Comment by vi4m** [comment]
Weird error. What operating system/environment do you use?

**Comment by fossilet** [comment]
I was using the Vagrant environment. The problem recurs today.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
