### ISSUE TITLE
Barcode Generation/Print Labels

### ISSUE THREAD

**Issue by delize** [allegro/ralph#2297]
Hey,

It would be wonderful if Ralph was able to do Barcode Generation and Label Printing for each unique asset.

Is this something that is planned in the future?

Thanks

**Comment by derbalazs** [comment]
+1 here :)

**Comment by Chefkeks** [comment]
Any news/updates/plans about this feature request?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
