### ISSUE TITLE
DonPedro Agent for Ralph 3

### ISSUE THREAD

**Issue by kevinba** [allegro/ralph#2318]
Hi,

I would like to advise the "Back Office" part of my Ralph server using the agent DonPedro but it does not work for this version.
Is there an equivalent ? Do you have a solution ?

Thank you in advance

**Comment by mkurek** [comment]
@kevinba not yet - we'll be working on scan feature in the next month.

**Comment by kevinba** [comment]
Ok thank you for your answer.
