### ISSUE TITLE
The display option of U availabilities is unavailable

### ISSUE THREAD

**Issue by kevinba** [allegro/ralph#2344]
Hi,

Since the last update, the display option of U availabilities (as you can see below) for data centers is unavailable.

Old Version

![good](https://cloud.githubusercontent.com/assets/17054000/14311081/c7c96a90-fbe5-11e5-99af-18c3f8f8c221.png)

New Version

![bad](https://cloud.githubusercontent.com/assets/17054000/14311131/1440bd2e-fbe6-11e5-8d5d-e50e01f2791e.png)

**Comment by mkurek** [comment]
@kevinba could you confirm that this bug still occurs in the newest version? i cannot reproduce it right now.

**Comment by kevinba** [comment]
Hi @mkurek,

I installed the latest version of Ralph but unfortunately the problem seems to persist.
However I note that the problem does not seem to occur when I use the Chrome browser, only when using IE and Mozilla.

**Comment by kevinba** [comment]
Hi,

I have installed the latest version of Ralph "releases 20160512.1" and I see that the problem appears to have been resolved.

Thank you very much
