### ISSUE TITLE
DC Visualization

### ISSUE THREAD

**Issue by MB0404** [allegro/ralph#2359]
As you see, the menu Layer is under the layer for the height-units and that grey bar for the back-side of a rack.
Tested in Chrome and ff. 

![ralph](https://cloud.githubusercontent.com/assets/8530436/14384843/9dbb0f10-fd9d-11e5-807a-49ea683a4082.JPG)

**Comment by vi4m** [comment]
Thank you for bug report. Confirmed locally - looks like z-order issue in css.
