### ISSUE TITLE
Identify the number of power supplies present on a machine

### ISSUE THREAD

**Issue by kevinba** [allegro/ralph#2371]
Hi everyone,

As a user I wish I could identify the number of power supplies present on a machine.

The goal is to be able to know if a machine has one or more power supplies.
I also like to be able to differentiate the power supplies connected to an corrugated tour and those that are not.

Do these changes are possible ?

Thank you in advance

**Comment by mkurek** [comment]
Hi @kevinba. What do you mean by "identify"? Do you want it do happen automatically (magically) or you just want a field where you'll enter the number of power supplies?

**Comment by kevinba** [comment]
Hi @mkurek. I do not know if it possible to automatically upload these informations but I would want a field (maybe in the "Hardware" part in the "Basic info") where I can enter the number of power supplies and maybe another field where I can specified if they are redundant to each other.

**Comment by mkurek** [comment]
@kevinba wait for #1316 - then you'll specify your own additional fields

**Comment by kevinba** [comment]
Ok, thank you very much !
