### ISSUE TITLE
License to VM Assignment

### ISSUE THREAD

**Issue by TheBigfoot** [allegro/ralph#2376]
Hi together,
I tried adding a previously created License to a VirtualServer. Ralph NG crashed with this.

Full error trace can be found here:
http://dpaste.com/3XV85EX

One question about License assignment:
How may i visualize the assignment of a specific License Key to a specific user/device, without adding it as single license?
So creating a License "Windows 7" with 10 different License Keys and then assign them to single devices?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
