### ISSUE TITLE
More VM properties

### ISSUE THREAD

**Issue by TheBigfoot** [allegro/ralph#2377]
Ralph NG:
Will there be a possibility to add more details to a Virtual Machine?

We are working with many virtual machines, so there is a requirement of adding hostnames, cpu cores, memory and storage details to virtual machines, and also having a reference link for the underlying hardware. So knowing if there is too much overcommitment is inevitable.

**Comment by mkurek** [comment]
VMs are work-in-progress feature - we've added it only to show usage (inheritance) of `BaseObject`. We'll add more properties to VMs probably next week.

**Comment by mkurek** [comment]
It's already implemented. Closing.
