### ISSUE TITLE
User/Permission Creation

### ISSUE THREAD

**Issue by TheBigfoot** [allegro/ralph#2378]
Ralph NG:
As you offer an awesome rights management, please add shortcuts to Create "Read Only Users" or "Modify not Delete/Create" Users. Yes there is a group feature, but creating these Groups will be a pain of clicking hundreds of Viewing rights.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
