### ISSUE TITLE
Hide Links to forbidden Features

### ISSUE THREAD

**Issue by TheBigfoot** [allegro/ralph#2379]
Ralph NG:
After having created a read only user, it still gets shown the edit link for a rack item. 
As the user is not allowed to access this he gets access denied after calling. Is it possible to hide the link?

Also somehow related to this issue:
How a can a Read Only user display relations of accessory items to rack items? 
I think there should be an additional view like the one for superusers, just without the edit capability, so having read only input fields or only showing texts.

**Comment by mkurek** [comment]
@TheBigfoot could you provide some links to the views you've mentioned? ex. to view with "edit link for a rack item"?

**Comment by TheBigfoot** [comment]
@mkurek I will provide them, my vagrant machine broke, so I have to set it up again, hope to manage this at the weekend.

**Comment by TheBigfoot** [comment]
![selection_006](https://cloud.githubusercontent.com/assets/746624/15038362/800078a0-12a3-11e6-9a84-607dffe7f26b.png)

For example, when viewing Datacenter Visualization http://localhost:8000/dc_view#/dc/1/rack/1 the edit Link in the table is shown. It links to http://localhost:8000/data_center/datacenterasset/2/ which is return HTTP 403 which is correct but then should not be displayed.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
