### ISSUE TITLE
System to Database/Disk Share Assignment

### ISSUE THREAD

**Issue by TheBigfoot** [allegro/ralph#2380]
RalphNG:
The Features for documenting Databases and Disk Share a a good start but are lacking some features.
There should be a clean possibility to Show the providing Hardware, which is serving these resources. 
As well the accessing resources should be documented, as well with some generic field for documenting access database and rights (For disk shares similar LUNs and access type) 

Also think about clusters service resources.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
