### ISSUE TITLE
Software/Licensing Improvements

### ISSUE THREAD

**Issue by TheBigfoot** [allegro/ralph#2382]
RalphNG:
I'm not that happy with the software/License DB type.

I would like to document all major software items on my hosts. This includes webserver, databases and individual software. 
I would like to see a parent Feature for software for creating e.g.: 
Databases => MySQL => MySQL 5.7
There should be also a possibility to document the software version. Some people might want to make this perfectly accurate with scripts updating the exact release version "5.6.28-1" every night for beeing able to follow outstanding security issues based on the release version. I personally would be happy with documenting the major version. 

About License counting: 
With OpenSource like Apache and MySQL I don't care about License count. Simple Solution: Add Maxint Licenses. Is there am more beautiful solution, while keeping the feature of counting the assignments?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
