### ISSUE TITLE
IP Management

### ISSUE THREAD

**Issue by TheBigfoot** [allegro/ralph#2383]
RalphNG
This might have been discussed before, but I didn't find an issue about this.

For IP addresses there should be an additional field for documenting the segment it is part of. So with a few hundred machines having nearly all an internal + some external IPs + IPMI, not thinking about inter vlan routers. The list will be flooded with entries not being useful with only filters for management and public address. 

Also I would like to see the possibility to add complete subnets, beeing able to assign single entries and having the rest in state "unassigned". So it might also provide a Feature "show me first free Ip in Segment "DC 12 - DMZ". Yes this might collide with DHCP, maybe there will be a flag - in use by DHCP?

About VIPs: I am confused, that I am not able to add a IP in the VIP dialogue. This should be possible and also it must be possible to assign VIPs to multiple devices (Hardware and VMs, even at the same time). I know many setups where the primary system is hardware and the failover system is a smaller VM. The VIP assignments to each host might also contain attributes like "Round Robin, Primary, Secondary, Failover, etc" 
This is somehow related to #2226 

I also found, that I have assigned an IP address to a host, marked this as "management IP" but it is not appearing in the hardware overview table on the right, where in the Location Information box the Management IP address a a simple text field.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
