### ISSUE TITLE
[Discussion] Linux installation agent for monitoring servers

### ISSUE THREAD

**Issue by delize** [allegro/ralph#2405]
Hello,

I noticed that you have the Windows Agent for collecting details on Windows based platforms, but I was wondering if there would be a linux based agent coming anytime soon? I would like to implement a mixture of Ralph (for our datacenter/server room management) and SnipeIT or Jira for the client side. 

However, I don't see any information about this, and would like to confirm if this is a possibility in the future?

Thanks

**Comment by vi4m** [comment]
We're currently working on ralph-cli client, as a discovery solution, for gathering following data:
- server components(disk, processors, etc)
- mac addresses
- basic installed software

**Comment by delize** [comment]
Would this be expandable to run scripts to pull information as well?

Also, while not at all related to the ticket, are you currently working on a mac based agent too?

**Comment by vi4m** [comment]
This is the concept we're working on https://github.com/allegro/ralph-cli So the basic concept is that you can extend scan with custom plugins.

**Comment by vi4m** [comment]
We're not actively working on osx yet.

**Comment by TheBigfoot** [comment]
If you design the client modular enough the Linux version should work on mac as well, only including other modules for installed software inventory?!

**Comment by mkurek** [comment]
@TheBigfoot yes - the client is written in go so it should work fine on windows, linux and osx. The case here are plugins to fetch info from host - if we don't provide plugin for osx, then you'll be able to write your own plugin to get this information (and run it through [ralph-cli](https://github.com/allegro/ralph-cli))

**Comment by delize** [comment]
That sounds great. Would actually make my life a lot easier.

**Comment by mkurek** [comment]
Everything looks clear right now. If you have more questions about the scan, please open an issue in https://github.com/allegro/ralph-cli
