### ISSUE TITLE
API not work

### ISSUE THREAD

**Issue by ist0ne** [allegro/ralph#2411]
curl -X PATCH http://10.101.1.146:8000/api/data-center-assets/2/ -H 'Authorization: Token 6386d276f4ff6eb9b66d39e9dc4218e012ea9b2d' -d '{
    "sn":"4VF9DB3",
}'
{"id":2,"tags":["web"],"created":"2016-05-03T13:10:04","modified":"2016-05-04T06:32:56.978646","remarks":"","hostname":"m6-37-21","sn":"4VF9DBX","barcode":"0110600054","niw":"","required_support":false,"order_no":"","invoice_no":"","invoice_date":null,"price":"0.00","provider":"","depreciation_rate":"25.00","force_depreciation":false,"depreciation_end_date":null,"task_url":"","status":"in use","position":19,"orientation":"front","slot_no":"","source":null,"delivery_date":null,"production_year":null,"production_use_date":null,"management_ip":null,"management_hostname":"","parent":null,"service_env":1,"model":1,"budget_info":null,"property_of":1,"rack":3,"connections":[]}

**Comment by ar4s** [comment]
Please try something like this
`curl -X PATCH http://10.101.1.146:8000/api/data-center-assets/2/ -H 'Authorization: Token 6386d276f4ff6eb9b66d39e9dc4218e012ea9b2d' -d 'sn=4VF9DB3'`

or 

`curl -X PATCH http://10.101.1.146:8000/api/data-center-assets/2/ -H 'Authorization: Token 6386d276f4ff6eb9b66d39e9dc4218e012ea9b2d' -H "Content-Type: application/json" -d '{
"sn":"4VF9DB3",
}'`

**Comment by ist0ne** [comment]
It's work, thinks.

curl -X PATCH http://10.101.1.146:8000/api/data-center-assets/2/ -H 'Authorization: Token 6386d276f4ff6eb9b66d39e9dc4218e012ea9b2d' -H "Content-Type: application/json" -d '{ "sn": "4VF9DB3" }'
{"id":2,"tags":["web"],"created":"2016-05-03T13:10:04","modified":"2016-05-04T11:35:29.397079","remarks":"","hostname":"m6-37-21","sn":"4VF9DB3","barcode":"0110600054","niw":"","required_support":false,"order_no":"","invoice_no":"","invoice_date":null,"price":"0.00","provider":"","depreciation_rate":"25.00","force_depreciation":false,"depreciation_end_date":null,"task_url":"","status":"in use","position":19,"orientation":"front","slot_no":"","source":null,"delivery_date":null,"production_year":2016,"production_use_date":"2016-03-28","management_ip":null,"management_hostname":"","parent":null,"service_env":1,"model":1,"budget_info":null,"property_of":1,"rack":3,"connections":[]}

**Comment by ist0ne** [comment]
I add a new asset, It's error!
"model":["This field is required."]

curl -X POST http://10.101.1.146:8000/api/data-center-assets/ -H 'Authorization: Token 6386d276f4ff6eb9b66d39e9dc4218e012ea9b2d' -d '{"model":1,"hostname":"m6-37-25","status":"in use","service_env":1}'

{"model":["This field is required."]}

**Comment by ar4s** [comment]
@ist0ne add `-H "Content-Type: application/json"` to `curl` like I did in my last comment

**Comment by ist0ne** [comment]
Thinks.

**Comment by a31amit** [comment]
Whoever is trying now, below thing worked for me 

` curl -s -H "Content-Type: application/json" -H "Authorization: Token YOUR-TOKEN_VALUE" -X POST http://localhost:8000/api/data-center-assets/ -d '{"hostname": "myhost.mydomain.tld", "model": 1, "service_env": 1, "status": "new", "rack": 5, "sn": "Unknown", "position": 42}'`
