### ISSUE TITLE
Possible to add Invoices and Quotes?

### ISSUE THREAD

**Issue by danielniccoli** [allegro/ralph#2418]
I am looking for a good and flexible CMDB solution. Ralph 3 looks appealing.

We have a workflow regarding purchases. Get a quote and get it signed by the head of department. Then place the order.

What we do with our current self-built Microsoft Access Solution is:
1. Create a quote object.
2. Add each item to the quote object with price, product number, description, technical details, etc.
3. Add the quote as a pdf to the quote object.

When the quote was signed, we add the signed quote to the quote object as proof.

Now we place the order, the items get shipped and we receive the invoice.
1. We create an invoice object.
2. Add the invoice as a pdf to the invoice object.
3. Link all the items from the quotes to the invoice
4. add the real price to the invoice (prices change if one purchases e.g. a month after the quote)

Then we take stock of what was shipped.
1. Add serial number to the items from the quote/invoice object and assign it to users/hardware and set a status (in use, in stock, etc).

**My question is**: Is it currently possible to do my quote and invoice workflow in Ralph3? Doesn't look like it. Or is it planned to add such a workflow in the future?

**Comment by vi4m** [comment]
The answer: no and yes.

We have customizable workflow mechanism(http://ralph.mkurek.com/transitions/transitionmodel/1/) So you can define e.g. 3 statuses (quoting, purchasing, billing) with custom actions (such as pdf attachment generation with our templating mechanism). 

The missing part could be a Quoting mechanizm(we don't have 'Quote' object), but it should be easy to add it. You could also emulate its mechanism with "Operations" module.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
