### ISSUE TITLE
Is Ralph 3 finished?

### ISSUE THREAD

**Issue by rebeccakandiah** [allegro/ralph#2430]
Hi, 

I just wanted to confirm and see if the creation of Ralph 3 is completely finished or is Ralph 3 still being built? 

Regards, 
Rebecca

**Comment by vi4m** [comment]
I would say it's production stable since couple of months, and a lot of companies already uses it in production. That's why we decided to publish it till the end of May under 3.0 version.

**Comment by vi4m** [comment]
The reason we haven't closed the 3 version is the feedback we got from end users, who needs more functionalities. For example, custom fields will be included in the 3.0 version. We want 3.0 version to be all-inclusive when it comes to migrating existing data, making a transition to ralph, complete.

**Comment by rebeccakandiah** [comment]
Is it possible to give me a date on when it should be completely finished?

**Comment by mkurek** [comment]
@rebeccakandiah what do you mean by 'completely finished'? As @vi4m said, we want to publish 3.0 version till the end of the May and it should cover most (if not all) features from Ralph 2 (we'll fully migrate in our company from Ralph2 to Ralph3 then).

**Comment by pydubreucq** [comment]
Hi,
Could you update the Roadmap please ?
https://github.com/allegro/ralph/wiki/Ralph-3.x-roadmap
Thanks by advance
Best Regards

**Comment by vi4m** [comment]
Updated. Basically, we merged 3.0 + 3.1 + 3.2 into one 'bigger' release.

**Comment by pydubreucq** [comment]
Wow !!! Thanks a lot !!!

**Comment by danmx** [comment]
any news?

**Comment by vi4m** [comment]
I've updated our roadmap, it seems everything is in place. We're tagging our codebase into RC1 stage.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group

**Comment by romcheg** [comment]
But yes, it is :)
