### ISSUE TITLE
ralph migrate fails unless if user ralph_ng exists

### ISSUE THREAD

**Issue by cchongXD** [allegro/ralph#2436]
When I follow the steps on http://ralph-ng.readthedocs.io/en/latest/installation/installation/, I was unable to successfully run "ralph migrate" unless I first created MySQL user "ralph_ng".

It was not found in the docs. It is the expected behavior?

Thank you.

**Comment by mkurek** [comment]
hi @cchongXD. I'm assuming that you're using DEB package, am I right?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
