### ISSUE TITLE
Agent Client for Windows?

### ISSUE THREAD

**Issue by ghost** [allegro/ralph#2454]
Good morning,

Is there an agent to run or install on a windows client?

Thank you

**Comment by ghost** [comment]
I'm try http://ralph.readthedocs.io/en/latest/donpedro.html#installation but not works for me... Someone can help me ? Thk

**Comment by vi4m** [comment]
We haven't ported Windows agent to the Ralph 3 yet. It's on our Roadmap though.

**Comment by ghost** [comment]
Thanks vi4m!

I saw the ralph roadmap , and since it is in development , in addition to discovering hardware components and mac addresses, I think it is not a complicated thing for you also enter all applications like office ( including the license from the registry key ) , shared disks , printer , etc.

In addition to being a useful thing (especially me ) , I think that these additions will make your project even more complete!
