### ISSUE TITLE
Add Switches to DC Visualization ?

### ISSUE THREAD

**Issue by kevinba** [allegro/ralph#2488]
Hi,

Is there a way to add switches in my server room and be able to view some information such as the number of ports, the associated VLAN, consumed ports...

This feature does already exist on Ralph ?
Thank you for your help

**Comment by vi4m** [comment]
No. Currently you can add accestories and provide labels with connections, as a form of replacement.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
