### ISSUE TITLE
Looking for information on Ralph functionality

### ISSUE THREAD

**Issue by greavette** [allegro/ralph#2499]
Hello Team,

Wow!  What an amazing system you've created here.  I've been using Racktables on and off for a few years but your Ralph system looks amazing!  I'm not sure where to post this question so I'm hoping someone can point me in the right direction.

I'm looking to fulfill the following with Ralph to use in our server room:
- Power Usage(Killowatt) tracking.
- HDD including all other components Serial, Warranty Expiry/Installed Date tracking.
- On the shelf inventory tracking.
- IP Subnet Management/Tracking
- vLAN Tracking

Are all the above available within Ralph 3?  I've seen domain tracking and it would appear that each Server has the ability to input the IP for it...but I'm looking to track all IP's (physical servers, virtual, printers, switches...etc).  

Any advice or pointers you can give me would be greatly appreciated.

Thank you.

**Comment by vi4m** [comment]
- Power usage tracking - we have Scrooge billing system for estimated (nominal) power consumption per Asset Model. Not anything automatic, though.
- vlan tracking - you can enter vlan numbers https://ralph-ng.allegrogroup.com/networks/network/add/
- ip subnets tracking - yes, https://ralph-ng.allegrogroup.com/networks/network/add/
- on the shelf tracking - yes
- hdd - we're not using it at the moment, to be tested in depth

**Comment by vi4m** [comment]
Unfortunatelly Back Office assets are not ip-addressable at the moment, so it's not possible to track back office networks usage.

**Comment by greavette** [comment]
Very sorry for not responding to your replies @vi4m  I appreciate you answering my questions!  Great to hear that vlan and IP subnet tracking is available and that I can track items on the shelf.  

I'm taking another look at Ralph now as I've noticed a lot of work has been going on in Ralph these past few months.  I'm very impressed with how Ralph looks now.

I'm very happy to see that I can add in as many memory and hard drives as needed.  But one thing I would need for memory and hard drives is the date of install and perhaps the warranty of each hardware so that I may keep track and be pro-active on when a memory or hard drive is coming close to warranty expiring.  Would these types of fields be considered by the Ralph Developer Team so that we may track when hardware components were installed and/or coming close to expiry?  

Thank you.

**Comment by mkurek** [comment]
Hi @greavette. We are planning to add more features to components module (like installation date etc), but we cannot provide you specific date. We'll handle this topic probably at the beginning of 2017.

**Comment by greavette** [comment]
Hi @mkurek, thank you for this update.  Being able to put in the installation date of key components like hard drives and memory modules would be key for me to begin using Ralph...looking forward to your upcoming changes in 2017!

I'd also like to ask for help on how to use the auto scan feature of Ralph I've heard of.  I believe there is a scan button somewhere on Ralph that will let me scan my network for all IP's...is this true?  How do I use it?

Thank you.

**Comment by mkurek** [comment]
@greavette there is no scan built-in directly into ralph3 (it was built-in in ralph2), but we have new tool for such things - [ralph-cli](https://github.com/allegro/ralph-cli) - it has plugins for different servers types and could push information to ralph. It's also easily extendable so you could write your own scripts (in any language you want) for your servers as well. Check it out!

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
