### ISSUE TITLE
 ralph sitetree_resync_apps ( issue ) during installation.

### ISSUE THREAD

**Issue by 176bis** [allegro/ralph#2506]
Hi Ralph Team,

I can install Ralph successfully and can create account and login to Ralph without error but but got error during installation. I'm not sure this error can affect to my installation.
Thank you,

> ducdm@cmdb:~$ ralph sitetree_resync_apps
> /opt/ralph/ralph-core/lib/python3.4/site-packages/django/contrib/contenttypes/mo                                                                                        dels.py:161: RemovedInDjango19Warning: Model class django.contrib.contenttypes.m                                                                                        odels.ContentType doesn't declare an explicit app_label and either isn't in an a                                                                                        pplication in INSTALLED_APPS or else was imported before its application was loa                                                                                        ded. This will no longer be supported in Django 1.9.
>   class ContentType(models.Model):
> 
> /opt/ralph/ralph-core/lib/python3.4/site-packages/django/contrib/admin/models.py                                                                                        :28: RemovedInDjango19Warning: Model class django.contrib.admin.models.LogEntry                                                                                         doesn't declare an explicit app_label and either isn't in an application in INST                                                                                        ALLED_APPS or else was imported before its application was loaded. This will no                                                                                         longer be supported in Django 1.9.
>   class LogEntry(models.Model):
> 
> /opt/ralph/ralph-core/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango                                                                                        19Warning: django.contrib.contenttypes.generic is deprecated and will be removed                                                                                         in Django 1.9. Its contents have been moved to the fields, forms, and admin sub                                                                                        modules of django.contrib.contenttypes.
>   return f(_args, *_kwds)
> 
> /opt/ralph/ralph-core/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango                                                                                        19Warning: The utilities in django.db.models.loading are deprecated in favor of                                                                                         the new application loading system.
>   return f(_args, *_kwds)
> 
> /opt/ralph/ralph-core/lib/python3.4/site-packages/django/contrib/auth/models.py:                                                                                        41: RemovedInDjango19Warning: Model class django.contrib.auth.models.Permission                                                                                         doesn't declare an explicit app_label and either isn't in an application in INST                                                                                        ALLED_APPS or else was imported before its application was loaded. This will no                                                                                         longer be supported in Django 1.9.
>   class Permission(models.Model):
> 
> /opt/ralph/ralph-core/lib/python3.4/site-packages/django/contrib/auth/models.py:                                                                                        98: RemovedInDjango19Warning: Model class django.contrib.auth.models.Group doesn                                                                                        't declare an explicit app_label and either isn't in an application in INSTALLED                                                                                        _APPS or else was imported before its application was loaded. This will no longe                                                                                        r be supported in Django 1.9.
>   class Group(models.Model):
> 
> /opt/ralph/ralph-core/lib/python3.4/site-packages/django/contrib/auth/models.py:                                                                                        436: RemovedInDjango19Warning: Model class django.contrib.auth.models.User doesn                                                                                        't declare an explicit app_label and either isn't in an application in INSTALLED                                                                                        _APPS or else was imported before its application was loaded. This will no longe                                                                                        r be supported in Django 1.9.
>   class User(AbstractUser):
> 
> /opt/ralph/ralph-core/lib/python3.4/site-packages/taggit/models.py:96: RemovedIn                                                                                        Django19Warning: Model class taggit.models.Tag doesn't declare an explicit app_l                                                                                        abel and either isn't in an application in INSTALLED_APPS or else was imported b                                                                                        efore its application was loaded. This will no longer be supported in Django 1.9                                                                                        .
>   class Tag(TagBase):
> 
> /opt/ralph/ralph-core/lib/python3.4/site-packages/taggit/models.py:201: RemovedI                                                                                        nDjango19Warning: Model class taggit.models.TaggedItem doesn't declare an explic                                                                                        it app_label and either isn't in an application in INSTALLED_APPS or else was im                                                                                        ported before its application was loaded. This will no longer be supported in Dj                                                                                        ango 1.9.
>   class TaggedItem(GenericTaggedItemBase, TaggedItemBase):
> 
> /opt/ralph/ralph-core/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango                                                                                        19Warning: django.utils.importlib will be removed in Django 1.9.
>   return f(_args, *_kwds)
> 
> /opt/ralph/ralph-core/lib/python3.4/site-packages/django/forms/fields.py:1230: R                                                                                        emovedInDjango19Warning: IPAddressField has been deprecated. Use GenericIPAddres                                                                                        sField instead.
>   RemovedInDjango19Warning)
> 
> Traceback (most recent call last):
>   File "/opt/ralph/ralph-core/bin/ralph", line 9, in <module>
>     load_entry_point('ralph==3.0.0', 'console_scripts', 'ralph')()
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/**main**.py", li                                                                                        ne 29, in prod
>     main('ralph.settings.prod')
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/**main**.py", li                                                                                        ne 14, in main
>     execute_from_command_line(sys.argv)
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management                                                                                        /**init**.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management                                                                                        /**init**.py", line 346, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management                                                                                        /base.py", line 394, in run_from_argv
>     self.execute(_args, *_cmd_options)
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/django/core/management                                                                                        /base.py", line 445, in execute
>     output = self.handle(_args, *_options)
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/sitetree/management/co                                                                                        mmands/sitetree_resync_apps.py", line 25, in handle
>     tree_modules = import_project_sitetree_modules()
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/sitetree/utils.py", li                                                                                        ne 134, in import_project_sitetree_modules
>     module = import_app_sitetree_module(app)
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/sitetree/utils.py", li                                                                                        ne 121, in import_app_sitetree_module
>     sub_module = import_module('%s.%s' % (app, module_name))
>   File "/opt/ralph/ralph-core/lib/python3.4/importlib/**init**.py", line 109, in                                                                                         import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1467, in exec_module
>   File "<frozen importlib._bootstrap>", line 1572, in get_code
>   File "<frozen importlib._bootstrap>", line 1532, in source_to_code
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/admin/sitetrees.                                                                                        py", line 304
>     *cross_validation_items
>                    ^
> SyntaxError: can use starred expression only as assignment target`

**Comment by mkurek** [comment]
Hi @176bis . This bug was fixed few days ago. Please fetch the latest snapshot of deb package and confirm if it's working.

**Comment by 176bis** [comment]
Yup...you're right. Many thanks, Mkurek.
