### ISSUE TITLE
add Weight and Power to Asset Model and sum totals in DC Visualization

### ISSUE THREAD

**Issue by knippers** [allegro/ralph#2515]
I have a feature request. Would it be possible to add Weight (KiloGram) and Power (Watt) to the AssetModel. And display the sum/total Weight and Power in DC Vizualization per rack for all Assets in the rack that have AssetModels attached with Weight and Power filled-in. 
Using custom fields per Asset allows for the registration of the Weight and Power but you can't do much more with it.
Thanks for considering to add this feature.

**Comment by vi4m** [comment]
When it comes to power usage, we already have it in the asset model.

**Comment by vi4m** [comment]
<img width="522" alt="zrzut ekranu 2016-07-15 o 13 48 21" src="https://cloud.githubusercontent.com/assets/552398/16873355/f7bc6e7c-4a92-11e6-8bc1-0452a9635b43.png">

**Comment by vi4m** [comment]
Displaying total power usage / weight per rack sounds like a good idea, i like it.

**Comment by Vaygh** [comment]
Forgive me if I missed it in the documentation, but what unit is the "Power consumption" field in? It seems to be an integer value, so I'm guessing it's not amps, but I'd like to know for sure. Thanks!

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
