### ISSUE TITLE
delete DC rack and hardware problem

### ISSUE THREAD

**Issue by daro1337** [allegro/ralph#2580]
RACK:
OperationalError at /data_center/rack/
(1054, "Unknown column 'assets_genericcomponent.model_name' in 'field list'")
Request Method: POST
Request URL:    http://x.x.x.x:8000/data_center/rack/
Django Version: 1.8.12
Exception Type: OperationalError
Exception Value:  
(1054, "Unknown column 'assets_genericcomponent.model_name' in 'field list'")
Exception Location: /opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/connections.py in query, line 280
Python Executable:  /opt/ralph/ralph-core/bin/python
Python Version: 3.4.3
Python Path:  
['/opt/ralph/ralph-core/bin',
 '/opt/ralph/ralph-core/lib/python3.4',
 '/opt/ralph/ralph-core/lib/python3.4/plat-x86_64-linux-gnu',
 '/opt/ralph/ralph-core/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/opt/ralph/ralph-core/lib/python3.4/site-packages']
Server time:    Thu, 14 Jul 2016 12:11:57 +0200

Hardware:

OperationalError at /data_center/datacenterasset/
(1054, "Unknown column 'assets_genericcomponent.model_name' in 'field list'")
Request Method: POST
Request URL:    http://x.x.x.x:8000/data_center/datacenterasset/
Django Version: 1.8.12
Exception Type: OperationalError
Exception Value:  
(1054, "Unknown column 'assets_genericcomponent.model_name' in 'field list'")
Exception Location: /opt/ralph/ralph-core/lib/python3.4/site-packages/MySQLdb/connections.py in query, line 280
Python Executable:  /opt/ralph/ralph-core/bin/python
Python Version: 3.4.3
Python Path:  
['/opt/ralph/ralph-core/bin',
 '/opt/ralph/ralph-core/lib/python3.4',
 '/opt/ralph/ralph-core/lib/python3.4/plat-x86_64-linux-gnu',
 '/opt/ralph/ralph-core/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/opt/ralph/ralph-core/lib/python3.4/site-packages']
Server time:    Thu, 14 Jul 2016 12:15:20 +0200

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
