### ISSUE TITLE
Query regarding latest stable version

### ISSUE THREAD

**Issue by cgoswami** [allegro/ralph#2645]
Hi this more of query than issue, could you tell me the latest stable version from deb packages, i installed the latest but seems to have issues and then i installed another version but it too had issues 404 on all static file.

Since the docs dont mention it could you tell me the latest stable version on a fresh ubuntu 14.04 ?

**Comment by vi4m** [comment]
Probably it's the settings/prod.py bug - you should set DEBUG=True in it

**Comment by vi4m** [comment]
Link: https://github.com/allegro/ralph/issues/2478
