### ISSUE TITLE
Installation issue 

### ISSUE THREAD

**Issue by cgoswami** [allegro/ralph#2658]
I have the following error   **Applying supports.0001_initial...Killed** after the first raplh migrate during installation, i dropped the DB and restarted the migration, no effect, the prod.py has DEBUG = True,

`Operations to perform:
  Synchronize unmigrated apps: humanize, dc_view, taggit_serializer, import_export, ralph_admin, mptt, table, rest_framework, ralph2_sync, foundation, messages, django_rq, permissions, staticfiles
  Apply all migrations: sitetree, auth, admin, licences, data_center, virtual, dashboards, back_office, transitions, operations, data_importer, external_services, reversion, accounts, supports, custom_fields, taggit, assets, contenttypes, authtoken, dhcp, deployment, networks, attachments, security, domains, sessions, reports
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0001_initial... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying accounts.0001_initial... OK
  Applying accounts.0002_auto_20151204_0758... OK
  Applying accounts.0003_region_country... OK
  Applying accounts.0004_region_stocktaking_enabled... OK
  Applying admin.0001_initial... OK
  Applying taggit.0001_initial... OK
  Applying taggit.0002_auto_20150616_2121... OK
  Applying assets.0001_initial... OK
  Applying assets.0002_auto_20151125_1354... OK
  Applying assets.0003_auto_20151126_2205... OK
  Applying assets.0004_auto_20151204_0758... OK
  Applying assets.0005_category_depreciation_rate... OK
  Applying assets.0006_category_show_buyout_date... OK
  Applying assets.0007_auto_20160122_1022... OK
  Applying assets.0008_auto_20160122_1429... OK
  Applying assets.0009_auto_20160307_1138... OK
  Applying assets.0010_auto_20160405_1531... OK
  Applying assets.0011_auto_20160603_0742... OK
  Applying assets.0012_auto_20160606_1409... OK
  Applying assets.0013_auto_20160615_2140... OK
  Applying assets.0014_memory... OK
  Applying assets.0015_auto_20160701_0952... OK
  Applying assets.0016_fibrechannelcard... OK
  Applying assets.0017_processor... OK
  Applying assets.0018_disk... OK
  Applying assets.0019_auto_20160719_1443... OK
  Applying supports.0001_initial...Killed`

**Comment by vi4m** [comment]
It looks like ... someone murdered your python process ;-) out of memory ? How much memory have you assigned to your Ralph machine ?

**Comment by cgoswami** [comment]
hi Vi4m what is the recommended minimum on a vagrant box ?

**Comment by mkurek** [comment]
@cgoswami 1024 MB will work for sure, but you could try with lower values too (maybe 512 MB will be sufficient).

**Comment by cgoswami** [comment]
thanks for the info, all working now, closing this issue
