### ISSUE TITLE
Cannot import Asset Model

### ISSUE THREAD

**Issue by shinogata** [allegro/ralph#2668]
Hi team,

Similar to #2667 but seems a little different.

When I try to import "Asset model", it always produces errors after "submit" was clicked.
I used an Excel file (*.xls) just exported from Ralph itself, and it still occurs even if I removed "assets_count" row from the Excel sheet. It also happens in *.csv as well (not tested in other formats).
FYI I have no issue in importing other fields from *.xls.

Shin

---

Line number: 1 - 'AssetModel' object has no attribute 'assets_count'
OrderedDict([('manufacturer', 1.0), ('manufacturer_str', 'Dell'), ('category', 4.0), ('category_str', 'Laptop PC'), ('id', 14.0), ('name', 'Inspiron 15'), ('created', '2016-06-17 04:34:25'), ('modified', '2016-06-17 04:34:25'), ('type', 1.0), ('power_consumption', 0.0), ('height_of_device', '0.0'), ('cores_count', 0.0), ('visualization_layout_front', 1.0), ('visualization_layout_back', 1.0), ('has_parent', '0')])

Traceback (most recent call last):
File "/opt/ralph/ralph-core/lib/python3.4/site-packages/import_export/resources.py", line 384, in import_data
real_dry_run)
File "/opt/ralph/ralph-core/lib/python3.4/site-packages/import_export/resources.py", line 294, in get_diff
v1 = self.export_field(field, original) if original else ""
AttributeError: 'AssetModel' object has no attribute 'assets_count'
...

![asset-model](https://cloud.githubusercontent.com/assets/20832905/17393116/7e896ada-5a5c-11e6-9be5-6a92e96a29f8.PNG)

**Comment by shinogata** [comment]
Probably something to do with #2268 .

**Comment by willowpet** [comment]
any news for this issue ?

**Comment by vi4m** [comment]
@mkurek @ar4s

**Comment by managai** [comment]
experienced same problem, working with json
as workaround I removed category (leaving category_str)
asset model import works but, as expected , no asset category is set for imported models

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
