### ISSUE TITLE
__str__ improvements

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#2731]
For Change management systems which use our API, we use **str** for filtering and displaying CI's. Currently **str** includes direct ORM information, such as "data center asset" which is not concrete enough to be usable to the user. 

<img width="787" alt="zrzut ekranu 2016-08-17 o 10 54 21" src="https://cloud.githubusercontent.com/assets/552398/17730497/3042c01c-6469-11e6-9986-15b483201583.png">

Therefore i propose to change autocomplete information with more detailed information, (might be included from categories) such as "blade server", "printer", "rack" for assets. 

It can be done with changing current data center`__str__` logic to do more reflections about the inherited type.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
