### ISSUE TITLE
Demo of Ralph

### ISSUE THREAD

**Issue by rebeccakandiah** [allegro/ralph#2774]
Hi, 
We are looking to see if anyone will be able to provide our company a demo of Ralph. We also would like someone who can help evaluate our current asset management tool and see if Ralph can fulfill our needs. If anyone is available to help us please let me know.

**Comment by gerickt** [comment]
this demo: http://ralph-demo.allegro.tech/login/?next=/

doesnt works... the login & password: ralph
not login...

i looking for a live demo, because cant install
[https://github.com/allegro/ralph/issues/2799](url)

**Comment by vi4m** [comment]
We will reset demo instance on Monday.

**Comment by ar4s** [comment]
@gerickt try demo:demo

**Comment by mkurek** [comment]
ralph:ralph should work fine now too

**Comment by vi4m** [comment]
Demo is online 24/365. Closing.

**Comment by funyfizik** [comment]
cant login with ralph or demo login/pass
