### ISSUE TITLE
Delete the data with bulk 

### ISSUE THREAD

**Issue by ti22406** [allegro/ralph#2801]
Hi, thanks for deploying the app, this is really helpful for us.
We are deploying the apps in our company and will migrate the data in the spread sheet to Ralph this week.  We have one simple question here, I know the data can be imported/exported and it is feasible to have bulk upload using import function, however, not sure how to do the "Bulk-Delete" on Ralph.  Yes, we can delete the data one by one via Web site but we are sure that we will have the opportunities to delete lots of entry in one time.  It is time-consuming delete the date one by one manually so would like to know how to do "Bulk Delete".  Your advice will be appreciated.

**Comment by mkurek** [comment]
Hi @ti22406. You could either select multiple items on the list (see screenshot below) and then use `Actions` -> `Delete selected ...` or use ralph's shell (run `ralph shell` in command line) if you're familiar with Django.

<img width="1412" alt="screen shot 2016-09-13 at 07 42 39" src="https://cloud.githubusercontent.com/assets/107437/18462805/c7e65470-7985-11e6-991f-45cc24ff79c1.png">

**Comment by ti22406** [comment]
Thank you for quick reply!

iPhone$B$+$iAw?.(B

2016/09/13 14:44$B!"(BMateusz Kurek <notifications@github.com<mailto:notifications@github.com>> $B$N%a%C%;!<%8(B:

Hi @ti22406https://github.com/ti22406. You could either select multiple items on the list (see screenshot below) and then use Actions -> Delete selected ... or use ralph's shell (run ralph shell in command line) if you're familiar with Django.

[screen shot 2016-09-13 at 07 42 39]https://cloud.githubusercontent.com/assets/107437/18462805/c7e65470-7985-11e6-991f-45cc24ff79c1.png

##

**Comment by vi4m** [comment]
Ok, closing then.
