### ISSUE TITLE
REP 15: Integration tests

### ISSUE THREAD

**Issue by ar4s** [allegro/ralph#2808]
# Introduction

We have few external services like DNSaaS (via REST API) or DHCP (via configuration agent) and we don't have any integration tests.
# Proposal of solution

Run linked containers (by docker-compose) on Travis and write some integration tests.
Services to test:
1. DNSaaS
2. DHCP
3. InkPy
# To discuss

Can we interpret `Vagrant` as a service? Anyway, `Vagrantfile` need to be test.

**Comment by vi4m** [comment]
+1

I would say, the best option is to use docker instead of vagrant. Docker make sense only if it's used both in development and production. That's the purpose to have it.

**Comment by romcheg** [comment]
Not relevant
