### ISSUE TITLE
Server parts management

### ISSUE THREAD

**Issue by spuzirev** [allegro/ralph#2842]
Hi.
I'm trying to find following feature, but I can't.

We have lots of servers and we have lots of parts of servers, for example, HDDs, SSDs, motherboards, NICs, etc. All of them have their own serial numbers and positions inside servers, for example HDD's can be located in specified physical slot on the front panel and memory units can be located in cpecified DIMM-slots on the motherboard.

Is there any useful way to manage parts of hardware? I tried to create "Asset model" with "part" type and adding datacenter asset with server parent, but later I cannot find any links between server (parent) and HDD (child).

Ralph has the concept of Components, but unfortunately there is no way to manage components itself. I can't move some component from one Datacenter Asset to another one.

What is the right way?

Thank you.

**Comment by vi4m** [comment]
This is work in progress for now - we will update Asset to have "parts" links in it. Cannot promise any timeline, though.

**Comment by Tibshot** [comment]
Hello @vi4m,

Is there any branch to track/debug/add feature ?

Thanks,

Tib

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
