### ISSUE TITLE
Features Comparision with Latest Ralph 3.0 and Previous Ralph 2.X

### ISSUE THREAD

**Issue by rifnasahd** [allegro/ralph#2853]
Hi @vi4m @mkurek

I'm very new to Ralph and went through V3 and V2.X documentation. Can you please verify me whether following features avaialbe in Ralph 3.0 version?

Is there any link to compare available features of version 3.0 and 2.X?

1. scan networks automatically through periodic or manual scans and identify.

2. deploy servers by generating appropriate DNS/DHCP configs and uses I/PXE method.

3. see relations between Configuration Items using CMDB view interface

4. calculate TCO of Services using complex utilization of bare metal costs, IT Support work time, virtualization costs

5. integrate OpenStack billings with hardware costs

6. Configure DHCP Agent

7. Windows Agent 

8. Third party tool integration like zabbix, jira

Thank you.!

**Comment by greavette** [comment]
Great question!  I'm also very interested in these answers.  We use Zabbix exentisvely in our office so having third part integration into Zabbix would be very helpful!

I've opened an issue a while back asking a question about automatic discovery.  https://github.com/allegro/ralph/issues/2499.  There is a ralph-cli tool that was mentioned (I still need to test it out myself).  The Windows Agent was one that I would be very interested in as well.  Hopefully you'll get a response soon.

**Comment by mkurek** [comment]
Hi @rifnasahd @greavette 

> scan networks automatically through periodic or manual scans and identify.

You could do this using ralph-cli (although it's not possible right to scan whole network at once - we have this in our [roadmap](http://ralph-cli.readthedocs.io/en/latest/development/#sooner), but right now you'll have to run this command for each ip in network)

> deploy servers by generating appropriate DNS/DHCP configs and uses I/PXE method.

yes - ralph could generate DHCP configs and deploy servers using (i)PXE. We should add this section to the documentation.

About DNS - Ralph could be integrated with [django-powerdns-dnssec](https://github.com/allegro/django-powerdns-dnssec) which is basically wrapper (self-service) around PowerDNS.

> see relations between Configuration Items using CMDB view interface

I don't know what are you talking about :) Could you give us some example of it (in Ralph2)?

> calculate TCO of Services using complex utilization of bare metal costs, IT Support work time, virtualization costs

Yes - there is [(ralph_)scrooge](https://github.com/allegro/ralph_pricing) (a.k.a ralph_pricing -> will rebrand it to just "scrooge" soon) which handles all costs calculation (and fetches data for example from Ralph)

> integrate OpenStack billings with hardware costs

Yes, but's it's done in Scrooge. 

> Configure DHCP Agent

Yes - [DHCP agent provided by us](https://github.com/allegro/ralph/blob/ng/contrib/dhcp_agent/dhcp_agent.py) could be parametrized:

```
Usage: dhcp_agent.py [options]

Update configuration in DHCP server.

Options:
  -h, --help            show this help message and exit
  -H HOST, --host=HOST  Ralph instance host.
  -k KEY, --key=KEY     Ralph API key.
  -m SECTIONS, --sections=SECTIONS
                        Choose what part of config you want to upgrade.
                        [Default: all; Options: networks, entries]
  -l LOG_PATH, --log-path=LOG_PATH
                        Path to log file. [Default: STDOUT]
  -c DHCP_CONFIG_ENTRIES, --dhcp-config-entries=DHCP_CONFIG_ENTRIES
                        Path to the DHCP entries configuration file.
  -n DHCP_CONFIG_NETWORKS, --dhcp-config-networks=DHCP_CONFIG_NETWORKS
                        Path to the DHCP networks configuration file.
  -p PROTO, --proto=PROTO
  -e NET_ENV, --net-env=NET_ENV
                        Only get config for the specified network environment.
  -d DC, --dc=DC        Only get config for the specified data center.
  -r, --restart         Restart service after fetching config?
  -v, --verbose         Increase verbosity.
  -s DHCP_SERVICE_NAME, --dhcp-service-name=DHCP_SERVICE_NAME
                        Name of the service to restart.
```

> Windows Agent

It's on ralph-cli's [roadmap](http://ralph-cli.readthedocs.io/en/latest/development/#ideas-for-future-development) too (afaik ralph-cli use some system-dependent commands which are working right now on linux and osx only - @xor-xor might confirm that)

> Third party tool integration like zabbix, jira

We're not integrated with any of it by default, but it should be pretty straightforward to do this. I know that some monitoring guys in allegro integrated zabbix with custom fields with Ralph. About jira integration - we'll be working in the near future (in Operations module, to fetch all issues from jira related to some `BaseObject` in Ralph)

**Comment by xor-xor** [comment]
> afaik ralph-cli use some system-dependent commands which are working right now on linux and osx only - @xor-xor might confirm that

AFAIR all this boils down to user permissions and home dir handling.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
