### ISSUE TITLE
Cannot remove BO from menu

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#2856]
Cannot remove BO menu (with all its items) from main menu. Operating on groups permissions (all users belong to a single group) doesn't help.

**Comment by mkurek** [comment]
Aren't they superusers? Could you send dump (printscreen) of whole page with permissions definitions for this group and print screen of menu after logging as a user in this group?

**Comment by damian1976** [comment]
Ok, so the situation looks as follows:
1/ I'm the superuser and the other users are regular, staff users belonging to a single (LDAP) group
2/ From superuser account I'd like to disable BO menu (and possibly any other functionality later on)
3/ Currently the group has the following permissions set:

![permissions](https://cloud.githubusercontent.com/assets/9283029/20098547/b8eb7c92-a5b4-11e6-910b-12deaab04300.png)

**Comment by mkurek** [comment]
And what do you see in menu? All (3) items?

**Comment by damian1976** [comment]
![menu](https://cloud.githubusercontent.com/assets/9283029/20098960/89206c96-a5b6-11e6-963d-cc3e9d798121.PNG)
![menu_bo](https://cloud.githubusercontent.com/assets/9283029/20099286/00aa8778-a5b8-11e6-8eab-c1610350ac4f.png)

**Comment by mkurek** [comment]
i mean back office (sub)menu

**Comment by damian1976** [comment]
screenshot updated

**Comment by damian1976** [comment]
OK. Warehouse & office infrastructure needed to be unchecked too.
