### ISSUE TITLE
Main page/dashboard: wrong links?

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph#2857]
Within the main page & dashboard:
when hovering & clicking on circles representing Server Rooms the following links are built: https://ADDRESS/dc_view#/dc/DC_NUMBER
However, the circles should point to SRs, not DCs, so the links for the circles should look like:
https://ADDRESS/dc_view#/sr/SR_NUMBER

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
