### ISSUE TITLE
Custom Fields for IP Addresses

### ISSUE THREAD

**Issue by hanej** [allegro/ralph#2866]
We would like to use Ralph to also track our multicast IP address usage and to do so effectively, we will need to use custom fields as part of the IP address record.  Since a multicast IP can span multiple hostnames we will need to track which application and environment a multicast IP is assigned.  I don't see a way to do this currently.

**Comment by mkurek** [comment]
Custom fields are using django's content types, so it should be easy to do this.

Things to do:
1. use `CustomFieldMeta` (like here: https://github.com/allegro/ralph/blob/615d68bf64ac1e7735fd30d101d6dd8781155ec0/src/ralph/assets/models/configuration.py#L17-L19)
2. inherit from `WithCustomFieldsMixin` (like here: https://github.com/allegro/ralph/blob/615d68bf64ac1e7735fd30d101d6dd8781155ec0/src/ralph/assets/models/configuration.py#L23)
3. mix `WithCustomFieldsSerializerMixin` to api serializer (like here: https://github.com/allegro/ralph/blob/615d68bf64ac1e7735fd30d101d6dd8781155ec0/src/ralph/assets/api/serializers.py#L209)

Places to touch:
https://github.com/allegro/ralph/blob/ng/src/ralph/networks/models/networks.py#L586
https://github.com/allegro/ralph/blob/ng/src/ralph/networks/api.py#L43

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
