### ISSUE TITLE
Ralph 3: Upgrade to latest version causes error.

### ISSUE THREAD

**Issue by mywatch** [allegro/ralph#2881]
Hi Ralph-Team,

We are using Ralph build (Version: 3.0.0-snapshot-20160607-5736) in our production. 

On above setup we found below issues. 

a. Ralph ACL issue for Bulk Update.
b. ACL does not work on Back Office.
c. Import function does not work on "Support" Tab.

So we decided to use later build (Version: 3.0.0-snapshot-20161115-7304).

With the latest build we observed that the database schema is changed. Hence our production database dump into the latest build setup is not 100% successful. With this incomplete import, some of the menus throws an error message as provided in attachment.

It would be a great savior if you could provide us some migration steps/ scripts that can take care of latest database changes. 

Please revert me back if you required any information. 

![ralphissue](https://cloud.githubusercontent.com/assets/14229096/20787899/900c4abe-b7f1-11e6-8c52-9f5bb58acaa6.jpg)

**Comment by vi4m** [comment]
@ar4s @xliiv  can you take a look  ?

**Comment by vi4m** [comment]
did you run `ralph migrate` after the upgrade?

**Comment by mywatch** [comment]
Thanks for your reply!

Yes I performed $ralph migrate

It throws error complaining table already exists.

**Comment by mywatch** [comment]
Here is console output of my attempts to various ralph options.

[Console Output for Ralph Issue in GIT 5Nov16.txt](https://github.com/allegro/ralph/files/630331/Console.Output.for.Ralph.Issue.in.GIT.5Nov16.txt)

**Comment by vi4m** [comment]
@xliiv i think we can skip failiing migration with --fake [something] flag,right ? How to do it here?

It failed here on  `Applying assets.0012_auto_20160606_1409...Traceback (most recent call last):`
with:
`_mysql_exceptions.OperationalError: (1050, "Table 'assets_configurationclass' already exists")`

**Comment by ghost** [comment]
We could skip this migration by this:
`ralph migrate assets 0012 --fake`
and then run
`ralph migrate`

To see the progress you can do like this:
```
$ ralph migrate assets --list
assets
 [X] 0001_initial
 [X] 0002_auto_20151125_1354
 [X] 0003_auto_20151126_2205
 [X] 0004_auto_20151204_0758
 [X] 0005_category_depreciation_rate
 [X] 0006_category_show_buyout_date
 [X] 0007_auto_20160122_1022
 [X] 0008_auto_20160122_1429
 [X] 0009_auto_20160307_1138
 [X] 0010_auto_20160405_1531
 [X] 0011_auto_20160603_0742
 [ ] 0012_auto_20160606_1409
 [ ] 0013_auto_20160615_2140
..
```
then run
`ralph migrate assets 0012 --fake`
should produce something like this:
```
$ ralph migrate assets --list
assets
 [X] 0001_initial
 [X] 0002_auto_20151125_1354
 [X] 0003_auto_20151126_2205
 [X] 0004_auto_20151204_0758
 [X] 0005_category_depreciation_rate
 [X] 0006_category_show_buyout_date
 [X] 0007_auto_20160122_1022
 [X] 0008_auto_20160122_1429
 [X] 0009_auto_20160307_1138
 [X] 0010_auto_20160405_1531
 [X] 0011_auto_20160603_0742
 [X] 0012_auto_20160606_1409
 [ ] 0013_auto_20160615_2140
..
```

**Comment by mywatch** [comment]
On a setup with my Prod build and Prod Data, I followed suggested steps.  Same can be viewed in attached sheet.

Above approach doesn't solve our problem. By skipping 0012, migration failed further for 0014.

_Applying assets.0014_memory...Traceback (most recent call last):_

So I tried skipping one by one as per error message and again reach to our first error as:

_Applying assets.0012_auto_20160606_1409...Traceback (most recent call last):_

[Console Output for Ralph Issue in GIT 8Nov16.txt](https://github.com/allegro/ralph/files/638298/Console.Output.for.Ralph.Issue.in.GIT.8Nov16.txt)

**Comment by ghost** [comment]
@mywatch catch me on gitter, ok?

**Comment by mywatch** [comment]
We found, in our environment some how 27 extra tables are created and they are empty.
So after deleting all of them, our migration is successful. So I am closing this task. 

Huge thanks to Ralph team (Special thanks to @xliiv) for their help and support.
 
[ExtraTables In Prod DB.txt](https://github.com/allegro/ralph/files/660386/ExtraTables.In.Prod.DB.txt)

[SuccessFullMigration13Dec16.txt](https://github.com/allegro/ralph/files/660394/SuccessFullMigration13Dec16.txt)
