### ISSUE TITLE
Ralph Development Environment setup: Vagrant up doesn't activate virtual environment

### ISSUE THREAD

**Issue by mywatch** [allegro/ralph#2889]
Dear Ralph-team

Vagrant up command doesn't activate the virtual environment. Though file exists at /home/vagrant/bin/activate. Please find the whole command output in attached file.

$ vagrant up
.
.
.
.
.
.
.2.0 pytz-2015.4 ralph redis-2.10.3 requests-2.9.1 rq-0.5.6 simplegeneric-0.8.1 simplejson-3.8.2 six-1.10.0 snowballstemmer-1.2.1 sphinx-1.5 sqlparse-0.1.16 stevedore-1.12.0 tablib-0.11.2 tornado-4.4.2 traitlets-4.3.1 urwid-1.3.1 wcwidth-0.1.7 wrapt-1.10.6
: No such file or directory.profile: line 24: /home/vagrant/bin/activate
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

[VagrantUp_8Dec16.txt](https://github.com/allegro/ralph/files/639048/VagrantUp_8Dec16.txt)

**Comment by ghost** [comment]
Did you try rebuild your vagrant image?
Be aware that this WILL DESTROY your current image..

```
vagrant destroy
vagrant up
```

**Comment by mywatch** [comment]
I have used Windows for setting Ralph development environment and it seems this could be the issue. 
So closing this issue. 
Note: It would be nice to make development environment available for windows users as well.
