### ISSUE TITLE
Cannot run ralph migrate (Errno 13)

### ISSUE THREAD

**Issue by Rhaelyx** [allegro/ralph#2895]
Hello,

I get a permission error when running Ralph migrate. I've run source ~/.profile after editing it.

This is a clean install ubuntu 14.04 (Used the wiki install page)

When I use command with user and password from .profile.
'mysql -u root -p 'password' -h localhost ralph'. The login is succesful.

[Pastebin full error](http://pastebin.com/6ki5XPzx)

**Comment by vi4m** [comment]
I think you should run ralph migrate as a root user

**Comment by Rhaelyx** [comment]
I'm by no means a Linux expert. But I'm pretty sure that my user is a root user. I checked with the command ID.

`uid=1000(myuser) gid=1000(myuser) groups=1000(myuser),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lpadmin),111(sambashare)`

When I try sudo ralph migrate it says `sudo: ralph: command not found`
I'm assuming this is because $path changes when I use sudo. (Based on my google finds)

**Comment by Rhaelyx** [comment]
I ued the `sudo env "PATH=$PATH"` command in front of ralph migrate. Now it gives me the following error.

[Pastebin](http://pastebin.com/CNEJRBXY)

**Comment by ghost** [comment]
`_mysql_exceptions.OperationalError: (1045, "Access denied for user 'ralph_ng'@'localhost' (using password: YES)")`
According to the above the connection with db can't be settled.
Make sure you can connect to your db, and use these credentials in settings.

**Comment by Rhaelyx** [comment]
As per [this issue](https://github.com/allegro/ralph/issues/2680) it first suggest I need to create user ralph_ng. But it corrects by saying that running source ~/.profile is sufficient.

Seeing that it's not documented that I need to create this user I'm uncertain how to proceed. I have tested the credentials that are entered here.

export DATABASE_NAME=ralph
export DATABASE_USER=root
export DATABASE_PASSWORD=********
export DATABASE_HOST=127.0.0.1
export PATH=/opt/ralph/ralph-core/bin/:$PATH
export RALPH_DEBUG=1

'mysql -u root -p 'password' -h localhost ralph'. The login is succesful.

**Comment by vi4m** [comment]
@xliiv we should clean up this docs with custom user creating

**Comment by ghost** [comment]
@Oreios creating superuser is similar to Django version, like this:
https://docs.djangoproject.com/en/1.10/intro/tutorial02/#creating-an-admin-user
but you should replace `$ python manage.py` with `ralph`, so the whole command is:
`$ ralph createsuperuser`
After this, follow the steps from above link.

*Contribution opportunity*
When you success you can fix the documentation, how about that? ;)

**Comment by Rhaelyx** [comment]
@xliiv Even though creating a superuser is on step 3 and I'm still on step 1. I went ahead and tried the command. However it tells me '$: command nog found'.

I'm by all means just an amateur linux user, getting by with lots of internet help. Not sure I'd trust myself with an installation document.

**Comment by ghost** [comment]
Could you catch me on Gitter https://gitter.im/allegro/ralph ?

**Comment by Rhaelyx** [comment]
After verifying many files and settings with @xliiv. Somewhere in /settings/base.py I made a change that later got reverted trough a snapshot. Then we proceeded to verify the names trough ralph shell. Using this information logged in to the SQL and exited out.

Running ralph migrate worked perfectly now. In theory we didn't change any files. Only verified some.
