### ISSUE TITLE
Asset holder vs user

### ISSUE THREAD

**Issue by exebit** [allegro/ralph#2900]
Hello,
Assets and licences have a field **Property of**. It is an **Asset Holder** entity. On the other side users have **My equipment** info, it's always empty. Is it bug of existance of two same entities?

**Comment by mkurek** [comment]
Asset Holder entity (and field property of, which is related to it) is used (at least in our case) for storying **companies** (which owns financial rights for some asset, for example they bought it). It's useful when ralph is used to store information about assets from multiple companies.

On the other hand my equipment is for **users** which are owning (or using) particular asset - when you fill user/owner field, this asset will be shown in this user's "my equipment" view. (In practice, owner and user will have the same value, but in some cases it might be useful to set it to different values, for example owner is superior of user)

So, for example: 
* create new "Asset Holder" object, let's say "Allegro"
* set "property of" field of some asset X to "Allegro", which means, that this company has bought this asset
* set "owner" and "user" field to "mkurek", which means, that I'm using this asset (and owning it "inside company")
* this asset is visible in "mkurek's" my equipment view

**Comment by exebit** [comment]
Oh, I see, backoffice equipment has such fields. Thanx!
