### ISSUE TITLE
Feature request for Hardware Components

### ISSUE THREAD

**Issue by greavette** [allegro/ralph#2922]
Hello @vi4m  @mkurek ,

Happy New Year to the Ralph community!

I'd like to make a suggestion on adding custom fields for any component on the Hardware tab.  In my case I would like to add to the existing fields already existing in the components section in the slot number for each Memory Module and the date of install.  For our Hard Drives I will need to add in the bay the drive is installed in, the date of install as well as the expiry date for warranty on that drive.  While my requirements may not be needed for others I'd like to suggest that custom fields can be added so people can add in whatever they need to a component.  In this way Ralph developers don't need to add in fields that may not be needed by everyone and people can configure components to what they need.  I see that there already is a custom fields section at the bottom of basic info section where we can add in the custom field in the settings.  Perhaps this code can be reused to add in custom fields to the components as well?  

Thank you.

**Comment by vi4m** [comment]
Thanks for your request. I think the "components" area is something we're interested in extending in terms of functionality.

**Comment by greavette** [comment]
Thank you for the reply @vi4m !  Looking forward to seeing Ralph extend it's functions even further in 2017.  It looks like a great project so far.

**Comment by greavette** [comment]
Hello @vi4m  and @mkurek ,

Is pull request 2948 related to this request to add in custom fields to components in the Hardware tab/section of Ralph?

Thank you.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
