### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by spinnnor** [allegro/ralph#2928]
Hi,

i have a Problem, i will tested ralph3 but cannot installation.

1. sudo apt-get update && sudo apt-get install apt-transport-https
2.sudo apt-key adv --keyserver  hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61
3.sudo sh -c "echo 'deb https://dl.bintray.com/vi4m/ralph wheezy main' > /etc/apt/sources.list.d/vi4m_ralph.list"
4.sudo apt-get update

Error:
OK:1 http://de.archive.ubuntu.com/ubuntu xenial InRelease
OK:2 http://security.ubuntu.com/ubuntu xenial-security InRelease            
OK:3 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease           
OK:4 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
Ign:5 https://dl.bintray.com/vi4m/ralph wheezy InRelease
Ign:6 https://dl.bintray.com/vi4m/ralph wheezy Release
Ign:7 https://dl.bintray.com/vi4m/ralph wheezy/main amd64 Packages
Ign:8 https://dl.bintray.com/vi4m/ralph wheezy/main i386 Packages
Ign:9 https://dl.bintray.com/vi4m/ralph wheezy/main all Packages
Ign:10 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de_DE
Ign:11 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de
Ign:12 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-en
Ign:7 https://dl.bintray.com/vi4m/ralph wheezy/main amd64 Packages
Ign:8 https://dl.bintray.com/vi4m/ralph wheezy/main i386 Packages
Ign:9 https://dl.bintray.com/vi4m/ralph wheezy/main all Packages
Ign:10 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de_DE
Ign:11 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de
Ign:12 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-en
Ign:7 https://dl.bintray.com/vi4m/ralph wheezy/main amd64 Packages
Ign:8 https://dl.bintray.com/vi4m/ralph wheezy/main i386 Packages
Ign:9 https://dl.bintray.com/vi4m/ralph wheezy/main all Packages
Ign:10 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de_DE
Ign:11 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de
Ign:12 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-en
Ign:7 https://dl.bintray.com/vi4m/ralph wheezy/main amd64 Packages
Ign:8 https://dl.bintray.com/vi4m/ralph wheezy/main i386 Packages
Ign:9 https://dl.bintray.com/vi4m/ralph wheezy/main all Packages
Ign:10 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de_DE
Ign:11 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de
Ign:12 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-en
Ign:7 https://dl.bintray.com/vi4m/ralph wheezy/main amd64 Packages
Ign:8 https://dl.bintray.com/vi4m/ralph wheezy/main i386 Packages
Ign:9 https://dl.bintray.com/vi4m/ralph wheezy/main all Packages
Ign:10 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de_DE
Ign:11 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de
Ign:12 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-en
Fehl:7 https://dl.bintray.com/vi4m/ralph wheezy/main amd64 Packages
  404  Not Found
Ign:8 https://dl.bintray.com/vi4m/ralph wheezy/main i386 Packages
Ign:9 https://dl.bintray.com/vi4m/ralph wheezy/main all Packages
Ign:10 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de_DE
Ign:11 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-de
Ign:12 https://dl.bintray.com/vi4m/ralph wheezy/main Translation-en
Paketlisten werden gelesen... Fertig
W: The repository 'https://dl.bintray.com/vi4m/ralph wheezy Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://dl.bintray.com/vi4m/ralph/dists/wheezy/main/binary-amd64/Packages  404  Not Found
E: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

What is wrong? 

Thanks

**Comment by ghost** [comment]
What OS are you using?
Could you run in shell `lsb_release -a`?

**Comment by ghost** [comment]
I think recommended version of Ubuntu for Ralph is: 14.04 aka `trusty`

**Comment by spinnnor** [comment]
Oh  sorry :)

Latest Ubuntu16 version x86_64... I installed a new server and i hope thats work now.

Update: The same problem

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

x86_64

**Comment by spinnnor** [comment]
ahhh ok, i try the ubuntu 14.04.5 version

**Comment by Skvortsovg** [comment]
I have the same problem in ubuntu 14.04.5

**Comment by spinnnor** [comment]
Yes, me to... 

W: Failed to fetch https://dl.bintray.com/vi4m/ralph/dists/wheezy/main/binary-amd64/Packages  HttpError403

W: Failed to fetch https://dl.bintray.com/vi4m/ralph/dists/wheezy/main/binary-i386/Packages  HttpError403

E: Some index files failed to download. They have been ignored, or old ones used instead.
sebastian@DEV02:~$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=128 time=16.6 ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=128 time=17.4 ms
^C

**Comment by spinnnor** [comment]
no solution?

**Comment by Skvortsovg** [comment]
I tried to use manual installation as it is written in readme file, but this way also failed:(

**Comment by mkurek** [comment]
I'll tackle this problem today

**Comment by spinnnor** [comment]
Is there already a solution? :)

**Comment by vi4m** [comment]
Still working on it.

**Comment by vi4m** [comment]
Problem fixed. You can update & install it the sam way as before.

**Comment by wardag21** [comment]
still the same issue

**Comment by vi4m** [comment]
I checked yesterday, it works when: 

- you use amd64 architecture, i386 is not supported
- ubuntu 14.04 only for now.
