### ISSUE TITLE
Rack Orientation is not working

### ISSUE THREAD

**Issue by mywatch** [allegro/ralph#2930]
Hi Ralph Team,

For DC Visualization, rack orientation does not change once user change it at Racks Orientation settings to bottom to top and vice-versa. Rack numbering always start with descending order.

![image](https://cloud.githubusercontent.com/assets/14229096/21794244/04a12c6e-d73c-11e6-9d42-fcc3b53ab3df.png)

**Comment by ar4s** [comment]
Did you restart main server procesem like gunicorn?

**Comment by mywatch** [comment]
Yes, I restarted server too, no change, still same issue.

**Comment by mywatch** [comment]
I am not sure about main server process like gunicorn and how to run it.
I just changed orientation from top to bottom and restarted server $ralph runserver .0.0.0.8000.
And received no difference in orientation.

**Comment by mywatch** [comment]
Hi Ralph Team,
I miss understood rack orientation functionality. I checked rack orientation worked fine with (top, bottom, left and right) given options. 

But, there is a different requirement from us, could you please let us know, is it possible to reverse the slot ordering from descending to ascending in a rack.

Right now, default ordering is descending. Also is it possible to have both (ascending and descending) options available together in ralph. 

It would be a great help if you can point me files where actual code implementation is given.

**Comment by blocksmither** [comment]
There was a setting added a few months ago called RACK_LISTING_NUMBERING_TOP_TO_BOTTOM in settings/base.py that applies to all racks in the ralph instance. However, some companies deal with multiple datacenters and clients and the standards may differ.


I will submit a pull request next week. You can change the orientation per rack, so some racks can be in one order and some can be in another.   I will keep the RACK_LISTING_NUMBERING_TOP_TO_BOTTOM and use it as a default value for creating new racks and for values to fill in database migration.

**Comment by mkurek** [comment]
That would be great @thescriptbender!
