### ISSUE TITLE
Region option missing from Groups List

### ISSUE THREAD

**Issue by mywatch** [allegro/ralph#2931]
Dear Ralph team,

Under (Settings  --> Groups list), option to select Regions is missing. But same is available under (Settings --> Users list). Is there any specific reason to not provide regions in groups-list (or) its a bug. 

Your quick response will be appreciated. 

![image](https://cloud.githubusercontent.com/assets/14229096/21800432/fcbefe48-d760-11e6-9b3d-bdc49b4b7f24.png)

**Comment by mkurek** [comment]
Currently region is assigned only to user - but I think we could add this field for group too - then regions for user will be sum of its direct regions and it's groups regions.

**Comment by mywatch** [comment]
Thank you so much for you quick response. 

Actually we required groups-list to have regions option, so that our ldap sync all user with right regions, instead of doing one-by-one mapping under users-list.

**Comment by anchiru** [comment]
hi there. there any news about an ability to map LDAP group to the specific or some default region?

**Comment by romcheg** [comment]
No changes have been done about this yet. I'm going to close the issue for now since we are cleaning up the issue board for the project. Any contributions regarding this are welcome. Otherwise, please create a topic at  Ralph forum: https://ralph.discourse.group
