### ISSUE TITLE
Report tree node uniqueness

### ISSUE THREAD

**Issue by exebit** [allegro/ralph#2934]
Hello,
I see a mistake in **Manufactured - category - model** report. I have 1 Avaya Telecom and some Fortinet telecom devices. But report is the following:
![image](https://cloud.githubusercontent.com/assets/14807529/21889005/d74627fe-d8d7-11e6-8b2b-38cf4da50769.png)
All telecom devices are linked to Avaya.

Fortinet node is empty:
![image](https://cloud.githubusercontent.com/assets/14807529/21889134/786d0ada-d8d8-11e6-9fe6-cf248644738c.png)

I expect that report will have several same categories in appropriate vendor nodes.

P.S. I tried to unset **unique** attribute for category node, but method ReportContainer.add() doesn't have branch uniqueness criterion at ./lib/python3.4/site-packages/ralph/reports/base.py:60

**Comment by manioo8** [comment]
Same issue here, the report displays assets with incorrect amounts. 

we have a monitor model called U2415 added, with manufacturer selected as DELL. We also have another manufacturer than dell, called BELINEA. After adding a lot of assets with model selected as U2415 (which automatically assigns it's manufacturer to dell) and around 1-2 assets from belinea manufacturer, and going to Reports -> manufactory category model, we get a list of manufacturers with the amount of assets assigned to them. BELINEA, despite having only 1-2 assets, shows 109, and after clicking the name, displays a sub-menu in which all the different models are listed that are supposedly from belinea. The models displayed are actually from dell, but ralph incorrectly assigns them to another manufacturer in the report.

checking the database from cli with mysql commands also shows that there is only one model from belinea and that there are only two assets assigned to that model. I checked assets_asset, assets_assetmodel and assets_manufacturer tables. There's a manufacturer with a certain id, only one model with that manufacturer's id and only 2 assets with that model's id
So it seems that there's something wrong with the part of ralph that generates the manufactured category model list, as the database records seem to be correct
