### ISSUE TITLE
[feature request] Auto generate barcode

### ISSUE THREAD

**Issue by rnldnkp** [allegro/ralph#2941]
It would be great if Ralph could auto-generate a barcode (UID) for an object. You should be able to set a prefix and length of the value.

For example VM or PC makes: VM12345 or PC12345

Or did I mis something and is this already possible?

**Comment by vi4m** [comment]
The feature is not present yet, we autogenerate hostname's numbers only.

**Comment by rnldnkp** [comment]
Hi vi4m, thanks for your comment.

Ok, i'll look in to that. Maybe I misplaced 'barcode' and can we accomplish our goal with the hostname field. At the end, most of the assets are not physical objects. Like VM's or Software.

I have managed to get some hostnames popup in the demo. It seems to be attached to a transition. But I can't add transitions, and I cannot define what the hostname should look like. 

Or, it's just me and I can't find it ;)

To be sure I'm setting up a private demo, maybe that way I can manage to do more with this (as an admin user for example?)

**Comment by rnldnkp** [comment]
The hostname is only generated under Back Office (?) and I cannot tell how it's configured (lenghth etc.)

**Comment by rnldnkp** [comment]
@vi4m I was wondering, did the hacktoberfest work out? I'm still looking for a way to autogenerate a barcode and force it being unique (or just grey it out, using the auto generated one)

**Comment by romcheg** [comment]
We are not planning to implement this feature in the observable future. Any contributions, however, are welcome.
