### ISSUE TITLE
barcode and SN missing 'asterisk'/required indication

### ISSUE THREAD

**Issue by rnldnkp** [allegro/ralph#2942]
When adding an asset in the demo, some field shown an asterisk telling me it is required. But both Barcode and SN do not show an asterisk but do give an error when you save without them.

I guess those should have an asterisk as well, or they should be red when empty, not after I hit 'save'.

**Comment by vi4m** [comment]
That's true. It is this way because it depends which one you will use (one of: barcode or sn is required)

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
