### ISSUE TITLE
Built-in rack accessories modification

### ISSUE THREAD

**Issue by dizaar** [allegro/ralph#2955]
First, Great Thank for your work. I`d like to ask is there an idea of customizable built-in rack accessories modification?
Such as power socket. I`d like to have an option to point how many connections can be applied to one power socket, what equipment is connected to what power jack.
And what about possibility to graph connections between equipment?

**Comment by vi4m** [comment]
Something like this is in our roadmap. We plan to add customfields function in a few places around the system, including accesories.

For now, we use description field to put some information as a workaround.

**Comment by vi4m** [comment]
<img width="335" alt="zrzut ekranu 2017-02-01 o 11 41 35" src="https://cloud.githubusercontent.com/assets/552398/22503792/a204498a-e873-11e6-939c-4b269023beb7.png">
<img width="254" alt="zrzut ekranu 2017-02-01 o 11 43 34" src="https://cloud.githubusercontent.com/assets/552398/22503813/bb0abb30-e873-11e6-9c51-5af12d0bf86d.png">

**Comment by vi4m** [comment]
it's displayed on top of accesory then <img width="392" alt="zrzut ekranu 2017-02-01 o 11 44 22" src="https://cloud.githubusercontent.com/assets/552398/22503827/cd98bce8-e873-11e6-92bc-e058a3c69e3a.png">

**Comment by w5t3f** [comment]
@vi4m Maby something like "parent" in hardware. Asset model "cross panel" with given quantity of "parent" fields (12,24,48 according to panel type) named, e.g. port1, port2, port3.... A user would fill the "parent" field with the connected device/port.

**Comment by ar4s** [comment]
related with #2957

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
