### ISSUE TITLE
[Feature Request] Display custom fields along with other machine information in DC Visualization

### ISSUE THREAD

**Issue by zuniga7** [allegro/ralph#2957]
I would like to be able to display custom fields in the small panel that lists the service catalog, hostname, model, barcode, sn, etc when I am looking at a particular machine in the DC visualization.

**Comment by w5t3f** [comment]
Or some menu to choose what information to show on device visualisation.

**Comment by vollkommenIrrelevant** [comment]
Furthermore, there is no way to define these fields as mandatory for certain asset classes.

**Comment by mkurek** [comment]
Things to do:
1. expose custom fields in visualisation api - add it to visualisation serializers: https://github.com/allegro/ralph/blob/ng/src/ralph/dc_view/serializers/models_serializer.py (use https://github.com/allegro/ralph/blob/ng/src/ralph/lib/custom_fields/api/serializers.py#L113 )
2. Show them in UI:
 - add next row with custom fields exposed in visualisation api here -> https://github.com/allegro/ralph/blob/f236b607cd80d5d542e3ba5b19cec26c98042479/src/ralph/dc_view/static/partials/server_room/server_room.detail.rack.html#L78

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please start a topic at Ralph forum: https://ralph.discourse.group
