### ISSUE TITLE
[Feature Request] Format Validation for Data Center Asset Fields

### ISSUE THREAD

**Issue by zuniga7** [allegro/ralph#2958]
I would like to be able to specify validation formats for the barcode, serial number, and inventory number fields so that they are in the right format when saving or creating a new data center asset.

**Comment by mkurek** [comment]
This validator should be optional (to keep backward compatibility) and should be configurable in Ralph (Django) settings. Then it should be injected into barcode/sn/niw field in model (https://github.com/allegro/ralph/blob/ng/src/ralph/assets/models/assets.py#L368-L389 ) as a validator (https://docs.djangoproject.com/en/1.8/ref/validators/)

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please start a topic at  Ralph forum: https://ralph.discourse.group
