### ISSUE TITLE
Zabbix integration

### ISSUE THREAD

**Issue by defrancesco** [allegro/ralph#2960]
using the zabbix integration procedure (by command > ralph cmdb_integration --cmdb_zabbix) the procedure import hosts and trigger but  doesen't correlate the trigger and changes with CIs .

Again importing hosts give an error  hostid  cannot be null, to execute the procedure I need to remove not null constraint on related table

Can you fix please
Contact me for every clarification
Thanks

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
