### ISSUE TITLE
No Uniqueness checked while creating "server_rooms" and "categories"

### ISSUE THREAD

**Issue by cejojohn** [allegro/ralph#2963]
I tried with both APIs and GUI, the uniqueness is maintained with "name" of all other objects but not in case of "server_rooms" and asset "categories". We can create "server_rooms" and "categories" with the exact same details.
But rest everything inside Ralph does not allow the "name" to be same, so I thought this could be a bug.

**Comment by vi4m** [comment]
@ar4s any ideas?

**Comment by mkurek** [comment]
@vi4m We don't have unique property for server room and category - and in my opinion we should create unique for server room on name together with data center (in other words: you could not create server rooms with the same name in one DC).

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
