### ISSUE TITLE
DC Visualization enhancements

### ISSUE THREAD

**Issue by zuniga7** [allegro/ralph#2988]
Hi, I've noticed a couple of things in the DC visualization view that I think can be improved.

- When you click on a rack, the page should scroll to the top so that we can see the rack. This is a problem  when you have to scroll down to click on a rack that is not at the top of the rack list or the visualization.
- The little panel that displays the row/column and the rack of where your mouse is pointing can get covered by some of the racks. Maybe it would be helpful to allow the user able to re-position this  panel to where ever they need to.
- When I put the page at full screen in a 1920x1080 monitor, I noticed that the front/back view are not side by side, but when i decrease or increase the width by a little bit, them become side by side

A couple of features to consider:
- I think it would great to make the DC visualization more interactive, like for example, having a zoom in/out button that will affect the datacenter only and not zoom in/out the rack list on the left. 

- I also noticed that the printing option in the browser does not do a good job if you want to print the Visualition so another feature request I have is being able to generate the DC visualization into a PDF (without the information panel) and allowing the user to choose if they want to have it with/without the rack list.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
