### ISSUE TITLE
[Question] Running this on docker with an existing MySQL server

### ISSUE THREAD

**Issue by DracoMilesX** [allegro/ralph#3013]
Recently came across this and found out their is a docker image for except it requires to use an docker MySQL server and creating MySQL volumes.

Is their any way to run this with an existing MySQL installation? That I am already hosting on my NAS?
By the looks of it their is no real setup through web interface if I read it correctly?

**Comment by vi4m** [comment]
Yes, just point to your mysql server by IP in the settings file

**Comment by DracoMilesX** [comment]
Ok thanks for the info will look into it.
