### ISSUE TITLE
what's version of the django-sidetree the ralph3 use?

### ISSUE THREAD

**Issue by Jungle93** [allegro/ralph#3031]
there is the problem ,it is hard for me to download django-sitetree from https://github.com/idlesign/django-sitetree.git@.... 
could i just modify the requirements file ?
but the new problem  arise ,which version of the django-sitetree the ralph3 use?
wait for a answer

**Comment by mkurek** [comment]
@Jungle93 checkout new sources of Ralph - we're not using sitetree pointed to single commit anymore.

**Comment by Jungle93** [comment]
as down load from  github ,is seem's there is a  warnning
Could not find a tag or branch 'a626559c39ff1e865cde3441c44f42864c648dfb', assuming commit.

**Comment by Jungle93** [comment]
@mkurek thanks ,i will check , it is nice for get a answer from the team number.thanks very much
