### ISSUE TITLE
Cannot add dchost, but option presented

### ISSUE THREAD

**Issue by vi4m** [allegro/ralph#3054]
Just after the installation, after the first login to Ralph, an option is presented on empty page of dchosts "Nothing to display. You can add first dc host". 

But you cannot add "generic" dchost, so we should hide this link in some way. 

![selection_012](https://cloud.githubusercontent.com/assets/552398/25708375/9b1f249e-30e6-11e7-9cb7-32eb69843d3d.png)

**Comment by mkurek** [comment]
Fixed in #3056
