### ISSUE TITLE
Cannot install latest on 14.04 fresh install

### ISSUE THREAD

**Issue by axemann** [allegro/ralph#3066]
Hi all,

I apologize in advance if this was addressed in a previous issue, but for the life of me I can't locate it if it was.

Here's the deal:  I'm trying to do a new install on a clean install of Ubuntu 14.04, and when following the Installation guide, it always returns the following when issuing 'sudo apt-get install ralph-core redis-server mysql-server':
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ralph-core : PreDepends: python (>= 3.4) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

The system appears to want to install python2.7.4, but that just won't do since ralph-core has to have 3.4 or higher (which 3.4.3 is installed).

Any thoughts on what to try next?

Thanks,

Ben

**Comment by vi4m** [comment]
Checking

**Comment by vi4m** [comment]
Fixed - please update to the latest version.
