### ISSUE TITLE
Make Ralph working with nginx

### ISSUE THREAD

**Issue by ziompaul** [allegro/ralph#3089]
Hi,

I would like to deploy Ralph 3 fulltime working.
Now I have it installed on VmWare, but it works only when I am logged in and set the _ralph runserver_ command. And unfortunately it is unusable for now.

Why cant't it be self fulltime working?
Why should I use nginx to run it  fulltime?

What steps should I to do run Ralph fulltime with nginx?

**Comment by mkurek** [comment]
@ziompaul try docker (http://ralph-ng.readthedocs.io/en/latest/installation/installation/#docker-installation-experimental) or [supervisord](http://supervisord.org/index.html) for running Ralph's server (you could check example of supervisor config for Ralph2 - https://github.com/allegro/ralph/blob/develop/contrib/supervisor/ralph_gunicorn.conf - it should be something similar)

**Comment by ziompaul** [comment]
OK, I went back to setup Ralph 3 with docker. I have allready installed **docker** and **docker-compose**. Further instruction is not clear for me...

Some major questions for the begining.

**1.** Where to _copy docker-compose.yml_ configuration file?

**2.** What needs to be changed in copy docker-compose.yml file?

**3.** Do I have to copy somewhere the rest of https://github.com/allegro/ralph/tree/ng/contrib directory?

Regards

**Comment by ziompaul** [comment]
Anyone can help with the Docker?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
