### ISSUE TITLE
Change DC Visualization Object Colors

### ISSUE THREAD

**Issue by Silencedpulse** [allegro/ralph#3101]
We have racks filled from top to bottom and it would be easier if we could assign a color to an object so that when we are looking in the DC view it would look clean and easier to identify objects.

**Comment by vi4m** [comment]
Colors sounds like a good idea. But we have  to think how to set it, because requiring manual color for each device could be inconvenient. Maybe color per Service could be enough?

Speaking about the orientation though, I assume you set this[1] property in order to reverse ordering? 

<img width="1303" alt="zrzut ekranu 2017-06-25 o 21 39 04" src="https://user-images.githubusercontent.com/552398/27519193-06521830-59ef-11e7-87dc-e4beac401f18.png">

**Comment by Silencedpulse** [comment]
I have indeed set the RU order top to bottom so our rack numbers start at the bottom.  But since we have hardware throughout the entire rack, in the DC View it looks like one large green rack so visually it would be nice to select the color of the object so that we could separate devices when viewing the DC.  I don't think setting a color to a service would work for us because we have 3 datacenters and each datacenter is assigned as a service and we own/manage all of the hardware.  If that is easier, then I could work around that and assign each device a different service.

**Comment by vi4m** [comment]
Can you post a screenshot how it looks like?

**Comment by vi4m** [comment]
Another idea is to define color for specific hardware category, such as switches for example with 'yellow' color, and rack servers with the blue one (defined somewhere in category settings) - please show your visualization screens to better understand it.

**Comment by Silencedpulse** [comment]
The problem with coloring hardware is that many of the devices in the rack are the same hardware.  I'll post a screenshot on Monday.  Since the default color is green, is it possible to be able to select a color instead of using the default?

**Comment by vi4m** [comment]
Technically speaking yes, we could also specify color for each device separately, leaving default color

**Comment by Silencedpulse** [comment]
That would be ideal.  So once you create your device there'd be an option to select a color.  I don't think many options would be needed just enough to differentiate the devices that are right next to each other.

**Comment by ruapotato** [comment]
I'm okay with colored services. Any updates. The green is killing me.

**Comment by romcheg** [comment]
atm we have no time to change this. Any contribution, however, will be reviewed and appreciated.
