### ISSUE TITLE
Rack holes

### ISSUE THREAD

**Issue by pae23** [allegro/ralph#3111]
Some gears heights are not integer rack unit : some switches are 1.5 RU and sometimes. Ralph accepts only integers for RU. To tricks, I create rack units per hole (RU * 3) but that's dirty and it break the display in dc_view (I open an other issue for it).

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
