### ISSUE TITLE
Filtering Api requests.

### ISSUE THREAD

**Issue by MrEsL** [allegro/ralph#3112]
Hello,

is it possible to filter out certain data fields in data-center-assets for example in the api request instead of receiving lots of fields which I do not care about.

For example I would like to receive all hardware devices - barcode,rack,service env,hostname.

**Comment by vi4m** [comment]
We use Django Rest Framework - i don't think it allows to do that. 

@mkurek any ideas ?

**Comment by ar4s** [comment]
Probably GraphQL (http://graphql.org/) is the answer :) @vi4m true, DRF is not enough flexible to do this.

**Comment by MrEsL** [comment]
Thanks for clarifying ;)
