### ISSUE TITLE
Read The Docs github link broken

### ISSUE THREAD

**Issue by yonelly** [allegro/ralph#3113]
https://github.com/allegro/ralph/blob/ng/home/docs/checkouts/readthedocs.org/user_builds/ralph-ng/checkouts/latest/docs/.md

Goes to 404 on github

**Comment by vi4m** [comment]
Ok, here's the proper link: http://ralph-ng.readthedocs.io

**Comment by vi4m** [comment]
Where does this documentation link come from?

**Comment by yonelly** [comment]
![screen shot 2017-07-03 at 11 01 08 am](https://user-images.githubusercontent.com/9511615/27803594-13bdacfa-5fdf-11e7-9eec-c41fceadf3b2.png)
