### ISSUE TITLE
API DELETE returns error 401 (unauthorized) if trailing slash is missing

### ISSUE THREAD

**Issue by klikr** [allegro/ralph#3119]
here's the called URL
```
URL:    https://ralph.my.domain/api/virtual-servers/392
Method: DELETE
```

here's whats being returned:

```
The remote server returned an error: (401) Unauthorized.
   Respns: {"detail":"Authentication credentials were not provided."}
```

**Comment by klikr** [comment]
Just to clarify: I logged in using the API token, all other methods (GET, POST, PATCH) are working fine.

**Comment by klikr** [comment]
See communincation on gitter: https://gitter.im/allegro/ralph?at=595e3a632723db8d5ee37f70

**Comment by klikr** [comment]
adding a trailing slash resolves the problem, but Roman asked me to open up this bug anyway, because the redirect in django might be broken.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
