### ISSUE TITLE
Multi langage

### ISSUE THREAD

**Issue by pireoulepou** [allegro/ralph#3122]
Permets user to select the langage which may be used in ralp user interface:
english, french, deutsch, spanish ...

**Comment by vi4m** [comment]
Let's do it 👍

**Comment by pireoulepou** [comment]
😊

**Comment by ar4s** [comment]
@pireoulepou please update your ralph's instance - from now you can change language at ``http://your.ralph.instance/user_profile``

**Comment by pireoulepou** [comment]
Thanks a lot !!!
