### ISSUE TITLE
Question: Ralph agent for other distros (SuSE, CentOS) and operating systems (Windows, macOS)?

### ISSUE THREAD

**Issue by fthommen** [allegro/ralph#3131]
I read on http://ralph-ng.readthedocs.io/en/latest/installation/installation/, that "We only support Ubuntu 14.04 Trusty distribution on the AMD64 platform."  That seems to be true even for the agent.  I wanted to give Ralph a try, but our environment is 95% openSuSE/CentOS.  Are there plans to support these distros for the agent, too (soon)?

What about Windows and macOS?  An inventory system w/o cross-distro/cross-os agent doesn't seem to make much sense to me ;-)

frank

**Comment by fthommen** [comment]
I have seen #3093, but this issue seems to relate to the server.  I'm only interested in the client/agent and an installation method which allows it to be deployed on 200 nodes.

**Comment by vi4m** [comment]
Agent for linux is here, and it should run on any linux system: https://github.com/allegro/ralph-cli

**Comment by fthommen** [comment]
Great.  However I can't find a reference to it in the documentation (http://ralph-ng.readthedocs.io/en/latest/installation/installation/).  Maybe a section about client-only installations could be added to it?

**Comment by vi4m** [comment]
Good idea!

**Comment by vi4m** [comment]
We used to have this here [see screen] on our docs, but I think we should include it under installation as well

<img width="316" alt="zrzut ekranu 2017-08-07 o 20 54 05" src="https://user-images.githubusercontent.com/552398/29041341-c76cd926-7bb2-11e7-986e-13bd8b4fcd48.png">

**Comment by fthommen** [comment]
Thanks, but I am still at a loss. I expected some kind of agent, which is locally installed and gathers asset data (software versions, hardware information) and periodically sends it to the Ralph server.  Instead, ralph-cli seems to be a tool to be run on the Ralph server and which connects to the client hosts through the management port (which is not possible at our site anyway) to scan only hardware information.

Either I got the whole concept wrong or I'd need some more documentation/guidance.

To be clear: We don't require or want automatic network discovery, just a local "information gatherer"

**Comment by vi4m** [comment]
You got this right - we don't ship "agent" which is run on hosts all the time. 
We use combination of: ralph-cli for hardware identification (when installing HW in the DC), and puppet as an agent for software/os discovery. We don't ship our puppet scripts because they are specific for our use cases. We left Raph open for external API client / agents.

**Comment by fthommen** [comment]
I see :-)

Re **Software**: That means if I want to inventorize the software on our hosts, then I'd have to write my own client using the Ralph API to feed the data into Ralph?  This would rule out Ralph for us, as we don't have the resources to do this.  Puppet wouldn't help either, as we use ansible, not puppet for our configuration management.

Re **Hardware**: ralph-cli seems to require management port access (and only ilo and idrac, but we have IBM/Lenovo iBMC).  Is there also a (prebuilt/out-of-the-box) way to let it SSH into the server and do the hardware discovery there or would I have to implement this myself, too?

**Comment by vi4m** [comment]
Yes, to have working discovery you will likely have to write API client, or use 3rd -party plugins, such as http://fusioninventory.org. I talked with the guys behind the fusioninventory project, and I see oportunity to make fusioninventory <-> ralph integration

**Comment by fthommen** [comment]
ok.  Thanks a lot for the explanations.  We will keep an eye on Ralph, as it is seems very promising.  I specially liked the modern layout and the built-in rack management.  However w/o a more or less "out-of-the-box" hard- and software inventory possibility (_not_ using ilo/idrac/BMC & Co.) it is not an option for us.  Fusioninventory seems be a good choice.  I have successfully used it together with GLPI in the past.
