### ISSUE TITLE
Module 'encodings' missing

### ISSUE THREAD

**Issue by fthommen** [allegro/ralph#3132]
After installing Ralph according to http://ralph-ng.readthedocs.io/en/latest/installation/installation/ on Debian 9.1, a call to `ralph` results in 

```
$ export DATABASE_NAME=ralph
$ export DATABASE_USER=someuser
$ export DATABASE_PASSWORD=somepassword
$ export DATABASE_HOST=127.0.0.1
$ export PATH=/opt/ralph/ralph-core/bin/:$PATH
$ export RALPH_DEBUG=1
$ ralph
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted
$ 
```

Setting `PYTHONHOME` to `/opt/ralph/ralph-core/lib` reduces the error to
```
$ export PYTHONHOME=/opt/ralph/ralph-core/lib
$ ralph
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted
$
```

Installed version of ralph-core is  3.0.0-snapshot-20170801-8220

**Comment by vi4m** [comment]
We haven't tested ralph on Debian 9.1 yet - thanks for bug report. I guess we should build separate packages from within native debian system, not ubuntu.

**Comment by fthommen** [comment]
The intrinsic question is: How can one fix this?  I cannot even start 'pip' or 'easy_install' to install this module, as they fail with the same error.

**Comment by vi4m** [comment]
I think you should uninstall this debian package, and try with: 

* manual installation, 
* or install using Docker
* or stick to supported distro run on Ubuntu / earlier Debian in VM

- until native support for debian 9.1 land. The problem is with completely different version (3.4) boundled from Ubuntu 14, and maybe other system libraries.

**Comment by fthommen** [comment]
OK, but I could not find the "encodings" module for separate installation.  And then most manual installations require a "python setup.py", which leads to a bootstrap problem, as Ralph's `python` per se refuses to run.  Docker is not an option either, as our virtualization platform doesn't support containers ( :-( ).  We'll - forcibly - live with Ubuntu for the time being.  However a Debian or - even better - RHEL/CentOS would fit much better into our environment.  I'l also willing to test installation procedures etc.

However: Wouldn't it be flexibler to let users create their own virtual environment and use this for Ralph? This would eliminate the dependency from hardcoded symlinks etc.

**Comment by vi4m** [comment]
If you want flexibility, just use "manual installation" as below - 

<img width="974" alt="zrzut ekranu 2017-08-10 o 10 52 51" src="https://user-images.githubusercontent.com/552398/29162577-26c697b4-7dba-11e7-87c5-f405e6a5ceb4.png">

**Comment by vi4m** [comment]
On clean system, you can just create virtualenv by yourself (virtualenv /opt/ralph-core), activate it (source /opt/ralph-core/bin/activate) and after git clone https://github.com/allegro/ralph.git, issue "make install" and other , as above in picture.

**Comment by fthommen** [comment]
Thanks a lot.  I will give it a try

**Comment by akurach** [comment]
same on 
```
user@ubuntu:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
user@ubuntu:~$
```

**Comment by z2z** [comment]
Having same issue on ubuntu 16.04.03 LTS, wanted to quickly setup and run.

@fthommen @vi4m 

Please  add guide how to install on clean system.

**Comment by sz-po** [comment]
Same here. With python 2.7 and Ubuntu 16.04, clean install.
```root@ralph:~# /opt/ralph/ralph-core/bin/ralph migrate
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
Aborted

**Comment by chuegel** [comment]
Can confirm

**Comment by romcheg** [comment]
Ralph package was re-done entirely. Please refer to the official documentation for more details. In case of any questions you can ask for help at the official gitter channel or to  start a topic at  Ralph forum: https://ralph.discourse.group
