### ISSUE TITLE
REMOTE_USER Authentication

### ISSUE THREAD

**Issue by daviddpd** [allegro/ralph#3136]
I'm using a SSO system (I'm not yet attached to), but is pretty lightweight, and authenticates against LDAP.  I'm working towards this being the only sign-on screen, and even though user/password could be achieved via the Ralph login screen ... the ideal is to bypass it.
I'm using 

 - https://neon1.net/mod_auth_pubtkt/index.html

And with apache doing the reverse proxy, there is really no need to auth the token in Django/Ralph, because the request will never get there otherwise.

Django auth supports the REMOTE_USER without additional modules, and this seems ideal and the lightest weight.  

 - https://docs.djangoproject.com/en/1.8/howto/auth-remote-user/ 

I have this all working, however, Ralph is not reading REMOTE_USER and bypassing authentication.   I figure there is a customization here, that for some reason adding this addition middleware isn't working.  I've look around, but haven't found the area to adjust or patch. 

I wasn't able to get direct LDAP auth to work either, so there must be a little piece of glue config that is missing from the docs.

**Comment by mkurek** [comment]
Hi @daviddpd . If you want to setup ralph directly with ldap follow the guide here: http://ralph-ng.readthedocs.io/en/latest/installation/configuration/#ldap-authentication

> I have this all working, however, Ralph is not reading REMOTE_USER and bypassing authentication. I figure there is a customization here, that for some reason adding this addition middleware isn't working. I've look around, but haven't found the area to adjust or patch.

What customization do you mean? Could you point the place in our repo?

**Comment by daviddpd** [comment]
I honestly don't know, that is why I was asking - is there something overriding the bypass of the internal Ralph auth screen?  It wasn't working as a reverse proxy  with the development server ... then it dawned on me, that this option may only work in production mode, running via wsgi ... 

So I'm working on trying that now ...however, ap24-mod_wsgi4 in my ports was linked/compiled with python 2.7, not 3.4.   Got that compile going ... which wasn't straight forward, as required patches to the freebsd ports collection make files. 

Will update when I have tested with the updated mod_wsgi.

**Comment by mkurek** [comment]
Try first by removing `django.contrib.auth.middleware.SessionAuthenticationMiddleware` from `MIDDLEWARE_CLASSES` (or put `django.contrib.auth.middleware.RemoteUserMiddleware` directly in this place)

**Comment by daviddpd** [comment]
Thank you @mkurek  - that seems to have done the trick ... will post a blog/readme docs on the full setup with freebsd+apache+mod_wsgi-py34 for ralph in the next couple days.
