### ISSUE TITLE
Audit logging?

### ISSUE THREAD

**Issue by wrouesnel** [allegro/ralph#3137]
Is it possible to have Ralph record an audit log of *all* changes made to stored data by different parts of the system, be they Ralph processes (i.e. scanning) or users?

In our deployment we have a requirement to track the history of modifications, and need a way to do that. Could some like https://github.com/Atomidata/django-audit-log be integrated?

**Comment by vi4m** [comment]
Any object, which is recorded in ralph have history built-in, which is auditable. 
Furthermore, you can revert any object to the particulary history snapshot, at time. 
    
<img width="958" alt="zrzut ekranu 2017-08-09 o 09 54 44" src="https://user-images.githubusercontent.com/552398/29112758-1e6e6248-7cef-11e7-976c-81aac0a88965.png">


http://ralph-demo.allegro.tech/data_center/datacenterasset/12544/history/

**Comment by wrouesnel** [comment]
That would solve it entirely!
