### ISSUE TITLE
bower is deprecated

### ISSUE THREAD

**Issue by wrouesnel** [allegro/ralph#3138]
When building ralph-ng these days, bower is now throwing a deprecation warning that it is expected to be replaced by Yarn:
```
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467
```

**Comment by ar4s** [comment]
Thanks for reporting! We know about this problem with bower. Probably we going to install frontend' packages via ``npm``.

**Comment by ar4s** [comment]
1. `package.json` instead of `bower.json`
2. requires some changes in `gulpfile.js` (`bower_components` -> `.node_modules`)
3. yarn or npm

**Comment by cr0ssmind** [comment]
I vote to npm, but bower suggests using yarn.

**Comment by romcheg** [comment]
We will definitely do that at some point, but for now we don't have time to deal with that. Closing the issue to keep the board in the manageable state.
