### ISSUE TITLE
Location field for data center model

### ISSUE THREAD

**Issue by wrouesnel** [allegro/ralph#3142]
It would be useful to have a location field for the data centre type - specifically, a freeform address field (12 Fake St, Somecity Etc) and a Long/Latitude field (to facilitate visualization via Google Maps or something similar).

As it is, just the name of a data centre doesn't quite work since you generally want to use whatever the office colloquialism is for that location, but for presentation or onboarding it would be nice to store additional detail.

**Comment by mkurek** [comment]
This field should be added here: https://github.com/allegro/ralph/blob/ng/src/ralph/data_center/models/physical.py#L104

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
