### ISSUE TITLE
A child location info (rack etc.) inherited from a parent

### ISSUE THREAD

**Issue by w5t3f** [allegro/ralph#3151]
It will be very useful feature if setting a "parent" field in a part or device cause automatic inheritance the location info (rack etc.) from the parent.

**Comment by mkurek** [comment]
Validate first if this piece of code works: https://github.com/allegro/ralph/blob/ng/src/ralph/data_center/models/physical.py#L473-L486

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
