### ISSUE TITLE
Hardcoded "http://" breaks SSL reverse proxy - should be protocol agnostic

### ISSUE THREAD

**Issue by grzegor** [allegro/ralph#3152]
I'm hosting ralph in the cloud and I'm securing it with OAuth2 reverse proxy +SSL (https://github.com/bitly/oauth2_proxy). OAuth2 part works great, the SSL not so much. I have to do it over plain http because even though ralph seems to not mind the sudden port change, he insists on generating http:// links every time I try to update anything (even after visiting via https:// which kinda works - menu items itself are generated ok). IMO this should be protocol agnostic and not hardcoded.

Example:
I'm on https://ralph.domain/user_profile
I click "change language" (the form itself is generated ok: form action="/i18n/setlang/" method="post")
I get dropped to http://ralph.domain/i18/setlang (I blocked :80 on vps firewall so site can't be reached).

Chrome inspector shows that after clicking the button the request url was
 https://ralph.domain/i18n/setlang/ (good) but the response header "Location:" was http://ralph.domain/i18n/setlang/ 

I redacted all the addresses and tokens:

```
Request URL:https://ralph.domain/i18n/setlang/
Request Method:POST
Status Code:302 Found
Remote Address:##IP_REDACTED##:443
Referrer Policy:no-referrer-when-downgrade

**Response Headers**

HTTP/1.1 302 Found
Content-Language: en
Content-Type: text/html; charset=utf-8
Date: Wed, 30 Aug 2017 12:35:02 GMT
Location: http://ralph.domain/i18n/setlang/
Server: WSGIServer/0.2 CPython/3.4.3
Set-Cookie: sessionid=##REDACTED##
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN
Content-Length: 0

**Request Headers**

POST /i18n/setlang/ HTTP/1.1
Host: ralph.domain
Connection: keep-alive
Content-Length: 124
Cache-Control: max-age=0
Origin: https://ralph.domain
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Content-Type: application/x-www-form-urlencoded
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
DNT: 1
Referer: https://ralph.domain/user_profile
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,pl-PL;q=0.8,pl;q=0.6,en;q=0.4
Cookie: _oauth2_proxy=##REDACTED##; sessionid=##REDACTED##; csrftoken=##REDACTED##
Form Data
view parsed
csrfmiddlewaretoken=##REDACTED##&next=.&csrfmiddlewaretoken=##REDACTED##&language=en

```
**UPDATE:**
This workaround seems to do the job for me.
I installed apache+modrewrite and rewrite all traffic from http://ralph.domain to https://ralph.domain
This way I have ralph listening on 8000, proxy on 443 and apache on 80.
Proxy tunnels from 127.0.0.1:8000 and apache rewrites all from 80 to 443. Only 443 and 80 is exposed on the firewall.
Far from ideal because you have one more service running, one more port opened not to mention that requests on :80 can be sniffed and session cookie stolen (luckily not the oauth2 cookie so ralph one will be useless for anyone). But until the main problem is fixed this is still much better than "everything via http" approach.

**Comment by ar4s** [comment]
@grzegor please add ``SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')`` to your configuration and restart Ralph's instance and after that please give me feedback.

**Comment by grzegor** [comment]
@ar4s If by "your configuration" you mean 
`/opt/ralph/ralph-core/lib/python3.4/site-packages/django/conf/global_settings.py`
then sadly there is no change

**Comment by grzegor** [comment]
BTW my system:
```
# lsb_release -d    
Description:	Ubuntu 14.04.5 LTS
# apt-get install ralph-core=3.0.0-snapshot-20170827-8270
```
I'm using snapshot package from 3 days ago because latest 2 won't install.

**Comment by vi4m** [comment]
@ar4s why our latest builds failed?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
