### ISSUE TITLE
REST API doesn't allow virtual servers to specify a service environment as a hypervisor

### ISSUE THREAD

**Issue by fidotas** [allegro/ralph#3153]
Through the web interface it is possible to specify a service environment as the hypervisor for a virtual server asset. However when you attempt the same via the REST API it restricts you to using objects of type data-center-asset.

I fixed this by hand by importing the base object model into the head of src/ralph/virtual/api.py.

> from ralph.assets.models.base import BaseObject # DM - 2017-08-03

Then in the VirtualServerSaveSerializer class definition changed the primary key relationship constraint:

> class VirtualServerSaveSerializer(RalphAPISaveSerializer):
>     hypervisor = relations.PrimaryKeyRelatedField(
>         source='parent', queryset=BaseObject.objects, # DM - 2017-08-03 - Was DCHost.objects
>     )
> 
>    class Meta:
>        model = VirtualServer
>        exclude = ('parent',)

There's probably a better way of doing it.

**Comment by mkurek** [comment]
This is UI bug - you shouldn't assign service-env as parent to VM.

**Comment by Chez** [comment]
Fidotas,

Can I ask you how you made the api call. I have been trying to use curl to add a virtual server but keep getting errors: Here is my call in the dev environment curl -s -H "Authorization: Token mytoken" -X POST http://0.0.0.0:8000/api/virtual-servers/ -d '{"hostname": "VS-phishfinder-2", "service_env": 1, "status": 1, "type": 1, "hypervisor": 2}'
{"type":["This field is required."],"hypervisor":["This field is required."]}

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
