### ISSUE TITLE
No module named 'ralph.account'

### ISSUE THREAD

**Issue by ziompaul** [allegro/ralph#3157]
After success with importing users by LDAP, there is an error with importing Active Directory group with configuration:

```
from ralph.account.ldap import MappedGroupOfNamesType
AUTH_LDAP_GROUP_MAPPING = {
  'CN=Ralph3-Admins,OU=test,OU=Poland,DC=domain,DC=net': "superuser",
}
AUTH_LDAP_MIRROR_GROUPS = True
AUTH_LDAP_GROUP_TYPE = MappedGroupOfNamesType(name_attr="cn")
AUTH_LDAP_GROUP_SEARCH = LDAPSearch("DC=domain,DC=net",
    ldap.SCOPE_SUBTREE, '(objectClass=group)')
```

The LDAP error in SSH after ralph ldap_sync is:

```
from ralph.account.ldap import MappedGroupOfNamesType
ImportError: No module named 'ralph.account'
```

I see that I am not one and only who saw this error.
Ralph 3 is installed from Linux repository on Ubuntu 14.04.

Does this function import and maps AD grup to Ralph Group section only?
or it imports Users from AD group too and assign to newly imported Ralph group?

regards

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
