### ISSUE TITLE
Docker image size

### ISSUE THREAD

**Issue by pierlon** [allegro/ralph#3158]
The Docker image seems a bit bloated (latest tag '3.0.0-snapshot-20170901-8287' at 929 MB). After the ralph binary is installed, it doesn't seem the source files are needed afterward (with some minor exceptions). The main contribution to the image size is the 'node_modules' folder. The Dockerfile can also be optimized to further reduce the size.

The docker compose template seems outdated as well. (btw, what is the .octodocker.yml for?)

**Comment by grzegor** [comment]
It seems that it's already planned, see #1913 
Octodocker is some sort of product maintainers in-house proprietary merge decision aiding tool from what I understand (there is a presentation in polish by @mkurek and @szok, but the slides are in english so maybe you'll get a rough idea: https://www.youtube.com/watch?v=lUvmKObrIMY ).

**Comment by pierlon** [comment]
@grzegor thanks for the clarification.
