### ISSUE TITLE
addressing custom fields by name doesn't work

### ISSUE THREAD

**Issue by klikr** [allegro/ralph#3163]
URL:  https://ralph.my.domain/api/virtual-servers/93/customfields/my_lastack/
    Method: PATCH
    Body: {"value":  "someone@2017-09-12"}

returns

    The remote server returned an error: (404) Not Found
    Respns: {"detail":"Not found."}

Also:

    URL:    https://ralph.my.domain/api/virtual-servers/93/customfields/
    Method: PATCH
    Body:   {"custom_field":  "my_lastack", "value":  "someone@2017-09-12"}

returns

    The remote server returned an error: (405) Method Not Allowed.
    Respns: {"detail":"Method \"PATCH\" not allowed."}

**Comment by mkurek** [comment]
None of these would work and it's not a bug. 

In first approach you cannot identify custom field by name (attribute_name) - use id instead, ex. `https://ralph.my.domain/api/virtual-servers/93/customfields/1234/`. 

In second, PATCH is method used on specific object, not on list of objects - POST would be appropriate here.

**Comment by klikr** [comment]
OK, so docs are probably not OK
https://ralph-ng.readthedocs.io/en/latest/user/custom_fields/#changing-custom-fields
says 

> You could use custom field ID or attribute name to point it in API.

**Comment by vi4m** [comment]
Aren't we incosistent in this case? We return customfield "name" when read, but expect customfield `id` when writting to it?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
