### ISSUE TITLE
how to translate ?

### ISSUE THREAD

**Issue by milestone702** [allegro/ralph#3182]
I'm a new user in China, My teamworker don't not familiar with English ,I want to translate this project ,but I don't know how to translate , please tell me, thank you all

**Comment by vi4m** [comment]
Join transifex.com - then  find Ralph project. Find "NG" branch for translation. 
![zrzut ekranu 2017-10-20 o 14 44 23](https://user-images.githubusercontent.com/552398/31821475-89734fba-b5a5-11e7-8fd9-8c78fd8da270.png)
