### ISSUE TITLE
Feature: Aggregate fields per Rack

### ISSUE THREAD

**Issue by Phhere** [allegro/ralph#3190]
Hello,
we are using Ralph for some Rack planing and it would be quiet helpful to be able to aggregate fields and custom fields of all devices in a rack.
It would be nice to see this in DC View, to see how much power or network ports are required.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
