### ISSUE TITLE
Package for Debian 9

### ISSUE THREAD

**Issue by Phhere** [allegro/ralph#3191]
Hello,
it would be great to have packages for Debain 9 and not just wheezy and jessie.

**Comment by Freeaqingme** [comment]
I second this. Was first trying to do an install on Ubuntu Bionic, with little success. Then I figured I could try to make my own package in a Vagrant box, but that failed to build as well. Ended up (bordering on going back to Racktables) installing Debian 8; having to make a lot of exceptions in our Puppet setup (:disappointed: ).

Also, I noticed it seems the packages are over a year old. Is a pity that for such an awesome project, there's these loops you need to go through before things start to work.

**Comment by xsgb** [comment]
Here's my modifications that allowed me to build ralph-ng on Stretch. https://github.com/allegro/ralph/pull/3340

**Comment by romcheg** [comment]
The debian package was re-done dramatically. Could you please check it out? https://ralph-ng.readthedocs.io/en/stable/installation/installation/
