### ISSUE TITLE
Remove node-sass from dependencies

### ISSUE THREAD

**Issue by ar4s** [allegro/ralph#3195]
node-sass is a problematic package for example there is an error (during build travis and after update trusty image):

```
Error: Missing binding /home/travis/build/allegro/ralph/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x
Found bindings for the following environments:
  - Linux 64-bit with Node.js 7.x
```

Solution: django-compressor with libsass

**Comment by Skeen** [comment]
During the docker build described in the docs (the experimental one), it fails with:
```
> node-sass@4.9.4 install /opt/ralph/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.4/linux-x64-67_binding.node": 

HTTP error 404 Not Found
```
This is not just a network error, the project does not list such a release: https://github.com/sass/node-sass/releases/

The closest one is `linux-x64-64_binding.node`

**Comment by romcheg** [comment]
Docker containers are being published to dockerhub now and don't require building:
 - https://hub.docker.com/r/allegro/ralph
 - https://hub.docker.com/r/allegro/ralph-static-nginx
