### ISSUE TITLE
Feature Request: Allow more/custom imagery for Rack Accessories

### ISSUE THREAD

**Issue by Chewie9999** [allegro/ralph#3210]
At the moment, there are only basic images for Rack Accessories.
Either a number of square ports (depending on browser width) or a stippled effect for cable management.
It would be good if other images were available, or as new Rack Accessories are able to be created by the user, a way of uploading images for use so they give a more representative view.
Examples I would like to see:
- PDUs (eg, UK-sockets, C13/14 connectors, Schuko sockets)
Specific numbers of ports, eg 24, 48, 12 etc for the following:
- RJ45
- Fibre
- Coax
- Incoming fibre Tray

Once a way of adding custom images is chosen, I am happy to provide/draw imagery.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
