### ISSUE TITLE
Table 'ralph_ng.transitions_transition' doesn't exist

### ISSUE THREAD

**Issue by lowang-bh** [allegro/ralph#3214]
I  met the error" default: django.db.utils.ProgrammingError: (1146, "Table 'ralph_ng.transitions_transition' doesn't exist") ". I think it is because there are no such tables when newly install ralph3 develop environment but ralph3 try to migrate them(from ralph2).

**Comment by rcsheets** [comment]
#3216 seems to be a duplicate of this issue, but this issue has less information. I suggest closing this issue.

**Comment by lowang-bh** [comment]
same with#3216,close it
