### ISSUE TITLE
no write access to /home/ubuntu when vm_user = "ubuntu" in Vagrantfile

### ISSUE THREAD

**Issue by lowang-bh** [allegro/ralph#3217]
vm_user = "ubuntu"  -->
vm_user = "vagrant"
If vm_user is "ubuntu", then VM_USER=${VM_USER:-ubuntu} will be ubuntu, but the login user is vagrant actually when setup the develop environment. This will cause no write access to /home/ubuntu with login user of vagrant. Change it to "vagrant" it recover from error.

**Comment by rcsheets** [comment]
This appears to be a duplicate of #3215

**Comment by lowang-bh** [comment]
same as #32145, close it.
