### ISSUE TITLE
Support for CAS

### ISSUE THREAD

**Issue by ShyamalaViswanathan** [allegro/ralph#3223]
Is there any support for CAS, or CAS with mod_auth_cas

**Comment by ar4s** [comment]
Ralph doesn't support CAS itself. But you can try some app for Django e.g. https://github.com/mingchen/django-cas-ng and add to ``settings.py``. In general Ralph is normal Django project.

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
