### ISSUE TITLE
ralph/virtual/admin.py in get_parent, line 168

### ISSUE THREAD

**Issue by ghost** [allegro/ralph#3236]
when we go to this url in ralph3 /virtual/virtualserver/ and create an virtual server.
and then we go to the listing "again to /virtual/virtualserver/" we got above error.

and this in de trace-back. i think this is a bug because we can simulate this with a fresh install.
see the trace-back below.
----------------------------------------

Request Method: | GET
-- | --
http://192.168.50.181:8000/virtual/virtualserver/
1.8.18
AttributeError
'ServiceEnvironment' object has no attribute 'hostname'
/opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/virtual/admin.py in get_parent, line 168
/opt/ralph/ralph-core/bin/python
3.4.3
['/opt/ralph/ralph-core/bin',  '/opt/ralph/ralph-core/lib/python3.4',  '/opt/ralph/ralph-core/lib/python3.4/plat-x86_64-linux-gnu',  '/opt/ralph/ralph-core/lib/python3.4/lib-dynload',  '/usr/lib/python3.4',  '/usr/lib/python3.4/plat-x86_64-linux-gnu',  '/opt/ralph/ralph-core/lib/python3.4/site-packages',  '/opt/ralph/ralph-core/lib/python3.4/site-packages/odf',  '/opt/ralph/ralph-core/lib/python3.4/site-packages/odf',  '/opt/ralph/ralph-core/lib/python3.4/site-packages/odf',  '/opt/ralph/ralph-core/lib/python3.4/site-packages/odf',  '/opt/ralph/ralph-core/lib/python3.4/site-packages/odf',  '/opt/ralph/ralph-core/lib/python3.4/site-packages/odf',  '/opt/ralph/ralph-core/lib/python3.4/site-packages/odf']
Thu, 22 Feb 2018 11:02:23 +0100

**Comment by Chez** [comment]
I have also gotten the same error after adding a virtual server and then clicking virtual servers from the Data center Menu. Is this a recognised bug or a new bug?

**Comment by Thathwamasi** [comment]
Not sure as this is a proper solution:
When you try to change the below line in python this resolved the issue
on /opt/ralph/ralph-core/lib/python3.4/site-packages/ralph/virtual/admin.py in get_parent, line 168


From :
 return '<a href="{}">{}</a>'.format(
            obj.parent.get_absolute_url(), obj.parent.hostname

TO:
 return '<a href="{}">{}</a>'.format(
            obj.parent.get_absolute_url(), obj.hostname

**Comment by Chez** [comment]
That is a simple solution, however, the Ralph team need to check this out. I'm assuming they did testing before deployment and with that in mind, one would consider that all parents without a hostname cannot be assigned in this particular case.

**Comment by vi4m** [comment]
This issue is fixed. Closing.
