### ISSUE TITLE
Do not show some racks as empty in de visualization

### ISSUE THREAD

**Issue by ErikSmedinga** [allegro/ralph#3243]
We have a lot of racks in our data center that are rented to clients. At the moment I can either add them to Ralph so that the maps is correct. However all the racks show up as empty and its hard to see if we still have an empty rack available.
I wish there was a field in the rack 'inactive' so the rack will show up in the visualization, but it will not show empty positions. Also the rack space does not add to the total rack space. 
![inactive](https://user-images.githubusercontent.com/36470275/37204034-05263e8a-2390-11e8-8bd9-fe809216f491.jpg)

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
