### ISSUE TITLE
#3240 breaks `ralph migrate`

### ISSUE THREAD

**Issue by rcsheets** [allegro/ralph#3244]
Django's `prepare_sql_script` function requires `sqlparse`, which was  removed in #3240.

There is an ability to fall back to some legacy code in Django 1.8, but that is removed in Django 1.9, so we should probably re-introduce `sqlparse` somewhere in the requirements.

**Comment by ar4s** [comment]
I will create a pull request to fix it. I'm sorry for that :(

NOTE: https://github.com/django/django/blob/1.8.19/django/db/backends/base/operations.py#L268-L284

**Comment by rcsheets** [comment]
Confirmed fixed. Thanks.
