### ISSUE TITLE
Unable to view details of data center assets without change permissions

### ISSUE THREAD

**Issue by ErikSmedinga** [allegro/ralph#3247]
![details](https://user-images.githubusercontent.com/36470275/37392562-c22f0b38-276e-11e8-8981-5e07342d6674.jpg)
At the moment there is no way to allow a user to view data center assets details without giving them at least change permissions. It would be nice that basic users could only view this.

**Comment by ar4s** [comment]
Change permission for this view is strongly related with internal Django's permissions mechanism. Please check ``Can change data center asset``, all ``Can view * field`` and uncheck ``Can [delete|change] * field``
<img width="483" alt="screenshot 2018-03-14 10 49 33" src="https://user-images.githubusercontent.com/351535/37395318-4671a840-2776-11e8-9de7-2e47d8cb3d6a.png">

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
