### ISSUE TITLE
Adding Virtual Server with Hypervisor with ServiceEnv

### ISSUE THREAD

**Issue by Chez** [allegro/ralph#3259]
As Above, when you add a virtual server with a Hypervisor set as a Service Environment:

    File "/home/vagrant/ralph/src/ralph/virtual/admin.py", line 156, in get_parent

    obj.parent.get_absolute_url(), obj.parent.hostname

    AttributeError: 'ServiceEnvironment' object has no attribute 'hostname'

[console ready]
>>> obj.parent.__dict__
{'modified': datetime.datetime(2018, 4, 24, 8, 52, 37, 972512), 'content_type_id': 26, 'service_env_id': None, 'parent_id': None, '_state': <django.db.models.base.ModelState object at 0x7f8eef976e80>, 'configuration_path_id': None, 'remarks': '', 'id': 1, 'environment_id': 1, 'baseobject_ptr_id': 1, 'created': datetime.datetime(2018, 4, 24, 8, 52, 37, 972479), 'service_id': 1  }
>>> 

If adding a Service Environment to a Hypervisor, then why are they listed as options as they do not have hostnames.

**Comment by vi4m** [comment]
Which version of ralph is it?

**Comment by Chez** [comment]
Ralph 3

**Comment by vi4m** [comment]
Debian package? what does `dpkg -l "*ralph*"` show?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
