### ISSUE TITLE
can this be run on a windows environment

### ISSUE THREAD

**Issue by JunkyardCat** [allegro/ralph#3265]
the only os i have currently is windows 7 and raspbian is there a way to install ralph on these system?

**Comment by fajfer** [comment]
Raspbian is basically Debian ARM tailored for RPi. You could simply try installing it there since Debian is supported and recommended

**Comment by vi4m** [comment]
We focus on debian/ubuntu - try out if it works for you, please. @JunkyardCat

**Comment by vi4m** [comment]
If you want windows - just use virtualbox / docker and install deb package inside.
