### ISSUE TITLE
Don't hardcode the default country of a new user

### ISSUE THREAD

**Issue by djagoo** [allegro/ralph#3267]
The default value of a new users country should be changeable or use country of the logged in user as default value.

https://github.com/allegro/ralph/blob/c9f790e63d5a7536dcd5b5b9940aac397ebf09f0/src/ralph/accounts/models.py#L35

**Comment by vi4m** [comment]
Thanks for reporting this! I think we have to replace it with dynamic closure fetching current user region's.

**Comment by vi4m** [comment]
@romcheg is this already fixed?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
