### ISSUE TITLE
Advanced networking and cable management  functions.

### ISSUE THREAD

**Issue by loulasedna** [allegro/ralph#3270]
Hello, 

I'm currently testing ralph for my company and this is a good product,
But, I think there are missing things in it.

For advanced networking : 
- VRF  : for overlapping IP (same IP for multiple systems) 
- VLANs : to segment network 
- VXLAN :  because vxlan is currently use in DC.
- Maybe advanced function for allocation IP (like allocation in specific mask in a subnet, like in PHPIPAM) 

For cable management: 
- Connexion : information about begining and endind cable : device and patch panel an type (optical fiber, ethernet cable) 
- Information about power cable (type, begining-ending) 
...

**Comment by vi4m** [comment]
Unfortunately we don't have these functions yet, but we will happily accept/merge these features if somebody want to contribute(to write code for it). It will make Ralph even better.

If these are modules you are particullary interested in, you can buy fulltime development on this feature(customized for you) via 3rd party contributors, such as @xliiv (long-time contributor)

**Comment by ghost** [comment]
Unfortunately Im quite busy recently so I can't contribute/help/anything :/

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
