### ISSUE TITLE
Password fails on install if contains "$" symbol

### ISSUE THREAD

**Issue by andynz2017** [allegro/ralph#3273]
If DATABASE_PASSWORD environment variable contains "$" character, DB permission error thrown.

If you take the same password with $ and connect via terminal, connection succeeds as expected.

Printing the settings dictionary containing the environment variables which is passed through to MYSQL connection modules shows that the $ symbol and the character after the $ symbol in the password string is removed and not present even though it exists in environment variable.

An example password which you can reproduce with would be DATABASE_PASSWORD=blah$2!!123!

**Comment by ar4s** [comment]
You must escape ``$`` or wrap the value with ``'`` e.g. ``DATABASE_PASSWORD=blah\$2!!123!`` or ``DATABASE_PASSWORD='blah$2!!123!'``

**Comment by andynz2017** [comment]
Thanks. Always the simple things.
