### ISSUE TITLE
Autodiscovery

### ISSUE THREAD

**Issue by AndreCape** [allegro/ralph#3285]
Does anybody here have a more detailed manual on how to setup Autodiscovery please?

I had a look the docs below and tried to follow the steps but it seems to be from an earlier release.
http://ralph.readthedocs.io/en/latest/scan.html

Thank you.

**Comment by vi4m** [comment]
Provided link was from obsolete Ralph version (I disabled this old documentation to not make false assumptions about software options). 

I'm sorry, but we don't support autodiscovery anymore.  Instead, simple scripts, or API is needed to plug Ralph in existing installations. For more information read:

http://ralph-cli.readthedocs.io (CLI)
https://ralph-ng.readthedocs.io/en/latest/user/api/ (API)
