### ISSUE TITLE
docker-compose uses outdated syntax and features

### ISSUE THREAD

**Issue by larsks** [allegro/ralph#3288]
`contrib/docker-compose.yml.tmpl` uses outdated syntax and features (in particular the `links` keyword).  The file should be updated to use modern compose syntax and to rely on Docker-managed DNS rather than links.

**Comment by vi4m** [comment]
Can you give a shot with Pull Request for that? :)

**Comment by romcheg** [comment]
Docker packaging was re-done entirely.
