### ISSUE TITLE
Dashboard info boxes ignore associated regions

### ISSUE THREAD

**Issue by juniorfoo** [allegro/ralph#3300]
Info box on front page shows X back office assets and Y supports. When I click on either of them, the resulting list is 0 because my user does not have permissions to any regions.

**Comment by vi4m** [comment]
What's the correct behavior for this case?

**Comment by juniorfoo** [comment]
If you can't see an item because its not in a region that you have visibility to, it probably should not be counted in the dashboard widgets.

**Comment by vi4m** [comment]
sounds like an "easy" task (filter-out regions using Object Manager) - but we have to check it - @romcheg  can you estimate amount of work / what to change?

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group
