### ISSUE TITLE
FieldError at /networks/ipaddress/export/

### ISSUE THREAD

**Issue by diedriko** [allegro/ralph#3304]
When trying to export  ip addresses to a file (any kind of file), python script yields an error
Invalid field name(s) given in select_related: 'base_object'. Choices are: ethernet, network
Exception Location: 	/opt/ralph/ralph/lib/python3.4/site-packages/django/db/models/sql/compiler.py in get_related_selections, line 754

**Comment by romcheg** [comment]
Closing a stale issue. If it is still relevant, please re-open it or start a topic at  Ralph forum: https://ralph.discourse.group

**Comment by SuperChaw** [comment]
Is that this issue closed?
But when i test to export ip, the 500 error in web still occurs again.
The logs:
'base_object'. Choices are: ethernet, network Exception Location: /opt/ralph/ralph/lib/python3.4/site-packages/django/db/models/sql/compiler.py in get_related_selections, line XXX
