### ISSUE TITLE
Add cloud project issue on Ralph3

### ISSUE THREAD

**Issue by asdfII** [allegro/ralph#3316]
![image](https://user-images.githubusercontent.com/4301280/46240751-b44e8180-c3de-11e8-89f8-b540bcf483bc.png)
![image](https://user-images.githubusercontent.com/4301280/46240775-3ccd2200-c3df-11e8-87e0-f5c816d4b818.png)

My env:
CentOS 6.9
Python 3.6.6
Ralph 3

Can't fill out and finish the form.

**Comment by vi4m** [comment]
@romcheg

**Comment by Blejwi** [comment]
Hi @asdfII,

Originally all Cloud Models are intended to be created automatically by synchronization with OpenStack (or other cloud providers). [Link to documentation](https://ralph-ng.readthedocs.io/en/latest/installation/configuration/#synchronization-with-openstack).

Could you please describe your use case -- why do you need to add Cloud Project manually?

**Comment by asdfII** [comment]
Hi Damian,

I have some vms on AWS and Alibaba cloud.
Could you please give me a hand to deal with the case?


Thanks.
BR

**Comment by Blejwi** [comment]
Hi @asdfII,

Unfortunately, we don't have synchronization facilities for mentioned cloud providers.
Best way to handle this case is to write your own synchronization.

There are two ways to achieve this:
- First one is to write full synchronization management command and run it periodically (in CRON probably). You can use this OpenStack synchronization as an example: https://github.com/allegro/ralph/blob/ng/src/ralph/virtual/management/commands/openstack_sync.py
- The second way is to write driver for real-time synchronization. Here is recent PR which introduces cloud synchronization in Ralph: https://github.com/allegro/ralph/pull/3255.
After the driver is created you need to setup your cloud provider (AWS or Alibaba) to send a request to specific URL in Ralph `/virtual/cloudsync/<cloud_provider_id>/`. There is also a PR under development, that allows keeping encrypted authentication details for cloud providers in Database: https://github.com/allegro/ralph/pull/3329

In either case we will accept your contribution into Ralph.
If you need any further help feel free to ask 😃
