### ISSUE TITLE
Building Docker image interrupted due to missing python executable

### ISSUE THREAD

**Issue by knoppi** [allegro/ralph#3334]
With the most recent version of Ralph (pulled october 31st) I encountered problems during the build process.
 docker build .
gets interrupted in line 27:
`RUN $SCRIPTS_PATH/provision_js.sh`

In that line, among other packages, gyp is installed. That requires python with an executable called `python` or `python27`. To my understanding gyp does not run with python3. So I added a line before
`RUN apt-get install -y python2.7 && ln -s /usr/bin/python27 /usr/bin/python`

I'm sure that's not the most elegant way but I could not figure out what commit created this behaviour. 

This happened on a machine where I created the image from scratch. On a second machine I already had a working installation that I wanted to migrate. I, hence, also pulled the latest version there and rebuilt the image. That, in turn, worked without errors. Only the layers afterwards seemed to be rebuilt.

**Comment by romcheg** [comment]
Docker images were re-done completely and are now available pre-built at DockerHub:

- https://hub.docker.com/r/allegro/ralph
- https://hub.docker.com/r/allegro/ralph-static-nginx
