### ISSUE TITLE
components subpage for backoffice assets

### ISSUE THREAD

**Issue by diedriko** [allegro/ralph#3341]
Hi,
Couldn't it be possible to add a components subpage for the back office assets conform the data center assets?
This would greatly reduce the categorization of our assets either they are data center based or back office.

**Comment by vi4m** [comment]
Yes, it's something we want to develop. No timeline for now, though.

**Comment by vi4m** [comment]
If it make it easier, we have models ready. There is just GUI missing in Back Office form.

**Comment by diedriko** [comment]
Can we already have a preview?

**Comment by didierm** [comment]
@vi4m Anything we can help with ?

**Comment by vi4m** [comment]
can you code? :)

**Comment by didierm** [comment]
PHP4 ? Sure thing !
;)

**Comment by romcheg** [comment]
At the moment we have no plans to do that as a maintainers team. Any contributions are welcome.
