### ISSUE TITLE
Static files

### ISSUE THREAD

**Issue by emil246** [allegro/ralph#3371]
### Steps to reproduce

Fresh installation by guide https://ralph-ng.readthedocs.io/en/latest/installation/installation/
Do not serve static files.
### Expected behavior

Correct load static files in prod

### Actual behavior

The same symptoms
https://github.com/allegro/ralph/issues/2978

### Environment

* Ralph version: ?
* Operating system: Ubuntu 18.04
* Method of installation: Deb package

**Comment by vi4m** [comment]
@romcheg why is that?

**Comment by vi4m** [comment]
@emil246 did you use nginx?

**Comment by emil246** [comment]
@vi4m yes, we use nginx.

**Comment by szymi-** [comment]
https://ralph-ng.readthedocs.io/en/latest/installation/installation/#nginx-configuration - is this the configuration you use? Did you restart nginx to load the configuration? Did you link the "default" site to sites-enabled (it should be enabled by default if you followed the howto step by step):

    $ sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

When installing ralph-core package by apt, you should see this line in the output: 

    Collecting django static files...
    Static files collected successfuly.

Was this message displayed?

You should have STATIC_ROOT set in /etc/ralph, like so: 

    $ sudo grep STATIC_ROOT -r
    ralph.conf:STATIC_ROOT=/usr/share/ralph/static

If the above is ok and static files are still not served, try to collect staticfiles manually and then restarting nginx:

    $ sudo ralphctl collectstatic
    $ sudo systemctl restart nginx.service

If the problem persists after the above, please review the log files mentioned here https://ralph-ng.readthedocs.io/en/latest/installation/installation/#troubleshooting - maybe there are some useful error messages there.

**Comment by szymi-** [comment]
And one more last thing: when you connect to ralph, do you connect to port 80 or 8000 (assuming the configuration from the tutorial)? If you connect to port 8000 (http://<ralph_installation_address>:8000), you are not actually connecting to nginx, only to gunicorn. You should connect to nginx via port 80.

**Comment by emil246** [comment]
@szymi- I used port 8000, on port 80 static files is served. Thanks to all!

**Comment by tkuther** [comment]
The `ralphctl collectstatic` step seems missing in the docker build's init-ralph.sh, too.

**Comment by szymi-** [comment]
It is not required. Docker container has ralph installed from deb package. The package contains static files. However gunicorn, which is used to serve the app, does not serve the files. A nginx or other Web server instance is required for that. See the docker/docker-compose.yml file for reference.

**Comment by tkuther** [comment]
Well, the ralph-static volume mounted under /usr/share/ralph/static also gets mounted to NGINX container under /opt/static - but it's empty at first, causing 404 on NGINX side, of course.

Kubernetes manifest used (derived from your docker-compose.yml): https://gist.github.com/tkuther/eeb7d4c3dc536fc28250f3a91beef179

**Comment by szymi-** [comment]
Static files are present in the allegro/ralph image. Are you sure nothing is missing in your manifest? Here's some output from freshly started container using docker-compose.yml from the repo:

```
ralph/docker$ docker-compose rm
Going to remove docker_web_1, docker_inkpy_1, docker_db_1, docker_nginx_1, docker_redis_1
Are you sure? [yN] y
Removing docker_web_1   ... done
Removing docker_inkpy_1 ... done
Removing docker_db_1    ... done
Removing docker_nginx_1 ... done
Removing docker_redis_1 ... done

ralph/docker$ docker-compose up -d
Creating docker_nginx_1 ... done
Creating docker_db_1    ... done
Creating docker_redis_1 ... done
Creating docker_web_1   ... done
Creating docker_inkpy_1 ... done

ralph/docker$ docker exec -it docker_web_1 find /usr/share/ralph/static | head
/usr/share/ralph/static
/usr/share/ralph/static/elements
/usr/share/ralph/static/elements/badge-input.html
/usr/share/ralph/static/elements/tool-tip.html
/usr/share/ralph/static/elements/elements-min.53f2804efbec.html
/usr/share/ralph/static/elements/auto-complete.135e16624c5d.html
/usr/share/ralph/static/elements/html-echo.html
/usr/share/ralph/static/elements/auto-complete.html
/usr/share/ralph/static/elements/tool-tip.44bd527a23e5.html
/usr/share/ralph/static/elements/elements-min.html

ralph/docker$ curl -s http://localhost/static/admin/css/login.css | head
/* LOGIN FORM */

body.login {
    background: #eee;
}

.login #container {
    background: white;
    border: 1px solid #ccc;
    width: 28em;

ralph/docker$ curl -I http://localhost/static/admin/css/login.css 
HTTP/1.1 200 OK
Server: nginx/1.15.8
Date: Wed, 06 Feb 2019 09:51:54 GMT
Content-Type: text/css
Content-Length: 940
Last-Modified: Fri, 01 Feb 2019 17:19:24 GMT
Connection: keep-alive
ETag: "5c547f9c-3ac"
Expires: Thu, 06 Feb 2020 09:51:54 GMT
Cache-Control: max-age=31536000
Pragma: public
Cache-Control: public
Accept-Ranges: bytes

```

**Comment by tkuther** [comment]
Ah, you're right. My issue is specific to Kubernetes then.

While docker copies existing files from the container to the host volume upon container initialization, Kubernetes does not. So /usr/share/ralph/static ends up being empty.
