### ISSUE TITLE
ADD new field "phone number" in user list

### ISSUE THREAD

**Issue by look77** [allegro/ralph#3397]
It seems to me it will be good idea to add new field in User list/personal info  with phone number. If this field will be visible in USER LIST the potential user have clear view for contact details every user. 
Now  we can see phone number only in SimCard, but not everyone have a phone number from company.

Otherwise, I have Sim Card assigned to user, but in 
User list/"user"/Additional info       **-I don't see it.**

#
Environment
Ralph version: 20190111.1
Operating system: ubuntu 18.04 minimal/server on a VM, architecture: amd64
Method of installation: Deb package

**Comment by romcheg** [comment]
Users may have multiple sim cards assigned. Frankly, the list of users is not meant to be used by regular users for looking for contact information but rather to manage access settings for the assets.
