### ISSUE TITLE
After deploying from  container  with docker-compose

### ISSUE THREAD

**Issue by djkormo** [allegro/ralph#3417]
### Steps to reproduce

Login to

https://labs.play-with-docker.com

Cloning this repo 

git clone https://github.com/allegro/ralph.git
cd cd ralph/docker/

docker-compose up -d 

After deploying from  container  with docker-compose and  using credentials ralph/ralph
I have error 500

In container log of web app 

django.db.utils.ProgrammingError: (1146, "Table 'ralph_ng.accounts_ralphuser' doesn't exist")

### Environment

https://labs.play-with-docker.com

**Comment by romcheg** [comment]
You need to run `docker-compose run web init`. I'm working on the documentation for this. Please let me know if it helps.

**Comment by djkormo** [comment]
After using docker-compose run web init.

I have  docker_nginx_1 restarting all the times .
$ docker-compose ps
      Name                    Command                 State               Ports
----------------------------------------------------------------------------------------
docker_db_1        docker-entrypoint.sh mysql ...   Up           3306/tcp, 33060/tcp
docker_nginx_1     nginx -g daemon off;             Restarting
docker_redis_1     docker-entrypoint.sh redis ...   Up           0.0.0.0:32768->6379/tcp
docker_web_run_1   /var/local/ralph/docker-en ...   Up

Workaround

docker-compose down
and next
docker-compose up


$ docker-compose  ps
     Name                   Command               State            Ports
---------------------------------------------------------------------------------
docker_db_1      docker-entrypoint.sh mysql ...   Up      3306/tcp, 33060/tcp
docker_inkpy_1   /bin/sh -c supervisord -n        Up
docker_nginx_1   nginx -g daemon off;             Up      0.0.0.0:80->80/tcp
docker_redis_1   docker-entrypoint.sh redis ...   Up      0.0.0.0:32769->6379/tcp
docker_web_1     /var/local/ralph/docker-en ...   Up      0.0.0.0:32770->8000/tcp

**Comment by romcheg** [comment]
@djkormo so basically restarting nginx container helped, didn't it?

**Comment by djkormo** [comment]
Yes.

**Comment by LateSong** [comment]
Hey, my question is the same as this one. I tried running docker-compose run --rm web ini’, but I also reported an error here, showing the error 'django.db.utils.OperationalError: (1050, "Table 'accounts_ralphuser' already exists")’

* docker version: 18.09.3
* Ralph version: 20190306.1
* Operating system: Deabian9.8
* Method of installation: docker-compose

**Comment by skrbx** [comment]
@LateSong try without --rm option
