### ISSUE TITLE
Modifying datacenterasset view

### ISSUE THREAD

**Issue by CaptainSifff** [allegro/ralph#3419]
Hi all,
what is the preferred way to modify the datacenterasset view, e.g. at
http://example.org/data_center/datacenterasset/ 
I'd like to have less/other fields  visible.

**Comment by romcheg** [comment]
@CaptainSifff this seems to be the perfect topic to post on Ralph's forum. Could you please do that here: https://ralph.discourse.group

**Comment by CaptainSifff** [comment]
Great! I didn't know about that.
