### ISSUE TITLE
django.db.utils.OperationalError: (1054, ...

### ISSUE THREAD

**Issue by rdarioc** [allegro/ralph#3461]
### Steps to reproduce

I've added ralph repos and ran apt-get update and apt-get upgrade.

Original installation was made manually with ralph 3

Python 3.6.8
/opt/ralph/ralph-core/bin/django-admin --version
1.8.19
 DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
full log available on https://xsnippet.org/363996

### Expected behaviour

I would have expected ralph to keep working as usual.

### Actual behaviour

Afterwards I get Server Error (500) to almost every menu option I select  and on ralph.log I get

  File "/opt/ralph/ralph-core/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'assets_asset.start_usage' in 'field list'")

### Environment

Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                              Version               Architecture          Description
+++-=================================-=====================-=====================-========================================================================
ii  ralph-core                        20190527.1            amd64                 Ralph is an DCIM/CMDB - asset management for Data Centers/ Back Office.

* Ralph version: 
* Operating system: Ubuntu 18.04.2 LTS
* Method of installation: Deb package? Manual installation? Docker? 
See above on how to reproduce issue.

**Comment by rdarioc** [comment]
Issue has been fixed. Documented here [https://ralph.discourse.group/t/upgrade-via-apt-issue/67](url). I would recommend the execution of the migration script at the end of the installation scripts of ralph on Ubuntu from repo, just to make sure all structures are aligned.

**Comment by rdarioc** [comment]
Just a recommendation to add the migration script at the end of the installation scripts for the installation of ralph from repo on Ubuntu.

**Comment by vi4m** [comment]
Thanks @rdarioc for reporting this. 

We will try to improve upgrading experience, https://github.com/allegro/ralph/issues/3463
