### ISSUE TITLE
Question: Integration of fusioninventory (or other software) as discovery agent?

### ISSUE THREAD

**Issue by fthommen** [allegro/ralph#3490]
In issue #3131 a possible integration ralph <-> fusioninventory had been suggested. Has this happened in the meantime or does ralph integrate other discovery agents (namely for inventorizing installed software)?

**Comment by CaptainSifff** [comment]
To my knowledge ralph-cli is still the only thing that is available. I had written my own hardware discovery wrappers here: https://ralph.discourse.group/t/customization-stories-and-tricks/27

**Comment by vi4m** [comment]
As said before, we provide open API, and ralph-cali to allow custom integrations. 
We don’t have plans to write discovery agents by ourselves.

@fthommen you can also ask Fusion Inventory staff , if they have plans to integrate with Ralph
