### ISSUE TITLE
how to modify hardware attributes 

### ISSUE THREAD

**Issue by ilovefood2** [allegro/ralph#3515]
I followed instructions and installed ralph as default,
everything seems to be ok, while i browse the UI, and I want to make change of datacentre>hardware attributes, but i can't seems to find a way.

for example, i want to remove barcode, location columns and add some other columns as needed.
![image](https://user-images.githubusercontent.com/4293869/73587822-87a4f100-448e-11ea-9ca5-742c7dea5e4c.png)

I know there are customized fields i could use, but those fields don't show in the first page as columns which is the way I prefer. 

is there any way to accomplish it?

thanks

**Comment by vi4m** [comment]
The only way to hide fields, is to modify permission settings (removing access to the given field)

**Comment by vi4m** [comment]
And you can add new fields with “custom fields”, but it won’t modify default columns(currently there is no way to customize columns view on listing). 

Hope it helps.
