### ISSUE TITLE
demo login credentials are not working

### ISSUE THREAD

**Issue by f31n** [allegro/ralph#3524]
hey there, i just wanted to have a look into ralph but found following error message:

"Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive."

when using on https://ralph-demo.allegro.tech
with "ralph" / "ralph"

as https://ralph.allegro.tech/ shows

is there a way to fix that?

thanks a lot.

**Comment by ar4s** [comment]
Thank you for reporting. Try now.

**Comment by f31n** [comment]
working again, thank you very much.

**Comment by aksharbarot** [comment]
It is not working now.

Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.

**Comment by funyfizik** [comment]
Not working too(
