### ISSUE TITLE
Service environments need sort by ascending

### ISSUE THREAD

**Issue by Geqsogen** [allegro/ralph#3540]
### Steps to reproduce

http://localhost/assets/serviceenvironment/
or
Settings -> Service environments

### Expected behavior

Sort list by ascending

### Actual behavior

Displays a list of uncomfortable

### Environment

* Ralph version: 20200521.1
* Operating system: Ubuntu 18.04.4 LTS
* Method of installation: Deb package

**Comment by romcheg** [comment]
@Geqsogen the patch is posted for a review and is likely to land today. I would be reluctant to make a new release just to fix the ordering in one place. Please give us a few days so we can land a few more changes and then release a new version of Ralph.
