### ISSUE TITLE
Ralph open-source app details

### ISSUE THREAD

**Issue by ZeroSum24** [allegro/ralph#3545]
Recently delighted to come across Ralph, and might be looking to contribute in the future.

I seen in the [Fosdem 2016](https://www.youtube.com/watch?v=j_OQxIoCPgw) talk that there was a demo of and some discussion about an open-source app that was produced to complement Ralph.

Was this app released? If so where might I find it, and is it still supported by yourselves?

**Comment by ZeroSum24** [comment]
Replicated this question on Glitter IM, feel free to close

**Comment by romcheg** [comment]
@ZeroSum24 the app was never released and was put off the roadmap as the priorities had shifted.

**Comment by ZeroSum24** [comment]
@romcheg thanks for getting back to me, that's good to know
