### ISSUE TITLE
Not able to login on the demo interface.

### ISSUE THREAD

**Issue by rajeevsonkhia** [allegro/ralph#3569]
Not able to login on the demo interface
https://ralph-demo.allegro.tech/ using ralph /ralph

its giving an error : 
Please enter the correct username and password for a staff account. Note that both fields may be case-sensitive.

**Comment by romcheg** [comment]
@MarekBleschke it should be possible to resolve this kind of issues by revoking write permissions to Ralph’s DB user. Changing password won’t be possible after that. There is a chance it will be necessary to migrate to Postgres to set per-column permissions

**Comment by dadayechong** [comment]
Not able to login on the demo 
——————
+1

**Comment by MarekBleschke** [comment]
> Not able to login on the demo
> ——————
> +1

Hi @dadayechong. Resetted password. Logging to ralph-demo should be working.

**Comment by funyfizik** [comment]
Cannot login too...

**Comment by MarekBleschke** [comment]
Hi @funyfizik, password is back to default.
Also we've set periodic reset of password (once per hour), so this problem should be less troublesome in future :)

**Comment by funyfizik** [comment]
thx!
