### ISSUE TITLE
Hello guys, I have issue with Databases and Disk Shares 

### ISSUE THREAD

**Issue by Free6838** [allegro/ralph#3587]
can't add databases and DiskShares, because of no form to fill 

![image](https://user-images.githubusercontent.com/18496000/99796464-f4d16200-2b46-11eb-9ea1-3f666cf6d1af.png)
![image](https://user-images.githubusercontent.com/18496000/99796988-dae44f00-2b47-11eb-9fdc-322bc389a6b9.png)
![image](https://user-images.githubusercontent.com/18496000/99797034-f2233c80-2b47-11eb-8922-c92d4de74a34.png)

**Comment by vi4m** [comment]
We don't support adding it manually - you can do it through the API.
