### ISSUE TITLE
Installation on CentOS 7

### ISSUE THREAD

**Issue by Omegabug** [allegro/ralph#3607]
### Steps to reproduce

I followed this guide #3093 to install RALPH on a VM, I got until `make install`l where I ran into a problem.

### Expected behavior

Make install should compile the code into binaries in a timely fashion.

### Actual behavior

Error due to dependency conflict:
-On oslo.utils 3.7.0 where it tells me it wants version 3.16.
-On keystoneauth1 2.3.0 where it tells me it wants version 2.10.0.
So I change openstack.txt to reflect those changes but I then get the same problem:
-On stevedore 1.12.0 where it tells me it wants version 1.16.0 (Due to the change in keystoneauth1).
After changing those values, my make install doesn't crash and advances until it gets stuck and doesn't change for hours.

### Environment

* Ralph version: 2.3.1
* Operating system: CentOS 7
* Method of installation: Manual installation
* Python: 3.6.8
* Pip: 21.0.1

**Comment by spearcrow** [comment]
I also experienced the same problem when installing Ralph on Centos 7

what I did was change the pip version to version 19.3.1 and I managed to run the installation process

**Comment by Omegabug** [comment]
Thanks, though in the end I installed Ralph with docker it was easier and quicker.
