### ISSUE TITLE
ralph-demo.allegro.tech login isn't working

### ISSUE THREAD

**Issue by Carlos-SS-PMI** [allegro/ralph#3611]
Hi all!
I want to show to my coleagues your excellent application, but online demo isn't working at: ralph-demo.allegro.tech
Login isn't working with "ralph" user and password.

Please, can you fix it?

Thanks!

**Comment by ttsyliuryk** [comment]
Having the same issue with the demo, is there an ETA for a fix?

**Comment by Carlos-SS-PMI** [comment]
Now is working. Thanks!
