### ISSUE TITLE
Test demo reports 500 error when login

### ISSUE THREAD

**Issue by sunnyBob** [allegro/ralph#3623]
### Steps to reproduce

input user(ralph) and password(ralph) to login

### Expected behavior
login successfully and see the main page

### Actual behavior
show "Server Error (500)" after login button clicked

### Environment
test demo (https://ralph-demo.allegro.tech/)

* Ralph version: 
* Operating system: 
* Method of installation: Deb package? Manual installation? Docker?

**Comment by szymi-** [comment]
Thanks for reporting this issue @sunnyBob. I fixed Ralph Demo, it should work now.

**Comment by sunnyBob** [comment]
Yes, It works now
