### ISSUE TITLE
Suspisious commit

### ISSUE THREAD

**Issue by romcheg** [allegro/ralph#3667]
Is there any particular reason why an unverified commit 04abcc9e78136ac1fb1ac119e2c660ee3baa396d was pushed without any code review into the main branch? I propose to revert it and to follow the regular procedure since the change does not seem to be urgent and there are multiple potential improvements that could be noticed during the code review.

**Comment by vi4m** [comment]
Yeah, it was an accident. We were testing codespaces to simplify setting up development environment. It works great, but has caveats:

* you don't work on separate fork, but on the **origin** (similar to Stash) - master is the **origin** master
* commiting to master, pushes the changes immediately
* we should keep master branch protected, but the deployment scripts don't allow it at the moment

It has been already reverted sice them, we will reintroduce codespaces soon.
