### ISSUE TITLE
Lacking input sanitization in Cluster name leads to persistent XSS

### ISSUE THREAD

**Issue by floppywiggler** [allegro/ralph#3669]
It is possible to perform a persistent XSS attack in the "Name"-field of any cluster that is created. This will then be executed when rendering for example the "Network->IP addresses" page.

### Steps to reproduce

Create a new cluster, in the name field, add any javascript code you'd like to execute. As a demo: `<script>alert(XSS)</script>`. Save the cluster.
Now navigate to for example Networks and IP-addresses on https://WEBROOT/networks/ipaddress/

Once the page is loaded, you will be prompted with an alert, verifying we have an XSS vulnerability.

### Expected behavior

Input sanitzation should be implemented in all "name" fields that does not allow special characters or code.

### Actual behavior

No cleaning of the input is done, any code is accepted and executed.

### Environment

Any version and environment. The demo instance is also vulnerable.

* Ralph version: 
* Operating system: 
* Method of installation: Deb package? Manual installation? Docker?

**Comment by hipek8** [comment]
Fixed in version 20211220.1
