### ISSUE TITLE
 docker_web_run not working

### ISSUE THREAD

**Issue by stsonmez** [allegro/ralph#3837]
### Environment

* Ralph version: latest
* Operating system: Ubuntu 22.04.4 LTS
* Method of installation: Deb package? Manual installation? Docker? -> Deb package

![1](https://github.com/user-attachments/assets/855f2184-49bd-4fc4-bd88-f1835a017f49)
![2](https://github.com/user-attachments/assets/5cc54208-c38e-421a-9b21-a5fef0cec33f)
![3](https://github.com/user-attachments/assets/bc4aafce-91b5-4413-a6e7-02c14f0b0240)

Hello, I did all the steps but the web portal is not coming because the docker service is not running as "Exited (1) 2 minutes ago docker_web_run". I kindly ask for your help.

**Comment by antropy833** [comment]
Same issue here

**Comment by matyldv** [comment]
Hi, we have published new version (20240830.2), please try again😄
