### ISSUE TITLE
How to add a rack?

### ISSUE THREAD

**Issue by adubkov** [allegro/ralph#734]
Hello!

First of all Thanks for so cool asset management system! :)

But I've one problem with it, due to lack of documentation. I can't find any info about how to add rack in "admin" panel so that it show at ui/racks/.
I tried next:
1. Add 'device model' named '42U Rack' with type 'rack'
2. Add 'device' named 'Rack C14-1' with appropriate 'device model' and save it.

But it's nothing show ui/racks/

Please help!

BTW, I don't understand why i can select device type 'data center' in 'device model', if i can add DC on 'Data centers' admin page and then it's not show in device list. Could you slightly explain why it's made so?

**Comment by rmgainey** [comment]
I have tried to follow these steps, but it requires a service to save successfully. What is the service it's asking for. I have defined one in the ralph assets section of the admin page but it is not available in the drop down menu in Admin > Discovery > Add device > Service ???

**Comment by rmgainey** [comment]
Never mind, I found the fix. https://github.com/allegro/ralph/issues/1250
