### ISSUE TITLE
No venture roles configured for Zabbix integration.

### ISSUE THREAD

**Issue by zhigoo** [allegro/ralph#968]
after config follow the doc
i run  
root@debian:~# ralph zabbixregister
No venture roles configured for Zabbix integration.

and i have creat  venture roles  in ci

![qq20140710111328](https://cloud.githubusercontent.com/assets/1224561/3534079/3494cc74-07e0-11e4-8582-117807201653.png)

**Comment by vi4m** [comment]
Ralph 2 is now unsupported. If unsure - i recommend to upgrade to the Ralph 3 version.
