### ISSUE TITLE
'ascii' codec can't encode characters in position 6-10: ordinal not in range(128)

### ISSUE THREAD

**Issue by satoruf** [allegro/ralph#973]
I create a venture role with property symbol name in Japanese (ja_JP.UTF-8).
After that, info page (http://192.168.xxx.xxx:8000/ui/ventures/ossl_dev/info/1?) shows property symbol name in Japanese properly, but click the update button under the propetrty list, got an error "UnicodeEncodeError at /ui/ventures/ossl_dev/info/1" as below;

'ascii' codec can't encode characters in position 6-10: ordinal not in range(128)
Request Method:	POST
Request URL:	http://192.168.xxx.xxx:8000/ui/ventures/ossl_dev/info/1
Django Version:	1.4.13
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode characters in position 6-10: ordinal not in range(128)
Exception Location:	/home/ralph/local/lib/python2.7/site-packages/django/forms/forms.py in _clean_fields, line 289
Python Executable:	/home/ralph/bin/python
Python Version:	2.7.3
Python Path:	
['/home/ralph/bin',
 '/home/ralph/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/home/ralph/local/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/home/ralph/project/src',
 '/home/ralph/lib/python2.7',
 '/home/ralph/lib/python2.7/plat-linux2',
 '/home/ralph/lib/python2.7/lib-tk',
 '/home/ralph/lib/python2.7/lib-old',
 '/home/ralph/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/ralph/local/lib/python2.7/site-packages']

Property type values in Japanese is no problem.
Any suggestions would be appreciated.
Satoru Funai

**Comment by mkurek** [comment]
Detailed info was not provided. Closing.
